contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 128b585b-27b2-4f47-80e6-7398a60bed12
inputs: []
name: AD Test
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0ddc4a0d-36d0-4c9f-8848-c0ed0ef8eeaa
      iscommand: false
      name: ""
      version: -1
    taskid: 0ddc4a0d-36d0-4c9f-8848-c0ed0ef8eeaa
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": -140
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      builtincondition:
      - - left:
            iscontext: true
            value:
              complex:
                root: NextSearch
          operator: isFalse
          right:
            value: {}
      exitCondition: ""
      iscommand: false
      max: 50
      wait: 10
    nexttasks:
      '#none#':
      - "8"
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      attributes:
        simple: ALL
      filter:
        simple: (objectClass=user)
      page-size:
        simple: "5"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0b8a4ce1-d8fe-43be-8a78-85bd8228956e
      iscommand: false
      name: AD Test ad-search-subsequent
      playbookId: 0fb4c595-2e0d-4446-857c-0c84c449e24e
      type: playbook
      version: -1
    taskid: 0b8a4ce1-d8fe-43be-8a78-85bd8228956e
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 265,
          "y": 515
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4d6e3e66-6769-40d0-8908-0d203100d350
      iscommand: false
      name: Push to Exabeam
      type: title
      version: -1
    taskid: 4d6e3e66-6769-40d0-8908-0d203100d350
    timertriggers:
    - action: start
      fieldname: newsla
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 865
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: NextSearch
      stringify:
        simple: "false"
      value:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 794e9ed3-4c37-426d-8c91-2b5fcea911cc
      iscommand: false
      name: Set - NextSearch for loop
      script: Set
      type: regular
      version: -1
    taskid: 794e9ed3-4c37-426d-8c91-2b5fcea911cc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 760,
          "y": 190
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 494e8d2c-c878-480a-83c8-8a4726af4fe1
      iscommand: false
      name: Get AD informations
      type: title
      version: -1
    taskid: 494e8d2c-c878-480a-83c8-8a4726af4fe1
    timertriggers:
    - action: pause
      fieldname: newsla
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 35
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "no"
      key:
        simple: SearchPageCookie
      subplaybook:
        simple: "no"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: 06845c68-56df-4fe7-8a13-7c6cb2f31958
      iscommand: false
      name: DeleteContext - SearchPageCookie
      script: DeleteContext
      type: regular
      version: -1
    taskid: 06845c68-56df-4fe7-8a13-7c6cb2f31958
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 690
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "no"
      key:
        simple: NextSearch
      subplaybook:
        simple: "no"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: 0c71e548-83f4-4be5-8e36-8b87de98be22
      iscommand: false
      name: DeleteContext - NextSearch
      script: DeleteContext
      type: regular
      version: -1
    taskid: 0c71e548-83f4-4be5-8e36-8b87de98be22
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 690
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      csvArray:
        complex:
          accessor: Result
          root: AD
      fileName:
        simple: activedirectory_all.csv
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Export given array to csv file
      id: ac8fc1ff-500a-4b3e-8444-2cbd7c75615b
      iscommand: false
      name: ExportToCSV
      script: ExportToCSV
      type: regular
      version: -1
    taskid: ac8fc1ff-500a-4b3e-8444-2cbd7c75615b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1010
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1245,
        "width": 1090,
        "x": 50,
        "y": -140
      }
    }
  }
