contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 1eb4b7ca-7bd7-4c16-89b2-ee7ca97b9464
inputs:
- description: ""
  key: domain
  playbookInputQuery: null
  required: false
  value:
    simple: commbank.com.au
name: test1
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3a6894c4-fbce-4785-820b-ff2ed02a9f8b
      iscommand: false
      name: ""
      version: -1
    taskid: 3a6894c4-fbce-4785-820b-ff2ed02a9f8b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      domain:
        simple: ${inputs.domain}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Queries a domain in AlienVault OTX.
      id: 016775fd-af7e-4094-8e37-03b75e274b28
      iscommand: true
      name: Domain command
      script: '|||domain'
      type: regular
      version: -1
    taskid: 016775fd-af7e-4094-8e37-03b75e274b28
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ea5fb036-b9c2-40d8-8946-47d1be707099
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: ea5fb036-b9c2-40d8-8946-47d1be707099
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
