contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 09255649-f317-4369-8b6e-365158d33977
inputs: []
name: setandhandleemptytest
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 12960e44-14cd-47e8-8ff8-c50c00b42700
      iscommand: false
      name: ""
      version: -1
    taskid: 12960e44-14cd-47e8-8ff8-c50c00b42700
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: QRadar.StartTime
      value:
        complex:
          accessor: Starttime
          root: QRadar.Events.[0]
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Set a value in context under the key you entered. If no value is entered, the script doesn't do anything.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: a3f37851-fa90-4925-8573-049e54acce98
      iscommand: false
      name: Set
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: a3f37851-fa90-4925-8573-049e54acce98
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 390,
        "x": 40,
        "y": 50
      }
    }
  }
