contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 9244e454-85e5-499a-8f43-58146b42bd3d
inputs: []
name: test_in
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fc564f77-6570-4d38-86d0-d67659dbd4b3
      iscommand: false
      name: ""
      version: -1
    taskid: fc564f77-6570-4d38-86d0-d67659dbd4b3
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Test
      value:
        complex:
          root: ${TestName}
          transformers:
          - args:
              to:
                value:
                  simple: ' -'
            operator: substringTo
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: f30638b5-fee6-43f2-80de-27ef6c6b9f53
      iscommand: false
      name: Set
      script: Set
      type: regular
      version: -1
    taskid: f30638b5-fee6-43f2-80de-27ef6c6b9f53
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 60,
          "y": 200
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${Test}
          operator: isEqualString
          right:
            value:
              simple: P1
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 903da0bc-886f-4615-828b-d63f7315c521
      iscommand: false
      name: Check the Priority
      type: condition
      version: -1
    taskid: 903da0bc-886f-4615-828b-d63f7315c521
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 60,
          "y": 390
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 435,
        "width": 390,
        "x": 50,
        "y": 50
      }
    }
  }
