contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 0b04208c-ae24-48fb-856d-99403d912b8e
inputs: []
name: main-pb
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2a0d7690-33cb-45a5-8360-c8ab0b0e8910
      iscommand: false
      name: ""
      version: -1
    taskid: 2a0d7690-33cb-45a5-8360-c8ab0b0e8910
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 720,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      builtincondition:
      - - left:
            iscontext: true
            value:
              simple: incident.status
          operator: isEqualString
          right:
            value:
              simple: Closed
      exitCondition: ""
      iscommand: false
      max: 110
      wait: 1
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 276dd3e2-71eb-4195-879e-229a63d7ca5a
      iscommand: false
      name: sub-pb
      playbookId: ba00221b-fb94-47aa-865a-5225c0ee2c63
      type: playbook
      version: -1
    taskid: 276dd3e2-71eb-4195-879e-229a63d7ca5a
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 720,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 720,
        "y": 50
      }
    }
  }
