contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 5a3383e6-a01d-4d17-8ac0-80e693468c43
inputs: []
name: sample- zip
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 97869422-8b7f-4878-812f-0125e9766151
      iscommand: false
      name: ""
      version: -1
    taskid: 97869422-8b7f-4878-812f-0125e9766151
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Pls upload the file here
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: attachments
      sender: ""
      title: upload the file
      totalanswers: 0
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: null
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 340d602b-8a0e-4d07-8068-54ece9bbf21e
      iscommand: false
      name: upload the file
      type: collection
      version: -1
    taskid: 340d602b-8a0e-4d07-8068-54ece9bbf21e
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      zipName:
        simple: ${File.Name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Zip a file and upload to war room
      id: ae94c324-94c5-4004-8d8c-4f3f80f515b7
      iscommand: false
      name: zip the file
      script: ZipFile
      type: regular
      version: -1
    taskid: ae94c324-94c5-4004-8d8c-4f3f80f515b7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 445,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
