contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: e5f8a63d-ce84-49a6-87d0-ed408044dae5
inputs: []
name: test communication task
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 34a559cd-bf17-4e38-8fc5-1643ca69e5d8
      iscommand: false
      name: ""
      version: -1
    taskid: 34a559cd-bf17-4e38-8fc5-1643ca69e5d8
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Hi there, shall we continue this investigation?
      cc:
        simple: jingqiao.wang@hotmail.com
      format: ""
      methods:
      - email
      replyOptions:
      - "Yes"
      - "No"
      subject:
        simple: Ask for your inputs
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
        simple: micwang@paloaltonetworks.com
    nexttasks:
      "No":
      - "2"
      "Yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: db4cf0d6-3b1f-46ec-807b-8b84640a6c4c
      iscommand: false
      name: ask via email
      type: condition
      version: -1
    taskid: db4cf0d6-3b1f-46ec-807b-8b84640a6c4c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7f6d7b50-abfd-4105-81b4-aa4798330fe5
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 7f6d7b50-abfd-4105-81b4-aa4798330fe5
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: continue
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 2cbfcb67-38ee-48de-8e81-8e76d77c6d1b
      iscommand: false
      name: continue
      script: Print
      type: regular
      version: -1
    taskid: 2cbfcb67-38ee-48de-8e81-8e76d77c6d1b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 560,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
