contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: c123a83a-1df3-43a0-8117-2ef17a87d1eb
inputs: []
name: Sample Demo Playbook
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3521162a-dbc0-46fc-8ab9-c0f4f61bf2f5
      iscommand: false
      name: ""
      version: -1
    taskid: 3521162a-dbc0-46fc-8ab9-c0f4f61bf2f5
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: cfef4fbb-93bd-4c8b-8b6f-fb3b7afb9ca5
      iscommand: false
      name: Untitled Task
      type: condition
      version: -1
    taskid: cfef4fbb-93bd-4c8b-8b6f-fb3b7afb9ca5
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Yes, its me
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 5edcff4c-d7e4-42c3-8182-cdcf01258741
      iscommand: false
      name: print
      script: Print
      type: regular
      version: -1
    taskid: 5edcff4c-d7e4-42c3-8182-cdcf01258741
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -540,
          "y": 390
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ' it isn''t me'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: cc907925-492b-4e35-847f-7944a9401bd2
      iscommand: false
      name: print
      script: Print
      type: regular
      version: -1
    taskid: cc907925-492b-4e35-847f-7944a9401bd2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 360,
          "y": 410
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 455,
        "width": 1280,
        "x": -540,
        "y": 50
      }
    }
  }
