contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: MSSentinelIncidentValidator Contribution Pack
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 8376d6df-a38f-4a2a-8b70-f4e43db50042
inputs:
- description: ""
  key: hoursago
  playbookInputQuery: null
  required: false
  value:
    simple: "1"
name: MSSentinelIncidentValidator
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 67208cbd-b5c2-4a5f-83f8-ffd83ef195f1
      iscommand: false
      name: ""
      version: -1
    taskid: 67208cbd-b5c2-4a5f-83f8-ffd83ef195f1
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      contextKey:
        simple: refDate
      dateFormat:
        simple: ISO
      hoursAgo:
        simple: ${inputs.hoursago}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Retrieves the current date and time.
      id: 28844722-68d8-4d69-82ea-dca910bda9dc
      iscommand: false
      name: AddDateTimetoContext
      script: GetTime
      type: regular
      version: -1
    taskid: 28844722-68d8-4d69-82ea-dca910bda9dc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      filter:
        complex:
          root: refDateTimeNow
          transformers:
          - args:
              prefix:
                value:
                  simple: 'properties/createdTimeUtc gt '
              suffix: {}
            operator: concat
      limit:
        simple: "100"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Azure Sentinel
      description: Gets a list of incidents from Azure Sentinel.
      id: b1d20158-f8e1-4c58-87c9-d2206ac2826b
      iscommand: true
      name: Get Sentinel ID from reference Time
      script: Azure Sentinel|||azure-sentinel-list-incidents
      type: regular
      version: -1
    taskid: b1d20158-f8e1-4c58-87c9-d2206ac2826b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: AzureSentinel.Incident.ID
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f5347f5a-5f25-4c1f-80a2-fbaa48eeaa3c
      iscommand: false
      name: Are there results
      type: condition
      version: -1
    taskid: f5347f5a-5f25-4c1f-80a2-fbaa48eeaa3c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      body:
        simple: |
          These are the Sentinel Incident Number that were missed.

          ${missingSentinelIncident}
      subject:
        simple: MIssed Sentinel Incident
      to:
        simple: sramesh1@paloaltonetworks.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends an email.
      id: f8cd1030-a06a-4e49-8a19-1713f6d368f9
      iscommand: true
      name: Send Email with missing incident
      script: '|||send-mail'
      type: regular
      version: -1
    taskid: f8cd1030-a06a-4e49-8a19-1713f6d368f9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: ${AzureSentinel.Incident.IncidentNumber}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 5993d529-0e82-4075-8823-d20f1f9e0347
      iscommand: false
      name: searchRelevantXSOARIncident
      playbookId: a568e71f-82fd-4589-848e-f61e09c86222
      type: playbook
      version: -1
    taskid: 5993d529-0e82-4075-8823-d20f1f9e0347
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 4818c38b-753d-4211-87f1-06e6edbdd10b
      iscommand: true
      name: CloseIncident
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 4818c38b-753d-4211-87f1-06e6edbdd10b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${missingSentinelIncident}
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: aff05fb2-0248-48b2-8377-d1b728da6b2a
      iscommand: false
      name: Are there missing Sentinel Incident
      type: condition
      version: -1
    taskid: aff05fb2-0248-48b2-8377-d1b728da6b2a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1290,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
