contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: "Example playbook, this will take images attached (png or jpeg), base64
  encode them to context, create html for those, and send an email with the html body
  containing those images.\n\nIdea being you can insert those images into an email
  body or even an Ask Task.   Each step in the playbook has details explaining what
  it's doing. "
id: a755380a-26f4-48e6-8944-c57d75786393
inputs: []
name: Base64 Images Playbook
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 158ce968-0954-4ff7-872b-31c055524148
      iscommand: false
      name: ""
      version: -1
    taskid: 158ce968-0954-4ff7-872b-31c055524148
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 65
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        complex:
          accessor: EntryID
          filters:
          - - left:
                iscontext: true
                value:
                  simple: File.Extension
              operator: inList
              right:
                value:
                  simple: png,jpg,jpeg
          root: File
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Encode a file as base64 and store it in context
      id: f6a788bf-716a-4254-85ac-670520b54e8d
      iscommand: false
      name: Base64 Encode - png or jpeg
      script: 25b3a0e5-547a-42fe-8932-5f7969dfca15
      type: regular
      version: -1
    taskid: f6a788bf-716a-4254-85ac-670520b54e8d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 225
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      images_base64:
        simple: ${Base64Files}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'This automation creates image tags from base64 encoded images
        in context.  '
      id: 15d212f0-9661-4d97-863f-edc56d3dc6f0
      iscommand: false
      name: Create html links with base64 encoded images
      script: 37a9e1d4-b046-4b79-8ed3-55875c9891cd
      type: regular
      version: -1
    taskid: 15d212f0-9661-4d97-863f-edc56d3dc6f0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 400
        }
      }
  "5":
    continueonerrortype: ""
    form:
      description: Where do you want to send this?
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Email
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: Email to send to
        type: shortText
      sender: ""
      title: Email Address
      totalanswers: 0
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Email Address
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: false
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fa008ffb-6b9f-4bad-8019-39381efc7da2
      iscommand: false
      name: Ask User for an Email Address
      type: collection
      version: -1
    taskid: fa008ffb-6b9f-4bad-8019-39381efc7da2
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      htmlBody:
        complex:
          root: ImageHTMLLinks
          transformers:
          - operator: uniq
          - args:
              separator:
                value:
                  simple: <br>
            operator: join
          - args:
              prefix:
                value:
                  simple: Here are some cool images base64 encoded!<br><br>
              suffix:
                value:
                  simple: <br>
            operator: concat
      subject:
        simple: Base64 Images from XSOAR
      to:
        simple: ${Email Address.Answers.0}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends an email.
      id: 1920d75f-d757-4d5f-801c-9aea8dc25871
      iscommand: true
      name: Send Email with Images in HTML Body
      script: '|||send-mail'
      type: regular
      version: -1
    taskid: 1920d75f-d757-4d5f-801c-9aea8dc25871
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 225
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      closeNotes:
        simple: Email sent
      closeReason:
        simple: Resolved
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: fd5cefa6-0eda-44c1-8e5b-77b0f403cc5b
      iscommand: true
      name: 'Fin. '
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: fd5cefa6-0eda-44c1-8e5b-77b0f403cc5b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 400
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 445,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
