contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 8ce2a111-fbbb-45ae-82af-6871b519dced
inputs:
- description: ""
  key: loopcount
  playbookInputQuery: null
  required: false
  value:
    simple: "1"
name: Forlooptesting
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fa221810-86a7-449d-861c-c868747b1e08
      iscommand: false
      name: ""
      version: -1
    taskid: fa221810-86a7-449d-861c-c868747b1e08
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: loopcount=
      value:
        simple: ${inputs.loopcount}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: fb7bd20a-0b32-4ed9-89a3-fb350bc6935c
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: fb7bd20a-0b32-4ed9-89a3-fb350bc6935c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: loopcount
      value:
        complex:
          root: loopcount
          transformers:
          - args:
              by:
                value:
                  simple: "1"
            operator: addition
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 2a553c35-e370-46b9-8f61-c826066596f1
      iscommand: false
      name: increment
      script: Set
      type: regular
      version: -1
    taskid: 2a553c35-e370-46b9-8f61-c826066596f1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "2"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: 74e668c7-6f87-400c-80af-4a0283792de4
      iscommand: false
      name: Sleep
      script: Sleep
      type: regular
      version: -1
    taskid: 74e668c7-6f87-400c-80af-4a0283792de4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 590,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
