contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 7d062158-8fdd-491e-8fbc-d1e695714eed
inputs: []
name: Test - Playbook Execution
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 60b2b041-12ca-4ec1-8ef7-61916de58135
      iscommand: false
      name: ""
      version: -1
    taskid: 60b2b041-12ca-4ec1-8ef7-61916de58135
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: true
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "30"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds.
      id: 4b490fc3-dab6-45a3-8b59-8722edb0632b
      iscommand: false
      name: Sleep
      script: Sleep
      type: regular
      version: -1
    taskid: 4b490fc3-dab6-45a3-8b59-8722edb0632b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -270,
          "y": 230
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "30"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds.
      id: b467d3e7-dce8-4756-8257-391b83e1ef8e
      iscommand: false
      name: Sleep
      script: Sleep
      type: regular
      version: -1
    taskid: b467d3e7-dce8-4756-8257-391b83e1ef8e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 600,
          "y": 240
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 285,
        "width": 1250,
        "x": -270,
        "y": 50
      }
    }
  }
