contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: ac799836-d78d-4112-8825-ba7034d0a665
inputs: []
name: CheckIPinRange
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 76700b36-73ae-4c22-85d4-8edaf1c31b6b
      iscommand: false
      name: ""
      version: -1
    taskid: 76700b36-73ae-4c22-85d4-8edaf1c31b6b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      IPAddress:
        simple: ${IPAddress}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 19f2138d-d12c-4edd-8c83-09cb39418364
      iscommand: false
      name: ValidateIPIsInInternalSubnets
      playbookId: 90314995-b07b-4736-8c32-7e223ed0ec2a
      type: playbook
      version: -1
    taskid: 19f2138d-d12c-4edd-8c83-09cb39418364
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: BlocklistIP
      value:
        complex:
          accessor: Address
          filters:
          - - left:
                iscontext: true
                value:
                  simple: IP.InRange
              operator: isEqualString
              right:
                value:
                  simple: "no"
          root: IP
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 585e5a7f-7cc2-4564-84b3-990bcd4fdca7
      iscommand: false
      name: Store the IP to be blocked
      script: Set
      type: regular
      version: -1
    taskid: 585e5a7f-7cc2-4564-84b3-990bcd4fdca7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 460
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 505,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
