contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 99767e53-0ad7-472f-81d5-9e569b157a28
inputs:
- description: ""
  key: Data
  playbookInputQuery: null
  required: false
  value:
    simple: ${ParseExcel.[0]}
name: Set Incident Data
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cbdb68ea-405f-4f40-83f9-0d24ba32d779
      iscommand: false
      name: ""
      version: -1
    taskid: cbdb68ea-405f-4f40-83f9-0d24ba32d779
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 20
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: violationid:${inputs.Data.ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Searches Demisto incidents. A summarized version of this scrips is avilable with the summarizedversion argument.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: c2db3bb0-d807-4f2d-8702-04934a879a1a
      iscommand: false
      name: search incident with violation id
      script: SearchIncidentsV2
      type: regular
      version: -1
    taskid: c2db3bb0-d807-4f2d-8702-04934a879a1a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      acknowleged:
        complex:
          accessor: Acknowleged}
          filters:
          - - left:
                iscontext: true
                value:
                  simple: ${inputs.Data.ID}
              operator: isEqualString
              right:
                value:
                  simple: ${foundIncidents.CustomFields.violationid}
          root: ${inputs.Data
      closurecategory:
        complex:
          accessor: Closure Category
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.Data.ID
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: ${foundIncidents.CustomFields.violationid}
          root: inputs.Data
      closurenotes:
        complex:
          accessor: Closure Notes}
          filters:
          - - left:
                iscontext: true
                value:
                  simple: ${inputs.Data.ID}
              operator: isEqualString
              right:
                value:
                  simple: ${foundIncidents.CustomFields.violationid}
          root: ${inputs.Data
      id:
        simple: ${foundIncidents.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 37fb5107-8f60-4a25-8708-6ed3f4c23d95
      iscommand: true
      name: update the incident
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 37fb5107-8f60-4a25-8708-6ed3f4c23d95
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 390
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: ${foundIncidents.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 238e7cf2-f01c-48be-82e2-4cfafa57adcd
      iscommand: true
      name: Close investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 238e7cf2-f01c-48be-82e2-4cfafa57adcd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 610
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: foundIncidents
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 69437949-fd51-4f05-8d32-f560644596fc
      iscommand: false
      name: Delete Context Key FoundIncidents
      script: DeleteContext
      type: regular
      version: -1
    taskid: 69437949-fd51-4f05-8d32-f560644596fc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 810
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 885,
        "width": 380,
        "x": 450,
        "y": 20
      }
    }
  }
