contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.5.0
    itemVersion: 2.0.15
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: This playbook queries indicators based on a pre-defined query or results
  from a parent playbook, and adds the resulting indicators to a QRadar Reference
  Set. The Reference Set name must be defined in the playbook inputs.
id: 262b2b2a-37d8-48f8-8525-440e8d42bf21
inputs:
- description: The name of the QRadar black list IP reference set to insert the data
    to.
  key: QRadarBlackListIPReferenceSetName
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: ""
    queryEntity: indicators
    results: null
    runFromLastJobTime: false
  required: false
  value: {}
- description: The name of the QRadar white list IP reference set to insert the data
    in to.
  key: QRadarWhiteListIPReferenceSetName
  playbookInputQuery: null
  required: false
  value: {}
- description: The name of the QRadar watch list IP reference set to insert the data
    in to.
  key: QRadarWatchListIPReferenceSetName
  playbookInputQuery: null
  required: false
  value: {}
name: TIM - QRadar Add IP Indicators_DEMO
outputs: []
quiet: true
sourceplaybookid: TIM - QRadar Add IP Indicators
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c6182ed2-1846-4619-8acd-c9d44e87e5e8
      iscommand: false
      name: ""
      version: -1
    taskid: c6182ed2-1846-4619-8acd-c9d44e87e5e8
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 340,
          "y": -70
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: inList
                    right:
                      value:
                        simple: QRadar,QRadar_v2,QRadar v3
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "34"
      "yes":
      - "31"
      - "32"
      - "37"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9f95b742-8d6c-4e7f-8c90-7e1f2106222d
      iscommand: false
      name: Is QRadarEnabled?
      type: condition
      version: -1
    taskid: 9f95b742-8d6c-4e7f-8c90-7e1f2106222d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 560,
          "y": 270
        }
      }
  "18":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: playbookQuery.value
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: playbookQuery.indicator_type
          operator: isEqualString
          right:
            value:
              simple: IP
      label: "yes"
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "34"
      "yes":
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 09d4fd42-524e-40a9-8d0e-fb395047b503
      iscommand: false
      name: Are there filtered results?
      type: condition
      version: -1
    taskid: 09d4fd42-524e-40a9-8d0e-fb395047b503
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 340,
          "y": 70
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "35"
    note: false
    quietmode: 0
    scriptarguments:
      ref_name:
        simple: ${inputs.QRadarBlackListIPReferenceSetName}
      value:
        complex:
          accessor: value
          filters:
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.CustomFields.tags
              operator: isEqualString
              right:
                value:
                  simple: approved_black
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.indicator_type
              operator: isEqualString
              right:
                value:
                  simple: IP
          root: playbookQuery
          transformers:
          - operator: uniq
      values:
        complex:
          root: inputs.ParentPlaybookIndicators
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Add or update a value in a reference set.
      id: c33a7b2d-4122-4df0-821c-1553ede4e005
      iscommand: true
      name: Add IPs to QRadar black list IP reference set
      script: '|||qradar-update-reference-set-value'
      type: regular
      version: -1
    taskid: c33a7b2d-4122-4df0-821c-1553ede4e005
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 860,
          "y": 800
        }
      }
  "31":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.QRadarBlackListIPReferenceSetName
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              complex:
                accessor: value
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: playbookQuery.CustomFields.tags
                    operator: isEqualString
                    right:
                      value:
                        simple: approved_black
                - - left:
                      iscontext: true
                      value:
                        simple: playbookQuery.indicator_type
                    operator: isEqualString
                    right:
                      value:
                        simple: IP
                root: playbookQuery
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "31"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "34"
      "yes":
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0cacdda0-e0e9-40ae-8a7b-e46d505df02a
      iscommand: false
      name: Is there a Qradar black list IP Reference Set and values?
      type: condition
      version: -1
    taskid: 0cacdda0-e0e9-40ae-8a7b-e46d505df02a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 860,
          "y": 450
        }
      }
  "32":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.QRadarWhiteListIPReferenceSetName
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              complex:
                accessor: value
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: playbookQuery.CustomFields.tags
                    operator: isEqualString
                    right:
                      value:
                        simple: approved_white
                - - left:
                      iscontext: true
                      value:
                        simple: playbookQuery.indicator_type
                    operator: isEqualString
                    right:
                      value:
                        simple: IP
                root: playbookQuery
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "32"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "34"
      "yes":
      - "33"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ac9b1046-ace1-4254-8ba6-6e5c4107ab26
      iscommand: false
      name: Is there a Qradar white list IP Reference Set and values?
      type: condition
      version: -1
    taskid: ac9b1046-ace1-4254-8ba6-6e5c4107ab26
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1600,
          "y": 450
        }
      }
  "33":
    continueonerrortype: ""
    id: "33"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "36"
    note: false
    quietmode: 0
    scriptarguments:
      ref_name:
        simple: ${inputs.QRadarWhiteListIPReferenceSetName}
      value:
        complex:
          accessor: value
          filters:
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.CustomFields.tags
              operator: isEqualString
              right:
                value:
                  simple: approved_white
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.indicator_type
              operator: isEqualString
              right:
                value:
                  simple: IP
          root: playbookQuery
          transformers:
          - operator: uniq
      values:
        complex:
          root: inputs.ParentPlaybookIndicators
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Add or update a value in a reference set.
      id: 86d8fa29-268d-47a5-84eb-9cd2af869f85
      iscommand: true
      name: Add IPs to QRadar white list IP reference set
      script: '|||qradar-update-reference-set-value'
      type: regular
      version: -1
    taskid: 86d8fa29-268d-47a5-84eb-9cd2af869f85
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1600,
          "y": 800
        }
      }
  "34":
    continueonerrortype: ""
    id: "34"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 350e387d-012c-4d53-8796-662ae5622050
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 350e387d-012c-4d53-8796-662ae5622050
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 340,
          "y": 1170
        }
      }
  "35":
    continueonerrortype: ""
    id: "35"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "34"
    note: false
    quietmode: 0
    scriptarguments:
      field:
        simple: tags
      fieldValue:
        simple: SIEM
      indicatorsValues:
        complex:
          accessor: value
          filters:
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.CustomFields.tags
              operator: isEqualString
              right:
                value:
                  simple: approved_black
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.indicator_type
              operator: isEqualString
              right:
                value:
                  simple: IP
          root: playbookQuery
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Adds the SIEM tag to the indicators.
      id: 84c21aa7-44b0-4513-8a28-4ba58ad41e84
      iscommand: true
      name: Add SIEM tag
      script: Builtin|||appendIndicatorField
      type: regular
      version: -1
    taskid: 84c21aa7-44b0-4513-8a28-4ba58ad41e84
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 860,
          "y": 970
        }
      }
  "36":
    continueonerrortype: ""
    id: "36"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "34"
    note: false
    quietmode: 0
    scriptarguments:
      field:
        simple: tags
      fieldValue:
        simple: SIEM
      indicatorsValues:
        complex:
          accessor: value
          filters:
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.CustomFields.tags
              operator: isEqualString
              right:
                value:
                  simple: approved_white
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.indicator_type
              operator: isEqualString
              right:
                value:
                  simple: IP
          root: playbookQuery
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Adds the SIEM tag to the indicators.
      id: ae55e580-b7c6-4271-865c-1ead7326691e
      iscommand: true
      name: Add SIEM tag
      script: Builtin|||appendIndicatorField
      type: regular
      version: -1
    taskid: ae55e580-b7c6-4271-865c-1ead7326691e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1600,
          "y": 970
        }
      }
  "37":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.QRadarWatchListIPReferenceSetName
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              complex:
                accessor: value
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: playbookQuery.CustomFields.tags
                    operator: isEqualString
                    right:
                      value:
                        simple: approved_watchlist
                - - left:
                      iscontext: true
                      value:
                        simple: playbookQuery.indicator_type
                    operator: isEqualString
                    right:
                      value:
                        simple: IP
                root: playbookQuery
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "37"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "34"
      "yes":
      - "38"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ae3a79ae-fabe-45ca-8bea-59f20da71f4a
      iscommand: false
      name: Is there a Qradar watch list IP Reference Set and values?
      type: condition
      version: -1
    taskid: ae3a79ae-fabe-45ca-8bea-59f20da71f4a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 2310,
          "y": 450
        }
      }
  "38":
    continueonerrortype: ""
    id: "38"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "39"
    note: false
    quietmode: 0
    scriptarguments:
      ref_name:
        simple: ${inputs.QRadarWatchListIPReferenceSetName}
      value:
        complex:
          accessor: value
          filters:
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.CustomFields.tags
              operator: isEqualString
              right:
                value:
                  simple: approved_watchlist
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.indicator_type
              operator: isEqualString
              right:
                value:
                  simple: IP
          root: playbookQuery
          transformers:
          - operator: uniq
      values:
        complex:
          root: inputs.ParentPlaybookIndicators
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Add or update a value in a reference set.
      id: 70d4f1e6-29a9-4f7a-8661-8b801128ccfc
      iscommand: true
      name: Add IPs to QRadar watch list IP reference set
      script: '|||qradar-update-reference-set-value'
      type: regular
      version: -1
    taskid: 70d4f1e6-29a9-4f7a-8661-8b801128ccfc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 2310,
          "y": 800
        }
      }
  "39":
    continueonerrortype: ""
    id: "39"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "34"
    note: false
    quietmode: 0
    scriptarguments:
      field:
        simple: tags
      fieldValue:
        simple: SIEM
      indicatorsValues:
        complex:
          accessor: value
          filters:
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.CustomFields.tags
              operator: isEqualString
              right:
                value:
                  simple: approved_watchlist
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.indicator_type
              operator: isEqualString
              right:
                value:
                  simple: IP
          root: playbookQuery
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Adds the SIEM tag to the indicators.
      id: fcbf18ee-285e-45b7-8369-1e5378bcfc8b
      iscommand: true
      name: Add SIEM tag
      script: Builtin|||appendIndicatorField
      type: regular
      version: -1
    taskid: fcbf18ee-285e-45b7-8369-1e5378bcfc8b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 2310,
          "y": 970
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1305,
        "width": 2350,
        "x": 340,
        "y": -70
      }
    }
  }
