contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 0ab7f1ac-203f-4fca-8f29-c76081c29704
inputs: []
name: ChatGptBot
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 66ea4e40-9c0a-4eda-8922-9e5cdf7db9f3
      iscommand: false
      name: ""
      version: -1
    taskid: 66ea4e40-9c0a-4eda-8922-9e5cdf7db9f3
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 35ce1159-a309-40ab-8734-3642d099bf67
      iscommand: false
      name: Incident Response Playbook
      type: title
      version: -1
    taskid: 35ce1159-a309-40ab-8734-3642d099bf67
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cefade9c-b225-4ce2-8ee7-849cb33430b5
      iscommand: false
      name: Incident Response approval starts from here
      type: title
      version: -1
    taskid: cefade9c-b225-4ce2-8ee7-849cb33430b5
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
  "3":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: asset criticality - ${incident.assetcriticality}
        options: []
        optionsarg:
        - simple: "Yes"
        - simple: "No"
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: singleSelect
      sender: ""
      title: Is below asset critical?
      totalanswers: 0
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: New message from the XBot !!
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 614472da-4e69-4c9c-8d5c-067be04c6a7d
      iscommand: false
      name: Identify Asset Criticality?
      type: collection
      version: -1
    taskid: 614472da-4e69-4c9c-8d5c-067be04c6a7d
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 50,
          "y": 485
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Is below asset critical?.Answers.0
          operator: isEqualString
          right:
            value:
              simple: "Yes"
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "yes":
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ad161d18-5241-4da6-8b1e-40917c8fd3d0
      iscommand: false
      name: Critical Asset?
      type: condition
      version: -1
    taskid: ad161d18-5241-4da6-8b1e-40917c8fd3d0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 660
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      builtincondition:
      - - left:
            iscontext: true
            value:
              simple: Please review below request?.Answers.0
          operator: isEqualString
          right:
            value:
              simple: "No"
        - left:
            iscontext: true
            value:
              simple: Please review below request?.Answers.0
          operator: isEqualString
          right:
            value:
              simple: "Yes"
      exitCondition: ""
      iscommand: false
      max: 4
      wait: 1
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 713a7d02-d6b1-4a64-8eac-514f43009e80
      iscommand: false
      name: ChatGptBotApproval
      playbookId: bf921b8d-c34d-4110-8304-ccc821265829
      type: playbook
      version: -1
    taskid: 713a7d02-d6b1-4a64-8eac-514f43009e80
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 850
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 710a5f4c-4b00-4538-8737-564ee63d7257
      iscommand: false
      name: close investigation
      type: title
      version: -1
    taskid: 710a5f4c-4b00-4538-8737-564ee63d7257
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1055,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
