contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 99767e53-0ad7-472f-81d5-9e569b157a28
inputs:
- description: ""
  key: Data
  playbookInputQuery: null
  required: false
  value:
    simple: ${ParseExcely.[0]}
name: Set Incident Data
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cbdb68ea-405f-4f40-83f9-0d24ba32d779
      iscommand: false
      name: ""
      version: -1
    taskid: cbdb68ea-405f-4f40-83f9-0d24ba32d779
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 20
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: violationid:${inputs.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Searches Demisto incidents. A summarized version of this scrips is avilable with the summarizedversion argument.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: af0b119c-4922-4ab8-8ba1-07c2f28a3ec9
      iscommand: false
      name: search incident with violation id
      script: SearchIncidentsV2
      type: regular
      version: -1
    taskid: af0b119c-4922-4ab8-8ba1-07c2f28a3ec9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: ${foundIncidents.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 586309d5-3e63-4da6-8653-00799e843ae7
      iscommand: true
      name: update the incident
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 586309d5-3e63-4da6-8653-00799e843ae7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 390
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 465,
        "width": 380,
        "x": 450,
        "y": 20
      }
    }
  }
