contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 3d6b5b49-bc99-490e-86b1-da2ef8fb31e4
inputs: []
name: Myfirstplaybook
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e9266ccf-900e-4eba-8272-ea60cec1289a
      iscommand: false
      name: ""
      version: -1
    taskid: e9266ccf-900e-4eba-8272-ea60cec1289a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 690,
          "y": 20
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b9b1ee1e-10b9-43f2-84f8-2666f725673c
      iscommand: false
      name: This is a manual task
      type: regular
      version: -1
    taskid: b9b1ee1e-10b9-43f2-84f8-2666f725673c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 690,
          "y": 190
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: |-
          This is a automation task

          ${incident.name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 87bd2ac5-22dd-4344-837b-85ffe97e6757
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 87bd2ac5-22dd-4344-837b-85ffe97e6757
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 690,
          "y": 380
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "5"
      "yes":
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${IP}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 109069bc-208c-4035-8309-ca9acfbc3f91
      iscommand: false
      name: IP exists
      script: Exists
      type: condition
      version: -1
    taskid: 109069bc-208c-4035-8309-ca9acfbc3f91
    timertriggers:
    - action: start
      fieldname: newsla
    type: condition
    view: |-
      {
        "position": {
          "x": 690,
          "y": 570
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      ip:
        simple: ${IP}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Provides data enrichment for ips.
      id: bf468dc4-71a2-4a68-8c49-6eff3899ae6e
      iscommand: true
      name: Reputation Check
      script: '|||ip'
      type: regular
      version: -1
    taskid: bf468dc4-71a2-4a68-8c49-6eff3899ae6e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 430,
          "y": 800
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9c4e861b-50ba-4299-8af9-ac9a5d3b069b
      iscommand: false
      name: No Ip
      type: regular
      version: -1
    taskid: 9c4e861b-50ba-4299-8af9-ac9a5d3b069b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 930,
          "y": 800
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: aa792769-92e0-4f5d-8c97-c9dac7ff82fd
      iscommand: false
      name: AD Test
      playbookId: 128b585b-27b2-4f47-80e6-7398a60bed12
      type: playbook
      version: -1
    taskid: aa792769-92e0-4f5d-8c97-c9dac7ff82fd
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1270,
          "y": 310
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6a02ef83-2d85-4fbc-85fd-985f5a6eca01
      iscommand: false
      name: Start Timer
      type: title
      version: -1
    taskid: 6a02ef83-2d85-4fbc-85fd-985f5a6eca01
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1210,
          "y": 505
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 875,
        "width": 1220,
        "x": 430,
        "y": 20
      }
    }
  }
