contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 44714b23-df94-4581-829e-401cf9234a33
inputs: []
name: DeDupDemoPlaybook
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 581843c4-5f69-47c6-842f-6b9da659701b
      iscommand: false
      name: ""
      version: -1
    taskid: 581843c4-5f69-47c6-842f-6b9da659701b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1480,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    reputationcalc: 1
    scriptarguments:
      columns:
        simple: sourceip,destinationip,filemd5
      data:
        simple: ${incident}
      title:
        simple: IOC Details
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Convert an array to a nice table display. Usually, from the context.
      id: 43a9aa05-e68c-43bf-89f2-e2adfa2dccd5
      iscommand: false
      name: To Table
      script: ToTable
      type: regular
      version: -1
    taskid: 43a9aa05-e68c-43bf-89f2-e2adfa2dccd5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 410
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ca3f9690-061a-47ab-87af-f78976d37e10
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: ca3f9690-061a-47ab-87af-f78976d37e10
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1480,
          "y": 580
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 2
    scriptarguments:
      closeReason:
        simple: 'Duplicate incident to '
      fieldsToDisplay:
        simple: id,name,created,sourceip,destionationip,filemd5
      fromDate:
        simple: 180 minutes ago
      handleSimilar:
        simple: Close
      limit:
        simple: "100"
      method:
        simple: Fields
      minimunIncidentSimilarity:
        simple: "0.9"
      query:
        simple: type:DemoPhishing and name:"Reported Phishing by Bob@demisto.com"
      showIncidentSimilarityForAllFields:
        simple: "True"
      similarTextField:
        simple: sourceip,filemd5
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: "This playbook identifies duplicate incidents using the Cortex
        XSOAR machine learning method (script).\nIn this playbook, you can choose
        fields and/or indicators to be compared against other incidents in the Cortex
        XSOAR database. \n\nNote: To identify similar incidents you must *must* properly
        define the playbook inputs. "
      id: 8e876999-af51-4021-8252-e89522a8894b
      iscommand: false
      name: Dedup - Generic v4_Custom
      playbookId: 91702eff-03d2-4b26-800b-70528f43af17
      type: playbook
      version: -1
    taskid: 8e876999-af51-4021-8252-e89522a8894b
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1470,
          "y": 380
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Test
      cc: null
      format: ""
      methods: []
      replyOptions:
      - "Yes"
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      "Yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: d553b2a3-438e-493f-84cb-f464d55d6c2e
      iscommand: false
      name: Test
      type: condition
      version: -1
    taskid: d553b2a3-438e-493f-84cb-f464d55d6c2e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 440,
          "y": 220
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "5_2_Yes": 0.5
    },
    "paper": {
      "dimensions": {
        "height": 435,
        "width": 1420,
        "x": 440,
        "y": 210
      }
    }
  }
