contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 761f5876-98c7-4bd9-8fa6-1e2d6887d56e
inputs:
- description: ""
  key: SponserEmail
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SEmail
      root: ParseCSV.ParsedCSV
      transformers:
      - operator: uniq
name: Demo - Dormant Accounts
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e225a398-faa9-4464-8a56-c53cf773e238
      iscommand: false
      name: ""
      version: -1
    taskid: e225a398-faa9-4464-8a56-c53cf773e238
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: TableData
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: ParseCSV.ParsedCSV.SEmail
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: inputs.SponserEmail
          root: ParseCSV.ParsedCSV
          transformers:
          - args:
              headers:
                value:
                  simple: ID,CSPID,Email,SponserID, SEmail
              is_auto_json_transform: {}
              json_transform_properties: {}
              title: {}
            operator: JsonToTable
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: a194666c-13d5-4981-8f4f-69fbee9816de
      iscommand: false
      name: Get the Accounts Details based on Sponsor
      script: Set
      type: regular
      version: -1
    taskid: a194666c-13d5-4981-8f4f-69fbee9816de
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      contextKey:
        simple: HTMLTable
      text:
        complex:
          root: TableData
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.mdToHTML
      id: ec179627-3674-4bb9-8b9c-7084112b83e1
      iscommand: true
      name: HTML Table
      script: Builtin|||mdToHtml
      type: regular
      version: -1
    taskid: ec179627-3674-4bb9-8b9c-7084112b83e1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      bodyType:
        simple: HTML
      htmlBody:
        simple: |-
          <!DOCTYPE html><html>
          <head><style>table, th, td { border:1px solid black;}</style></head>
          <body> Hi,
          <p>Below are the Dormant Accounts.</p>
          ${HTMLTable}
          </body>
          </html>
      subject:
        simple: ${incident.name}
      to:
        simple: ${inputs.SponserEmail}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Gmail Single User
      description: Sends an email using Gmail.
      id: 58a80c59-5998-4423-8dbc-8af1fffc761a
      iscommand: true
      name: Send Email
      script: Gmail Single User|||send-mail
      type: regular
      version: -1
    taskid: 58a80c59-5998-4423-8dbc-8af1fffc761a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 590
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: HTMLTable
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 1e4221d4-0414-40ba-8efd-8f0c0311d8b3
      iscommand: false
      name: Delete Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: 1e4221d4-0414-40ba-8efd-8f0c0311d8b3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 790
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 835,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
