contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: df806072-8b9a-4dfa-8393-d10fdb5e09b4
inputs: []
name: Email Communication - Data collection
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d9feef8b-5019-4b56-882e-b6c8ec1646bf
      iscommand: false
      name: ""
      version: -1
    taskid: d9feef8b-5019-4b56-882e-b6c8ec1646bf
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Please reply with Yes or No
        options: []
        optionsarg:
        - {}
        - simple: "Yes"
        - simple: "No"
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: singleSelect
      - defaultrows: []
        fieldassociated: fileattachments
        gridcolumns: []
        id: "1"
        label: ""
        labelarg:
          simple: Please find the attachment
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: attachments
      sender: Your SOC team
      title: User Response Form
      totalanswers: 0
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: |-
          <!DOCTYPE html>
          <html>
          <head><style>table, th, td {
            border:1px solid black;
          }
          </style>
          </head>
          <body>
          <table>
          <thead>
          <tr>
          <th>ID</th>
          <th>CSPID</th>
          <th>Email</th>
          <th>SponserID</th>
          <th>SEmail</th>
          </tr>
          </thead>

          <tbody>
          <tr>
          <td>4</td>
          <td>emp123</td>
          <td>test@test.com</td>
          <td>123</td>
          <td>cortexxsoar2023@gmail.com</td>
          </tr>

          <tr>
          <td>3</td>
          <td>emp789</td>
          <td>def@test.com</td>
          <td>123</td>
          <td>cortexxsoar2023@gmail.com</td>
          </tr>

          <tr>
          <td>5</td>
          <td>emp1213</td>
          <td>jkl@test.com</td>
          <td>123</td>
          <td>cortexxsoar2023@gmail.com</td>
          </tr>
          </tbody>
          </table>
          ${File.EntryID}
          </body>
          </html>
      cc: null
      format: html
      methods:
      - email
      subject:
        simple: This is test Email
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
        simple: sua@paloaltonetworks.com
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bff74571-46a6-4e50-84ad-844fbc5b020c
      iscommand: false
      name: Send Email to User
      type: collection
      version: -1
    taskid: bff74571-46a6-4e50-84ad-844fbc5b020c
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
