contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: fc5aee64-dac6-4727-84df-7c5f96cd2d15
inputs: []
name: main playbook
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1e985840-012b-41f1-8fa5-ce9b98a097bf
      iscommand: false
      name: ""
      version: -1
    taskid: 1e985840-012b-41f1-8fa5-ce9b98a097bf
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 1
    scriptarguments:
      key:
        simple: IP
      value:
        simple: '["1.1.1.1","2.2.2.2"]'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: b74fed4d-482b-4c3e-8415-f31dfea940aa
      iscommand: false
      name: Set a list
      script: Set
      type: regular
      version: -1
    taskid: b74fed4d-482b-4c3e-8415-f31dfea940aa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      IP:
        simple: ${IP}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dfbfb589-32d3-46a8-8c57-97e991de8b37
      iscommand: false
      name: loop playbook
      playbookId: 53f8d8c3-200a-4b04-84d8-3f03dc90390d
      type: playbook
      version: -1
    taskid: dfbfb589-32d3-46a8-8c57-97e991de8b37
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 360
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: loop completed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: ecc385a7-4efa-4116-87d5-3f49549dcb4d
      iscommand: false
      name: Success
      script: Print
      type: regular
      version: -1
    taskid: ecc385a7-4efa-4116-87d5-3f49549dcb4d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 570
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 615,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
