contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: e6ea0cdb-de53-4d38-8c6e-c5224c6e6a63
inputs: []
name: Test - Data Collection v2
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d14f2973-5d1b-411f-8984-872782b4f112
      iscommand: false
      name: ""
      version: -1
    taskid: d14f2973-5d1b-411f-8984-872782b4f112
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 400,
          "y": 0
        }
      }
  "1":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Is this Phishing
        options: []
        optionsarg:
        - simple: "Yes"
        - simple: "No"
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: singleSelect
      sender: Your SOC team
      title: Testing
      totalanswers: 0
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: {}
      cc: null
      format: html
      methods: []
      replyOptions:
      - "Yes"
      - "No"
      subject:
        simple: Test Incident
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
        simple: sua@paloaltonetworks.com
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 355f0adb-7442-4239-8185-7abd7d60a19c
      iscommand: false
      name: Data Collection Task
      type: collection
      version: -1
    taskid: 355f0adb-7442-4239-8185-7abd7d60a19c
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 30,
          "y": 340
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      task_id:
        simple: "1"
      users:
        simple: sua@paloaltonetworks.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Generates the URL for a Data Collection Task into Context.  Can be used to get the url for tasks send via Email, Slack, or even if you select "By Task Only".

        To generate links for specific users, add an array of users in the users argument.
      id: f87d78eb-e0ca-48d5-8fd1-6ca87f268456
      iscommand: false
      name: 'Get the generative link '
      script: 49beb76f-6d41-4c5a-80a6-02e2e0622ad7
      type: regular
      version: -1
    taskid: f87d78eb-e0ca-48d5-8fd1-6ca87f268456
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 880,
          "y": 20
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      bodyType:
        simple: HTML
      htmlBody:
        simple: |-
          <html>
          <body>
          <p>Hi, This is test email. Please <a href="${Testing.Links.0.link}">click</a></p>
          </body>
          </html>
      subject:
        simple: Test Email
      to:
        simple: sua@paloaltonetworks.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: Gmail Single User
      description: Sends an email using Gmail.
      id: 424d142d-5e22-4e6f-81e9-5d808249044c
      iscommand: true
      name: Send mail
      script: Gmail Single User|||send-mail
      type: regular
      version: -1
    taskid: 424d142d-5e22-4e6f-81e9-5d808249044c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 560,
          "y": 500
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "3"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds.
      id: 523a941e-5668-4249-8a69-d876d0322ac9
      iscommand: false
      name: Sleep
      script: Sleep
      type: regular
      version: -1
    taskid: 523a941e-5668-4249-8a69-d876d0322ac9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 560,
          "y": 350
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 595,
        "width": 1230,
        "x": 30,
        "y": 0
      }
    }
  }
