contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 53f8d8c3-200a-4b04-84d8-3f03dc90390d
inputs:
- description: ""
  key: IP
  playbookInputQuery: null
  required: false
  value:
    simple: ${IP}
name: loop playbook
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f37a1f8e-62de-497d-808a-c4e1f28dbdcc
      iscommand: false
      name: ""
      version: -1
    taskid: f37a1f8e-62de-497d-808a-c4e1f28dbdcc
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 60
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      value:
        simple: ${IP}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: f90c39b7-03b2-442c-8c73-2b4abe43ed85
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: f90c39b7-03b2-442c-8c73-2b4abe43ed85
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 245,
        "width": 380,
        "x": 450,
        "y": 60
      }
    }
  }
