contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: f8367c9f-af18-48cf-8c4b-67cb65934ec1
inputs: []
name: 'TIM - UBI - Main Add IP Indicator to Arcsight SIEM  '
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d6f4120b-fa26-47a3-8988-6135ccebe8ca
      iscommand: false
      name: ""
      version: -1
    taskid: d6f4120b-fa26-47a3-8988-6135ccebe8ca
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": -60
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 1
    scriptarguments:
      Threat Intel Query:
        simple: type:ip and verdict:Malicious and expirationStatus:active
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 41248c88-4b89-421c-88dc-2951c2b2f9bf
      iscommand: false
      name: TIM - UBI Get IP Indicator
      playbookId: d697b8b6-ca8e-4242-8eb4-6837d89610bb
      type: playbook
      version: -1
    taskid: 41248c88-4b89-421c-88dc-2951c2b2f9bf
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 40,
          "y": 275
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d6b98fed-d25c-481b-81a9-01257d73bf85
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d6b98fed-d25c-481b-81a9-01257d73bf85
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 40,
          "y": 735
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 3a373506-5348-4e36-8af3-4e84a3e426e6
      iscommand: false
      name: Delete All Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: 3a373506-5348-4e36-8af3-4e84a3e426e6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": 70
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 1
    scriptarguments:
      Threat Intel Query:
        simple: type:IP and verdict:Malicious and expirationStatus:active
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 87d1de7c-84c5-4506-8a42-07a9f7f3760d
      iscommand: false
      name: TIM - UBI Get IP Indicator
      playbookId: d697b8b6-ca8e-4242-8eb4-6837d89610bb
      type: playbook
      version: -1
    taskid: 87d1de7c-84c5-4506-8a42-07a9f7f3760d
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 610,
          "y": 320
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      daysAgo:
        simple: "1"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Retrieves the current date and time.
      id: e4f3bdb7-7049-4b69-8a01-74348376fd43
      iscommand: false
      name: Get time
      script: GetTime
      type: regular
      version: -1
    taskid: e4f3bdb7-7049-4b69-8a01-74348376fd43
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1030,
          "y": 70
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 3ff96526-0f51-4ade-8aa7-68993586bedd
      iscommand: true
      name: Closed Incident
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 3ff96526-0f51-4ade-8aa7-68993586bedd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 30,
          "y": 520
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 860,
        "width": 1380,
        "x": 30,
        "y": -60
      }
    }
  }
