contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: CVE_Eval_Pack
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: b891b14e-3e9e-4b7b-8c8f-1027d1c39ff0
inputs:
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: sourceInstances:"National Vulnerability Database_instance_1"
    queryEntity: indicators
    results: null
    runFromLastJobTime: true
  required: false
  value: {}
name: NewCVE
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d5bc0f78-606e-4d2f-8670-9fdaf6957da3
      iscommand: false
      name: ""
      version: -1
    taskid: d5bc0f78-606e-4d2f-8670-9fdaf6957da3
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: CVEList
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.indicator_type
              operator: isEqualString
              right:
                value:
                  simple: CVE
          root: playbookQuery
          transformers:
          - args:
              expression:
                value:
                  simple: '{CVE: value, Targets: CustomFields.targets}'
            operator: jmespath
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 7f3b1dd3-ee59-43d6-8d35-97481981a11f
      iscommand: false
      name: Extract CVE List
      script: Set
      type: regular
      version: -1
    taskid: 7f3b1dd3-ee59-43d6-8d35-97481981a11f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 545
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 19436b71-bcf8-4298-84c3-5d54765f1c40
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 19436b71-bcf8-4298-84c3-5d54765f1c40
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1245
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: UnknownCPEs
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: CVEList.Targets
              operator: isEmpty
          root: CVEList
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 1b6e2d4a-9a3c-4566-88b6-909aab023ae8
      iscommand: false
      name: UnknownCPEs
      script: Set
      type: regular
      version: -1
    taskid: 1b6e2d4a-9a3c-4566-88b6-909aab023ae8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: KnownCPEs
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: CVEList.Targets
              operator: isNotEmpty
          root: CVEList
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 4aba9391-a4ee-40c5-88b3-d5aefd38df42
      iscommand: false
      name: KnownCPEs
      script: Set
      type: regular
      version: -1
    taskid: 4aba9391-a4ee-40c5-88b3-d5aefd38df42
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 612.5,
          "y": 895
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 5
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      CVE:
        simple: ${UnknownCPEs.CVE}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 7f1dfd9d-1b2d-43b7-8b16-294755f28ac7
      iscommand: false
      name: NewCVE_UnknownCPE_Incident
      playbookId: 7302f2e1-56e3-4337-856e-da0635004378
      type: playbook
      version: -1
    taskid: 7f1dfd9d-1b2d-43b7-8b16-294755f28ac7
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: a39be55c-c883-4608-8e22-b8dc6a2625c0
      iscommand: false
      name: Delete Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: a39be55c-c883-4608-8e22-b8dc6a2625c0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: CVEList.Targets
                    operator: isEmpty
                root: CVEList
          operator: isNotEmpty
      label: Found Empty
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      Found Empty:
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 723acb06-3e3b-4dc3-8e31-b81e38224289
      iscommand: false
      name: Are there CVEs with no CPEs?
      type: condition
      version: -1
    taskid: 723acb06-3e3b-4dc3-8e31-b81e38224289
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 1a853278-ccc1-4b57-8bb9-e084706292aa
      iscommand: false
      name: NewCVE_KnownCPE_Check
      playbookId: 47219563-3ac4-4f03-8c1c-db16914d1f10
      type: playbook
      version: -1
    taskid: 1a853278-ccc1-4b57-8bb9-e084706292aa
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 612.5,
          "y": 1070
        }
      }
  "13":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: playbookQuery.indicator_type
                    operator: isEqualString
                    right:
                      value:
                        simple: CVE
                root: playbookQuery
          operator: isNotEmpty
      label: New CVEs
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      New CVEs:
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 975d104f-7520-40b1-83ce-4288bb351b2e
      iscommand: false
      name: Do we have CVEs?
      type: condition
      version: -1
    taskid: 975d104f-7520-40b1-83ce-4288bb351b2e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: CVEList.Targets
                    operator: isNotEmpty
                root: CVEList
          operator: isNotEmpty
          right:
            value: {}
      label: Found Known
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      Found Known:
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0e7c8f57-dd51-4b7d-8623-8e0da03964fc
      iscommand: false
      name: Are there CVEs with known CPEs?
      type: condition
      version: -1
    taskid: 0e7c8f57-dd51-4b7d-8623-8e0da03964fc
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 500,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1260,
        "width": 942.5,
        "x": 50,
        "y": 50
      }
    }
  }
