contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: dc2e543c-b138-4926-8059-fec729312c3b
inputs: []
name: Testerror
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 20d67007-f17f-4ec7-8f76-7732e4ac2234
      iscommand: false
      name: ""
      version: -1
    taskid: 20d67007-f17f-4ec7-8f76-7732e4ac2234
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 990,
          "y": 30
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: errorPath
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: adas
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: e14f3be2-b7da-42c6-896a-34ae9544d89b
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: e14f3be2-b7da-42c6-896a-34ae9544d89b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 990,
          "y": 220
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c76c57ad-9fca-4e1e-86c6-709e7f3bbd38
      iscommand: false
      name: Actions to do when there is a failure
      type: regular
      version: -1
    taskid: c76c57ad-9fca-4e1e-86c6-709e7f3bbd38
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1290,
          "y": 540
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 605,
        "width": 680,
        "x": 990,
        "y": 30
      }
    }
  }
