contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: CVE_Eval_Pack
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 5cf6ba09-ae32-4f4f-8618-a52c07c82059
inputs:
- description: ""
  key: CVEID
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: Host
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: Reason
  playbookInputQuery: null
  required: false
  value: {}
name: NewCVE_KnownCPE_Incident
outputs: []
sourceplaybookid: 7302f2e1-56e3-4337-856e-da0635004378
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b394b298-a5b5-414b-8e62-5efd4fdfc54f
      iscommand: false
      name: ""
      version: -1
    taskid: b394b298-a5b5-414b-8e62-5efd4fdfc54f
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: name
      value:
        simple: 'Automated Vulnerability Assessment: ${inputs.CVEID} for ${inputs.Host.hostname}'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: beebc94d-f069-4e4d-86e8-c1ee1c9140e3
      iscommand: false
      name: Set Name
      script: Set
      type: regular
      version: -1
    taskid: beebc94d-f069-4e4d-86e8-c1ee1c9140e3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 360
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: foundIncidents
          operator: isNotEmpty
      label: exists
    - condition:
      - - left:
            iscontext: true
            value:
              simple: foundIncidents
          operator: isEmpty
      label: does not exist
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      does not exist:
      - "5"
      exists:
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9c4eb640-5f6e-4676-8fa1-7c12ec8a0730
      iscommand: false
      name: Exists
      type: condition
      version: -1
    taskid: 9c4eb640-5f6e-4676-8fa1-7c12ec8a0730
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 58a0a50b-7824-49cb-8cf3-33668978dcfc
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 58a0a50b-7824-49cb-8cf3-33668978dcfc
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      cve:
        simple: ${inputs.CVEID}
      description:
        simple: Playbook automatically determined that this CVE matched host ${inputs.Host.hostname}
          because ${inputs.Reason}
      name:
        simple: ${name}
      type:
        simple: Vulnerability
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.create.inc
      id: d75b64ec-26ba-439b-8fff-da287770ad00
      iscommand: true
      name: Create Incident
      script: Builtin|||createNewIncident
      type: regular
      version: -1
    taskid: d75b64ec-26ba-439b-8fff-da287770ad00
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1245
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 2
    scriptarguments:
      query:
        simple: name="${name}"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Searches Demisto incidents.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: e10758f8-0fb8-4e40-8d18-c90cdaf6d79f
      iscommand: false
      name: Search Incidents
      script: SearchIncidentsV2
      type: regular
      version: -1
    taskid: e10758f8-0fb8-4e40-8d18-c90cdaf6d79f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
      subplaybook:
        simple: auto
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: 0969a6d8-7c17-427c-844e-e4b9bf3bf4b7
      iscommand: false
      name: Delete Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: 0969a6d8-7c17-427c-844e-e4b9bf3bf4b7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 180
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1435,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
