contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 3a4f4315-6e77-4b29-8799-c922921edb01
inputs: []
name: email send v2
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4f2f4c3d-1e79-401f-8e0d-d2f323764e8e
      iscommand: false
      name: ""
      version: -1
    taskid: 4f2f4c3d-1e79-401f-8e0d-d2f323764e8e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 110,
          "y": -750
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      emailnewbody:
        simple: |-
          <!DOCTYPE html>
          <html>

          <table>
          <thead>
          <tr>
          <th>ID</th>
          <th>CSPID</th>
          <th>Email</th>
          <th>SponserID</th>
          <th>SEmail</th>
          </tr>
          </thead>

          <tbody>
          <tr>
          <td>4</td>
          <td>emp123</td>
          <td>test@test.com</td>
          <td>123</td>
          <td>cortexxsoar2023@gmail.com</td>
          </tr>
          </tbody>
          </table>

          </body>
          </html>
      emailnewrecipients:
        simple: sua@paloaltonetworks.com
      emailnewsubject:
        simple: Test Email Communincation 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: c2e46527-fbe6-4a77-8d0c-16f87b2b2627
      iscommand: true
      name: Set Incident Fields
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: c2e46527-fbe6-4a77-8d0c-16f87b2b2627
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 100,
          "y": -200
        }
      }
  "2":
    continueonerrortype: ""
    evidencedata:
      customfields: {}
      description:
        simple: User Email Communication
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 2
    scriptarguments:
      mail_sender_instance:
        simple: Gmail Single User_instance_1
      new_thread:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Send email reply
        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 6a1aae11-5236-4738-81a7-b75f35e1f79d
      iscommand: false
      name: Send Email
      script: SendEmailReply
      type: regular
      version: -1
    taskid: 6a1aae11-5236-4738-81a7-b75f35e1f79d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 100,
          "y": -30
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      sla:
        simple: "600"
      slaField:
        simple: demosla
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: b7ae3004-2ab2-4b07-8817-082389b06749
      iscommand: true
      name: Set SLA
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: b7ae3004-2ab2-4b07-8817-082389b06749
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -430,
          "y": 670
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c7c7da36-676b-4bc1-85d3-b80001cf0d3e
      iscommand: false
      name: wait for user response
      tags:
      - userreply2
      type: regular
      version: -1
    taskid: c7c7da36-676b-4bc1-85d3-b80001cf0d3e
    timertriggers:
    - action: start
      fieldname: demosla
    type: regular
    view: |-
      {
        "position": {
          "x": -440,
          "y": 840
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: true
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "60"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds.
      id: 762d1d2f-9d3b-43a3-88b6-9d668cd3c96a
      iscommand: false
      name: Sleep 1 min
      script: Sleep
      type: regular
      version: -1
    taskid: 762d1d2f-9d3b-43a3-88b6-9d668cd3c96a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 90,
          "y": 130
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: email-${incident.id}
      timeout:
        simple: "500"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Demisto Lock
      description: Gets a specific lock. If the lock doesn't exist, it creates one.
        If the lock is already in use, the command waits until the lock is released
        or until timeout is reached. If timeout is reached and the lock hasn't been
        released, the command fails to get the lock.
      id: 4477cf91-44e3-40bb-8741-e76c146113c1
      iscommand: true
      name: demisto lock
      script: Demisto Lock|||demisto-lock-get
      type: regular
      version: -1
    taskid: 4477cf91-44e3-40bb-8741-e76c146113c1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 110,
          "y": -380
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: email-${incident.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Demisto Lock
      description: Release a lock
      id: 89f2a47a-6388-4b1b-8978-9a52fe8607eb
      iscommand: true
      name: demisto release lock
      script: Demisto Lock|||demisto-lock-release
      type: regular
      version: -1
    taskid: 89f2a47a-6388-4b1b-8978-9a52fe8607eb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 130,
          "y": 320
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0cacd17c-9f1c-4f07-84cb-b844a7b0c0ae
      iscommand: false
      name: end
      type: title
      version: -1
    taskid: 0cacd17c-9f1c-4f07-84cb-b844a7b0c0ae
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 130,
          "y": 620
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1685,
        "width": 950,
        "x": -440,
        "y": -750
      }
    }
  }
