contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: This is a Securonix initializer playbook which identifies the violator
  type, gets the associated policy violations, associates MITRE indicators, sets default
  priority and severity and assigns an analyst to the incident
id: 3217ac4e-38e5-4d81-8c38-faf7200efc22
inputs: []
name: Cust_IRC_Securonix_Initializer
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c6ce1def-34c1-4c32-84fa-dbaf468c352f
      iscommand: false
      name: ""
      version: -1
    taskid: c6ce1def-34c1-4c32-84fa-dbaf468c352f
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0949f263-bfad-4553-8490-9a59f25ebcf6
      iscommand: false
      name: CUst_IRC_Securonix_Generic_Get_Policy_Violations
      playbookName: Wipro_IRC_Securonix_Generic_Get_Policy_Violations
      type: playbook
      version: -1
    taskid: 0949f263-bfad-4553-8490-9a59f25ebcf6
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: from_date
      stringify:
        simple: "true"
      value:
        complex:
          accessor: occurred
          root: incident
          transformers:
          - args:
              variation:
                value:
                  simple: 7 days ago
            operator: ModifyDateTime
          - args:
              fromFormat:
                value:
                  simple: '%Y-%m-%dT%H:%M:%S+05:30'
              toFormat:
                value:
                  simple: '%m/%d/%Y %H:%M:%S'
            operator: 87dad037-5f4c-4af5-8a6c-8e321560d856
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Set a value in context under the key you entered. If no value is entered, the script doesn't do anything.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: e9e445fb-94e3-485e-89fc-82ea62fe7ab2
      iscommand: false
      name: Set from date
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: e9e445fb-94e3-485e-89fc-82ea62fe7ab2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: to_date
      stringify:
        simple: "true"
      value:
        complex:
          accessor: occurred
          root: incident
          transformers:
          - args:
              fromFormat:
                value:
                  simple: '%Y-%m-%dT%H:%M:%S+05:30'
              toFormat:
                value:
                  simple: '%m/%d/%Y %H:%M:%S'
            operator: 87dad037-5f4c-4af5-8a6c-8e321560d856
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Set a value in context under the key you entered. If no value is entered, the script doesn't do anything.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: 793619b4-6123-44b0-8e93-875929b90329
      iscommand: false
      name: Set to date
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: 793619b4-6123-44b0-8e93-875929b90329
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 545
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6e7c4c67-94f7-406e-8dd3-5721a7af3e35
      iscommand: false
      name: Delete unnecessary context
      type: title
      version: -1
    taskid: 6e7c4c67-94f7-406e-8dd3-5721a7af3e35
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1260
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: from_date
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: 60537455-85a4-4e28-8884-bb3f81a3f270
      iscommand: false
      name: Delete from_date
      script: DeleteContext
      type: regular
      version: -1
    taskid: 60537455-85a4-4e28-8884-bb3f81a3f270
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: to_date
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: 29be5530-53b9-466b-8636-089b055114dd
      iscommand: false
      name: Delete to_date
      script: DeleteContext
      type: regular
      version: -1
    taskid: 29be5530-53b9-466b-8636-089b055114dd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 49584098-87cb-42fc-883c-cde6705aefb4
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 49584098-87cb-42fc-883c-cde6705aefb4
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1595
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
      keysToKeep:
        simple: File
      subplaybook:
        simple: "no"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Delete field from context
      id: 20747c69-6c94-419f-8725-989192c2ab0f
      iscommand: false
      name: Delete Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: 20747c69-6c94-419f-8725-989192c2ab0f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      priority:
        simple: P3
      severity:
        simple: "2"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: dec4e1aa-af78-4af6-8b02-b3aed64056f2
      iscommand: true
      name: Assign default P3 priority and Medium severity
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: dec4e1aa-af78-4af6-8b02-b3aed64056f2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1420
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This is a generic subplaybook of Securonix which takes Violator
        ID, Violator Sub Text, Violator Text and Resource Name as inputs and sets
        the violator type as either accountname, ipaddress or resourcename
      id: 7a7af09a-3d33-4fef-8f8c-9dc02e6c1541
      iscommand: false
      name: Cust_IRC_Securonix_Generic_Identify_Violator_Type
      playbookName: Wipro_IRC_Securonix_Generic_Identify_Violator_Type
      type: playbook
      version: -1
    taskid: 7a7af09a-3d33-4fef-8f8c-9dc02e6c1541
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 414fa26c-1025-4ae1-812f-2a06e6277d68
      iscommand: false
      name: Wipro_IRC_Securonix_Generic_Assign_Owner
      playbookId: cf99b3fe-2026-4266-8a77-cf78dd8b70fc
      type: playbook
      version: -1
    taskid: 414fa26c-1025-4ae1-812f-2a06e6277d68
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1420
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      destinationhostname:
        complex:
          accessor: ViolationData
          root: Securonix
          transformers:
          - args:
              field:
                value:
                  simple: destinationhostname
            operator: getField
          - operator: uniq
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      destinationips:
        complex:
          accessor: ViolationData
          root: Securonix
          transformers:
          - args:
              field:
                value:
                  simple: destinationaddress
            operator: getField
          - operator: uniq
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      destinationmacaddress:
        complex:
          accessor: ViolationData
          root: Securonix
          transformers:
          - args:
              field:
                value:
                  simple: destinationmacaddress
            operator: getField
          - operator: uniq
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      destinationport:
        complex:
          accessor: ViolationData
          root: Securonix
          transformers:
          - args:
              field:
                value:
                  simple: destinationport
            operator: getField
          - operator: uniq
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      devicelocalip:
        complex:
          accessor: ViolationData
          root: Securonix
          transformers:
          - args:
              field:
                value:
                  simple: deviceaddress
            operator: getField
          - operator: uniq
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      devicename:
        complex:
          accessor: ViolationData
          root: Securonix
          transformers:
          - args:
              field:
                value:
                  simple: devicehostname
            operator: getField
          - operator: uniq
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      sourcehostname:
        complex:
          accessor: ViolationData
          root: Securonix
          transformers:
          - args:
              field:
                value:
                  simple: sourcehostname
            operator: getField
          - operator: uniq
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      sourceips:
        complex:
          accessor: ViolationData
          root: Securonix
          transformers:
          - args:
              field:
                value:
                  simple: sourceaddress
            operator: getField
          - operator: uniq
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      sourcemacaddress:
        complex:
          accessor: ViolationData
          root: Securonix
          transformers:
          - args:
              field:
                value:
                  simple: sourcemacaddress
            operator: getField
          - operator: uniq
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      sourceport:
        complex:
          accessor: ViolationData
          root: Securonix
          transformers:
          - args:
              field:
                value:
                  simple: sourceport
            operator: getField
          - operator: uniq
          - args:
              separator:
                value:
                  simple: ','
            operator: join
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: a0e10e63-c493-4c18-8b09-1c794f3ae4da
      iscommand: true
      name: Set the required common incident fields in the layout
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: a0e10e63-c493-4c18-8b09-1c794f3ae4da
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 19649c8c-2bc3-42a1-8dbf-22ed24572dad
      iscommand: false
      name: Cust_IRC_Generic_Associate_MITRE
      playbookName: Wipro_IRC_Generic_Associate_MITRE
      type: playbook
      version: -1
    taskid: 19649c8c-2bc3-42a1-8dbf-22ed24572dad
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 3
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        This is a generic sub playbook which checks the inputted IP against three lists
        * Inventory_AD_DC
        * Inventory_SAP
        * Inventory_VDI
        and outputs the IP details which belongs to one of the IP in these lists. Sets the fields wiprocriticalasset and assettable.
        If  the IP is not found, it is resolved to a host and then it is checked
      id: 57e3ec67-acea-434e-8e71-af20fe05ecdc
      iscommand: false
      name: Cust_IRC_Generic_Critical_Asset
      playbookName: Wipro_IRC_Generic_Critical_Asset
      type: playbook
      version: -1
    taskid: 57e3ec67-acea-434e-8e71-af20fe05ecdc
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1245
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1610,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
