contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: e3978062-f7cd-4154-854f-efc1d2040dd1
inputs: []
name: Test - service Now Mirroring
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 35e47478-d2d8-4d58-89e2-656a290be839
      iscommand: false
      name: ""
      version: -1
    taskid: 35e47478-d2d8-4d58-89e2-656a290be839
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 2
    scriptarguments:
      caller_id:
        simple: Suresh
      category:
        simple: Software
      short_description:
        simple: Test Incident Mirror 3
      state:
        simple: ${incident.severity}
      subcategory:
        simple: Email
      ticket_type:
        simple: incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Creates new ServiceNow ticket.
      id: adbc9ea9-da89-45f8-804c-80917d711569
      iscommand: true
      name: Create Service Now ticket
      script: '|||servicenow-create-ticket'
      type: regular
      version: -1
    taskid: adbc9ea9-da89-45f8-804c-80917d711569
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 2
    scriptarguments:
      dbotMirrorDirection:
        simple: In
      dbotMirrorId:
        simple: ${ServiceNow.Ticket.ID}
      dbotMirrorInstance:
        simple: ServiceNow v2_instance_1
      dbotMirrorTags:
        simple: comment,work_notes,ForServiceNow,FromServiceNow
      servicenowseverity:
        simple: ${ServiceNow.Ticket.Priority}
      servicenowstate:
        simple: ${ServiceNow.Ticket.State}
      ticketnumber:
        simple: ${ServiceNow.Ticket.Number}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: d17b0dfa-27aa-4ca9-8b77-621ad8eab160
      iscommand: true
      name: Enable Mirroring
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: d17b0dfa-27aa-4ca9-8b77-621ad8eab160
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f32e251e-5949-43a0-8816-0f2e897466b6
      iscommand: false
      name: end
      type: title
      version: -1
    taskid: f32e251e-5949-43a0-8816-0f2e897466b6
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 610
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 625,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
