contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 31267631-44da-4a94-81c6-e0a402cdefb1
inputs: []
name: data collection email with attachment playbook
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 31f2bbbb-4bbf-4266-839a-7ffab16adab3
      iscommand: false
      name: ""
      version: -1
    taskid: 31f2bbbb-4bbf-4266-839a-7ffab16adab3
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: sd
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: shortText
      sender: XSOARSOCLTD
      title: sd
      totalanswers: 0
    formDisplay:
      bodybackgroundcolor: ""
      bodyfontcolor: ""
      headerbackgroundcolor: '#f4f5f5'
      headerfontcolor: ""
      isexternalrtl: false
      sender: ""
      submitbuttonbackgroundcolor: ""
      submitbuttonfontcolor: ""
      submittext: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: {}
      cc: null
      format: html
      methods: []
      subject:
        simple: test link
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: {}
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a827f787-97dd-4af5-8b9a-8d3b4ebc7203
      iscommand: false
      name: data collection task
      type: collection
      version: -1
    taskid: a827f787-97dd-4af5-8b9a-8d3b4ebc7203
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: true
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "2"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: 98b7e323-33e2-4a90-86b9-84fbbe894b77
      iscommand: false
      name: wait a bit to get the link
      script: Sleep
      type: regular
      version: -1
    taskid: 98b7e323-33e2-4a90-86b9-84fbbe894b77
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      body:
        simple: |-
          link is here
          ${sd.Links.0.link}
      subject:
        simple: sample
      to:
        simple: shapatil@paloaltonetworks.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: EWSO365
      description: Sends an email.
      id: 88f90a4d-7010-44e8-87cd-fb058573c3a9
      iscommand: true
      name: send email
      script: EWSO365|||send-mail
      type: regular
      version: -1
    taskid: 88f90a4d-7010-44e8-87cd-fb058573c3a9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 360
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: continue
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 684d9dd2-881f-4434-846c-10c02b6b17dd
      iscommand: false
      name: Next tasks
      script: Print
      type: regular
      version: -1
    taskid: 684d9dd2-881f-4434-846c-10c02b6b17dd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 360
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 405,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
