contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: fb74d26c-d76f-4ef7-8054-6435bd17dd62
inputs: []
name: RCTDemo
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: def48d04-c52c-44ea-82eb-8503a29ccd59
      iscommand: false
      name: ""
      version: -1
    taskid: def48d04-c52c-44ea-82eb-8503a29ccd59
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    scriptarguments:
      XDRAlertDetails:
        simple: ${PaloAltoNetworksXDR.Incident.alerts}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: a6fe35f2-5cd6-4502-8685-3eafca684f29
      iscommand: false
      name: XDR Demo Playbook
      playbookId: ff1d730e-8379-458d-89a6-6fbb9491192f
      type: playbook
      version: -1
    taskid: a6fe35f2-5cd6-4502-8685-3eafca684f29
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
