contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 0144b6cd-1d8e-48c1-8705-5ec9e20589c5
inputs: []
name: Parse BU Data On Child Incidents
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c0ef6ff5-ccf3-48ba-8cfe-cefb80505984
      iscommand: false
      name: ""
      version: -1
    taskid: c0ef6ff5-ccf3-48ba-8cfe-cefb80505984
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 400,
          "y": 670
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: AssetDetails
      value:
        simple: ${incident.iocassetdetails}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 77796138-492f-4bc8-82c0-552f274c0459
      iscommand: false
      name: Store the Data in Context
      script: Set
      type: regular
      version: -1
    taskid: 77796138-492f-4bc8-82c0-552f274c0459
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 750,
          "y": 380
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 45371bf9-2413-4cc0-803d-e7ca1d7ed64e
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 45371bf9-2413-4cc0-803d-e7ca1d7ed64e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1430,
          "y": 770
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      csvArray:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: AssetDetails.Key
              operator: containsGeneral
              right:
                iscontext: true
                value:
                  simple: incident.accountname
          root: AssetDetails
      fileName:
        simple: TestIOCAsset.csv
      retry-count:
        simple: "1"
      retry-interval:
        simple: "10"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Export given array to csv file
      id: 9ca21049-8025-4cb2-80de-4fea7be53da3
      iscommand: false
      name: Export IOC Asset Info Based on BU
      script: ExportToCSV
      type: regular
      version: -1
    taskid: 9ca21049-8025-4cb2-80de-4fea7be53da3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 740,
          "y": 575
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      csvArray:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: VulAssetDetails.Key
              operator: containsGeneral
              right:
                iscontext: true
                value:
                  simple: incident.accountname
          root: VulAssetDetails
      fileName:
        simple: TestVulAsset.csv
      retry-count:
        simple: "1"
      retry-interval:
        simple: "10"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Export given array to csv file
      id: 5ec90563-ff84-427a-81fc-19ea8f56fcdf
      iscommand: false
      name: Export Vulnerable Assets Info Based on BU
      script: ExportToCSV
      type: regular
      version: -1
    taskid: 5ec90563-ff84-427a-81fc-19ea8f56fcdf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 575
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      emailhtml:
        simple: |-
          <html>
          <head><style>table, th, td { border:1px solid black;}</style>
          </head>
           <body>
            <p>Dear Team,</p>
             <p>Please find the below list:</p>
              <p>${Table}</p>
          </body>
          </html>
      emailnewrecipients:
        simple: sua@paloaltonetworks.com
      emailnewsubject:
        simple: ${incident.name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 88366e01-9606-47ae-8bb9-bb22ef92257d
      iscommand: true
      name: Set Email Properties
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 88366e01-9606-47ae-8bb9-bb22ef92257d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 400,
          "y": 1010
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: VulAssetDetails
      value:
        simple: ${incident.vulnerabilityassetdetails}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 0ddde087-22f9-4573-8c5e-67f85cad2c6e
      iscommand: false
      name: Store the Data in Context
      script: Set
      type: regular
      version: -1
    taskid: 0ddde087-22f9-4573-8c5e-67f85cad2c6e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 20,
          "y": 430
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${incident.vulnerabilityassetdetails}
          operator: isEqualString
          right:
            value:
              simple: "null"
      label: "yes"
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 86bcc1eb-04e1-4ee6-8585-722d36a5cd84
      iscommand: false
      name: Check if VulAsset deails exists or not?
      type: condition
      version: -1
    taskid: 86bcc1eb-04e1-4ee6-8585-722d36a5cd84
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 40,
          "y": 215
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${incident.iocassetdetails}
          operator: isEqualString
          right:
            value:
              simple: "null"
      label: "yes"
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4c65440c-45b9-432a-8683-a7c5ac1eb3f0
      iscommand: false
      name: Check if  IOCAsset deails exists or not?
      type: condition
      version: -1
    taskid: 4c65440c-45b9-432a-8683-a7c5ac1eb3f0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 570,
          "y": 215
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: '"| tstats summariesonly=t count FROM datamodel=Network_Traffic.All_Traffic
          GROUPBY All_Traffic.src_ip All_Traffic.dest_ip All_Traffic.index All_Traffic.action
          host sourcetype| search [inputlookup IOC_Scan_testing.csv | rename IP as
          All_Traffic.dest_ip| fields All_Traffic.dest_ip] |table All_Traffic.index,
          host, sourcetype, All_Traffic.dest_ip, All_Traffic.src_ip, All_Traffic.action
          | append [| tstats summariesonly=t count FROM datamodel=Network_Traffic.All_Traffic
          GROUPBY All_Traffic.src_ip All_Traffic.dest_ip All_Traffic.index All_Traffic.action
          host sourcetype| search [inputlookup IOC_Scan_testing.csv | rename IP as
          All_Traffic.src_ip| fields All_Traffic.src_ip]|table All_Traffic.index,host,
          sourcetype, All_Traffic.dest_ip, All_Traffic.src_ip, All_Traffic.action]"'
    separatecontext: false
    skipunavailable: false
    task:
      brand: SplunkPy_test_final_v2
      description: Searches Splunk for events.
      id: 8a62f779-ec27-4d68-87d2-5686e80033cd
      iscommand: true
      name: query splunk (for indicators in lookup file )
      script: SplunkPy_test_final_v2|||splunk-search
      type: regular
      version: -1
    taskid: 8a62f779-ec27-4d68-87d2-5686e80033cd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1390,
          "y": 430
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: '"| tstats summariesonly=t count FROM datamodel=Network_Traffic.All_Traffic
          GROUPBY All_Traffic.src_ip All_Traffic.dest_ip All_Traffic.index All_Traffic.action
          host sourcetype| search [inputlookup IOC_Scan_testing.csv | rename IP as
          All_Traffic.dest_ip| fields All_Traffic.dest_ip] |table All_Traffic.index,
          host, sourcetype, All_Traffic.dest_ip, All_Traffic.src_ip, All_Traffic.action
          | append [| tstats summariesonly=t count FROM datamodel=Network_Traffic.All_Traffic
          GROUPBY All_Traffic.src_ip All_Traffic.dest_ip All_Traffic.index All_Traffic.action
          host sourcetype| search [inputlookup IOC_Scan_testing.csv | rename IP as
          All_Traffic.src_ip| fields All_Traffic.src_ip]|table All_Traffic.index,host,
          sourcetype, All_Traffic.dest_ip, All_Traffic.src_ip, All_Traffic.action]"'
    separatecontext: false
    skipunavailable: false
    task:
      brand: SplunkPy_test_final_v2
      description: Searches Splunk for events.
      id: 3abd344e-f873-4438-84b3-42b0dba201aa
      iscommand: true
      name: query splunk (for indicators in lookup file )
      script: SplunkPy_test_final_v2|||splunk-search
      type: regular
      version: -1
    taskid: 3abd344e-f873-4438-84b3-42b0dba201aa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 120
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      attachment:
        simple: ${incident.attachment}
      new_thread:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Send email reply
        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: b0d44022-4da2-449b-8fe9-98b61ea66988
      iscommand: false
      name: Send Email to BU
      script: d4ff89db-151e-41fd-8719-471b2019098f
      type: regular
      version: -1
    taskid: b0d44022-4da2-449b-8fe9-98b61ea66988
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 400,
          "y": 1205
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      emailnewattachment:
        simple: ${incident.attachment}
      emailnewbody:
        simple: "htmlBody=\"<html>\n <body>\n\nDear Sec Reps,<br>\n<br>\n<style>\ntable
          {\n  font-family: calibri, sans-serif;\n  border-collapse: collapse;\n  width:
          100%;\n}\n\ntd, th {\n  border: 1px solid #dddddd;\n  text-align: left;\n
          \ padding: 8px;\n}\n\ntr:nth-child(even) {\n  background-color: #dddddd;\n}\n</style>\n<table>\n
          \ <tr>\n    <td>Situation</td>\n    \n\n  </tr>\n  <tr>\n    <td>${incident.situation}</td>\n\n
          \ </tr>\n  <tr>\n    <td>Assessment</td>\n    \n\n  </tr>\n    <tr>\n    \n
          \   <td>${incident.assessment}</td>\n\n  </tr>\n  <tr>\n    <td>Recommendation</td>\n
          \   \n\n  </tr>\n    <tr>\n    \n    <td>${incident.recommendation}</td>\n\n
          \ </tr>\n</table>\n<br>\nWe would like to seek your assistance to investigate
          the above. <br>\n<br>\nRegards,<br>\nNSOC<br>\n </body>\n</html>\""
      emailnewrecipients:
        simple: ${lists.NSOCRecipientsList}
      emailnewsubject:
        simple: ${incident.alertname}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 93e8cb5d-e4a3-4952-8910-d478b172c70a
      iscommand: true
      name: Set Email Properties
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 93e8cb5d-e4a3-4952-8910-d478b172c70a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 2107.5,
          "y": 50
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5a4f1740-c863-41bd-83e5-fda32129ad9d
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 5a4f1740-c863-41bd-83e5-fda32129ad9d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 400,
          "y": 1380
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Table
      value:
        simple: |-
          <table>
            <tr>
              <th>Indicator</th>
              <th>Type</th>
              <th>Verdict</th>
            </tr>
            <tr>
              <td>1.1.1.1</td>
              <td>IP</td>
              <td>Malicious</td>
            </tr>
            <tr>
              <td>1.3.2.1</td>
              <td>IP</td>
              <td>Suspicious</td>
            </tr>
          </table>
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 99aa63b0-92ca-4863-8789-b3460a16d1a7
      iscommand: false
      name: Set
      script: Set
      type: regular
      version: -1
    taskid: 99aa63b0-92ca-4863-8789-b3460a16d1a7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 400,
          "y": 800
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1395,
        "width": 2467.5,
        "x": 20,
        "y": 50
      }
    }
  }
