contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: f2f82edf-9118-4f3e-8ca4-b68b0240e31d
inputs:
- description: ""
  key: entry
  playbookInputQuery: null
  required: false
  value:
    simple: ${getListRow.Results}
name: verify SSL sub playbook
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b2dc7b57-dc0c-4449-8735-43e3d90f4d2a
      iscommand: false
      name: ""
      version: -1
    taskid: b2dc7b57-dc0c-4449-8735-43e3d90f4d2a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      Port:
        simple: ${inputs.entry.port}
      URL:
        simple: ${inputs.entry.url}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Use this automation to check for validity of your SSL certificate
        and get the time until expiration.
      id: 3df9c66e-8f51-4f68-8dcc-ad6dd0c65cef
      iscommand: false
      name: verify the SSL
      script: SSLVerifier
      type: regular
      version: -1
    taskid: 3df9c66e-8f51-4f68-8dcc-ad6dd0c65cef
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 240,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
