contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: a0d633f9-d3e1-44ac-8c57-5e37889a7bba
inputs:
- description: ""
  key: incidentid
  playbookInputQuery: null
  required: false
  value:
    simple: 90,91
name: XSOAR - ReOpen Incidents
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6caae716-7276-4122-8de2-f39e0daea6e7
      iscommand: false
      name: ""
      version: -1
    taskid: 6caae716-7276-4122-8de2-f39e0daea6e7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
