contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 37aa0873-5191-4ed6-8443-c60b432d7f31
inputs: []
name: pp_threatintel_load_twitter_indicators
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4ecce93c-f32b-4d17-8901-9f8e9acc3d52
      iscommand: false
      name: ""
      version: -1
    taskid: 4ecce93c-f32b-4d17-8901-9f8e9acc3d52
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      twitter_feed_path:
        simple: https://raw.githubusercontent.com/0xDanielLopez/TweetFeed/master/today.csv
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 87f1bab7-1f4e-4d80-84ca-d41bf9d7f42d
      iscommand: false
      name: Fetch and load intel feed
      script: pp_threatintel_fetch_twitter_feed
      type: regular
      version: -1
    taskid: 87f1bab7-1f4e-4d80-84ca-d41bf9d7f42d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      resolution:
        simple: Auto-closed
      resolutionsummary:
        simple: Auto-closed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e4cfd9cd-672b-4599-8385-10a8e72db0e8
      iscommand: false
      name: Close incident
      script: pp_CloseInvestigation_v2
      type: regular
      version: -1
    taskid: e4cfd9cd-672b-4599-8385-10a8e72db0e8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: '| inputlookup ecscti_feed_raw_twitter_via_demisto.csv |stats count'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c314282a-bff0-4236-8962-6c9102763c55
      iscommand: false
      name: Get number of indicators before loading today's data
      script: pp_splunk_search_v2
      type: regular
      version: -1
    taskid: c314282a-bff0-4236-8962-6c9102763c55
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: '| inputlookup ecscti_feed_raw_twitter_via_demisto.csv |stats count'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8a8b8143-e71a-42f8-8931-e241b69d09aa
      iscommand: false
      name: Get number of indicators after loading today's data
      script: pp_splunk_search_v2
      type: regular
      version: -1
    taskid: 8a8b8143-e71a-42f8-8931-e241b69d09aa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
