contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: de98086e-b00e-4d50-8e2f-907ff3e25406
inputs: []
name: DemoPhishingPlaybook
outputs: []
quiet: true
sourceplaybookid: 44714b23-df94-4581-829e-401cf9234a33
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 96ee6427-02ed-4f5b-8187-66a9cbf016ce
      iscommand: false
      name: ""
      version: -1
    taskid: 96ee6427-02ed-4f5b-8187-66a9cbf016ce
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 2
    reputationcalc: 1
    scriptarguments:
      columns:
        simple: emailfrom,emailsubject,sourceip,destinationip,filemd5
      data:
        simple: ${incident}
      title:
        simple: IOC Details
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Convert an array to a nice table display. Usually, from the context.
      id: cb4b1460-1701-44af-82a9-fbc5839d5173
      iscommand: false
      name: To Table
      script: ToTable
      type: regular
      version: -1
    taskid: cb4b1460-1701-44af-82a9-fbc5839d5173
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b7c62f6a-c25b-42e1-802a-d57fab6589c9
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: b7c62f6a-c25b-42e1-802a-d57fab6589c9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 570
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 2
    scriptarguments:
      CloseSimilar:
        simple: "1"
      closeReason:
        simple: 'Duplicate incident to '
      fieldsToDisplay:
        simple: id,name,createdsourceip,destionationip,filemd5
      fromDate:
        simple: 24 hours ago
      handleSimilar:
        simple: Link and Close
      limit:
        simple: "1"
      method:
        simple: Fields
      minimunIncidentSimilarity:
        simple: "0.5"
      query:
        simple: -status:closed -category:job
      showIncidentSimilarityForAllFields:
        simple: "True"
      similarTextField:
        simple: sourceip,filemd5
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: "This playbook identifies duplicate incidents using the Cortex
        XSOAR machine learning method (script).\nIn this playbook, you can choose
        fields and/or indicators to be compared against other incidents in the Cortex
        XSOAR database. \n\nNote: To identify similar incidents you must *must* properly
        define the playbook inputs. "
      id: 22ca8b54-4d4a-4688-803e-47859e9d2cc4
      iscommand: false
      name: Dedup - Generic v4_Custom
      playbookId: 91702eff-03d2-4b26-800b-70528f43af17
      type: playbook
      version: -1
    taskid: 22ca8b54-4d4a-4688-803e-47859e9d2cc4
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1470,
          "y": 380
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 425,
        "width": 1400,
        "x": 450,
        "y": 210
      }
    }
  }
