contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 4afe4fe0-d62e-40d4-8cc6-0ba4c8069083
inputs: []
name: read csv file playbook
outputs: []
quiet: true
sourceplaybookid: 5a3383e6-a01d-4d17-8ac0-80e693468c43
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4099035a-5434-4e28-8bd6-42f0c1a11560
      iscommand: false
      name: ""
      version: -1
    taskid: 4099035a-5434-4e28-8bd6-42f0c1a11560
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Pls upload the file here
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: attachments
      sender: ""
      title: upload the file
      totalanswers: 0
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: null
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e36f2beb-74a7-43fe-8488-7c205b0ef694
      iscommand: false
      name: upload the csv  file
      type: collection
      version: -1
    taskid: e36f2beb-74a7-43fe-8488-7c205b0ef694
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 2
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Load the contents of a file into context.
      id: f5619e9f-260d-45e5-83d9-eb9b60407f74
      iscommand: false
      name: read the csv file
      script: ReadFile
      type: regular
      version: -1
    taskid: f5619e9f-260d-45e5-83d9-eb9b60407f74
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      listData:
        simple: ${FileData}
      listName:
        simple: testList
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.add
      id: 6172e944-7525-43c4-8d5d-b61c65be2e9b
      iscommand: true
      name: add the csv data to LIST
      script: Builtin|||addToList
      type: regular
      version: -1
    taskid: 6172e944-7525-43c4-8d5d-b61c65be2e9b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 580
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 625,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
