contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: fb4716be-86c0-48c4-8d2f-80c9c99952bb
inputs: []
name: Demo - Sub Playbook Output
outputs:
- contextPath: UserResponse
  type: unknown
- contextPath: IP.Address
  description: Bad IP address.
- contextPath: IP.Geo.Country
  description: Bad IP country.
- contextPath: DBotScore.Score
  type: unknown
- contextPath: DBotScore.Vendor
  description: The vendor used to calculate the score.
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8d3e3907-c2ad-474d-8d49-f18ac2c5d196
      iscommand: false
      name: ""
      version: -1
    taskid: 8d3e3907-c2ad-474d-8d49-f18ac2c5d196
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 460,
          "y": 50
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 2
    scriptarguments:
      ignore-outputs:
        simple: "false"
      ip:
        simple: 8.8.8.8
    separatecontext: false
    skipunavailable: false
    task:
      brand: VirusTotal (API v3)
      description: Checks the reputation of an IP address.
      id: 96b352cf-ff23-4a20-8a3c-f5f8c89efacc
      iscommand: true
      name: check IP reputation
      script: VirusTotal (API v3)|||ip
      type: regular
      version: -1
    taskid: 96b352cf-ff23-4a20-8a3c-f5f8c89efacc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 190
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: UserResponse=
      userdetails:
        simple: block
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: d3db38d2-c00b-407e-8aa4-29bc5c6bc1bf
      iscommand: true
      name: setIncident
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: d3db38d2-c00b-407e-8aa4-29bc5c6bc1bf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 150,
          "y": 580
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: UserResponse=
      userdetails:
        simple: unblock
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 3dd07f04-65da-4f38-8f42-4be067b14fa1
      iscommand: true
      name: setIncident field userdetails to unblock
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 3dd07f04-65da-4f38-8f42-4be067b14fa1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 980,
          "y": 570
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      block:
      - "6"
      unblock:
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e72128b9-c63b-4789-81a4-bd8442091e09
      iscommand: false
      name: Ask user to block
      type: condition
      version: -1
    taskid: e72128b9-c63b-4789-81a4-bd8442091e09
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 460,
          "y": 340
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 625,
        "width": 1210,
        "x": 150,
        "y": 50
      }
    }
  }
