contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 109a73cb-1720-4e2c-83b0-5463f2690fda
inputs: []
name: Quiet mode SPB
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4484e4dd-38ee-4c04-898c-bb8eb0e1899d
      iscommand: false
      name: ""
      version: -1
    taskid: 4484e4dd-38ee-4c04-898c-bb8eb0e1899d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 980,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Hello 1 SPB
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 68fcbc99-18df-4e2c-8899-5966cd7257a7
      iscommand: false
      name: Print 1
      script: Print
      type: regular
      version: -1
    taskid: 68fcbc99-18df-4e2c-8899-5966cd7257a7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 980,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Hello 2 SPB
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: a095c1a4-586e-43ce-8ab9-20ae85a09634
      iscommand: false
      name: Print 2
      script: Print
      type: regular
      version: -1
    taskid: a095c1a4-586e-43ce-8ab9-20ae85a09634
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 980,
          "y": 390
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 435,
        "width": 380,
        "x": 980,
        "y": 50
      }
    }
  }
