contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 1e5adb84-1488-46a7-8bf5-3c5cd87b2b33
inputs:
- description: ""
  key: IncidentID
  playbookInputQuery: null
  required: false
  value: {}
name: Pause Playbook Execution
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8d2e4a86-2d83-4871-8eef-465504510c28
      iscommand: false
      name: ""
      version: -1
    taskid: 8d2e4a86-2d83-4871-8eef-465504510c28
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      uri:
        simple: /investigation/${inputs.IncidentID}/pause
    separatecontext: false
    skipunavailable: false
    task:
      brand: Core REST API
      description: send HTTP POST request.
      id: 83966170-6e4c-4992-8607-d02524974e82
      iscommand: true
      name: Pause the playbook investigation
      script: Core REST API|||demisto-api-post
      type: regular
      version: -1
    taskid: 83966170-6e4c-4992-8607-d02524974e82
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 240
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 285,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
