contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: ff8982b1-3398-4ebf-8632-f45caf0c8c59
inputs: []
name: SplunkTest
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a8dd19cd-d0e9-40e1-881d-b1e11e4115e0
      iscommand: false
      name: ""
      version: -1
    taskid: a8dd19cd-d0e9-40e1-881d-b1e11e4115e0
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: SplunkPy_instance_BNET
    separatecontext: false
    skipunavailable: false
    task:
      brand: SplunkPy
      description: Query Splunk to retrieve a list of sample alerts by alert type.
        Used for mapping fetched incidents through the Get Schema option.
      id: 9b614428-c055-4cfe-8933-88af23480eba
      iscommand: true
      name: Splunk Test
      script: SplunkPy|||get-mapping-fields
      type: regular
      version: -1
    taskid: 9b614428-c055-4cfe-8933-88af23480eba
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 240
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      ip:
        simple: ${IP}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Provides data enrichment for ips.
      id: 5578d000-d2dc-41de-8623-a5837d57d79c
      iscommand: true
      name: Ip Reputation
      script: '|||ip'
      type: regular
      version: -1
    taskid: 5578d000-d2dc-41de-8623-a5837d57d79c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 430
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      body:
        simple: "Hi, \n\nWe have received an alert from ${incident.sourceInstance}
          and type is ${incident.type}\n\nPlease take below actions\n1) Action1\n2)
          Action2\n\n${IP.Address} - ${IP.Geo.Country}\nRegards,\n"
      subject:
        simple: ${incident.id} - ${incident.description}
      to:
        simple: test@email.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends an email.
      id: b1cc578d-0aea-4a24-848a-9fee4feae97b
      iscommand: true
      name: Send Notification
      script: '|||send-mail'
      type: regular
      version: -1
    taskid: b1cc578d-0aea-4a24-848a-9fee4feae97b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 620
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2949f35a-4d3a-48fb-8188-0c72d73a4a9a
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: 2949f35a-4d3a-48fb-8188-0c72d73a4a9a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 780
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 795,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
