contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: f2b02c08-1813-4d75-881b-967233f8f5f5
inputs: []
name: AlertingHealthCheckActionableItems
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c913f967-b873-4ad8-89c5-5968893b19b9
      iscommand: false
      name: ""
      version: -1
    taskid: c913f967-b873-4ad8-89c5-5968893b19b9
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      fromdate:
        simple: 7 days ago
      type:
        simple: System Diagnostics and Health Check
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Searches Demisto incidents.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: 4a0872dc-1241-4d25-8772-e6c51dbd74ea
      iscommand: false
      name: Search for HealthCheck Incidents
      script: SearchIncidentsV2
      type: regular
      version: -1
    taskid: 4a0872dc-1241-4d25-8772-e6c51dbd74ea
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "3"
    note: false
    quietmode: 2
    scriptarguments:
      value:
        simple: ${foundIncidents.CustomFields.healthcheckactionableitems.category}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: da4641c5-c14a-4772-8836-7682b744aaba
      iscommand: false
      name: Validate if any Actionable items present or not?
      script: Exists
      type: condition
      version: -1
    taskid: da4641c5-c14a-4772-8836-7682b744aaba
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      closeNotes:
        simple: No Actionable item, Hence closing the case.
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 95783cd3-0958-434c-8370-36864659cba9
      iscommand: true
      name: No Actionable item, Hence closing the case.
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 95783cd3-0958-434c-8370-36864659cba9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 900,
          "y": 630
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 675,
        "width": 830,
        "x": 450,
        "y": 50
      }
    }
  }
