contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 7f38c643-f98c-4aa2-82a3-331ee2397ff4
inputs: []
name: GetQradarOffenseandUpdateListwithID
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6d7bd335-5ab5-4895-8fd8-79f0aca3fdec
      iscommand: false
      name: ""
      version: -1
    taskid: 6d7bd335-5ab5-4895-8fd8-79f0aca3fdec
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: id
      value:
        simple: ${lists.test}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 1549f764-4c25-4628-85c4-343dbbe67525
      iscommand: false
      name: Get ID
      script: Set
      type: regular
      version: -1
    taskid: 1549f764-4c25-4628-85c4-343dbbe67525
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      filter:
        simple: id>${id}
      range:
        simple: 0-10
    separatecontext: false
    skipunavailable: false
    task:
      brand: QRadar v3
      description: Gets offenses from QRadar.
      id: d2eb72b1-9201-4904-8e65-8c006ba6a49d
      iscommand: true
      name: Get Offense
      script: QRadar v3|||qradar-offenses-list
      type: regular
      version: -1
    taskid: d2eb72b1-9201-4904-8e65-8c006ba6a49d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      listData:
        simple: ${lists.test}
      listName:
        simple: test
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.remove
      id: 2d760e06-1d05-4cfb-8d1e-1dbe1a5b2107
      iscommand: true
      name: RemoveDatafromlist
      script: Builtin|||removeFromList
      type: regular
      version: -1
    taskid: 2d760e06-1d05-4cfb-8d1e-1dbe1a5b2107
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      idoffense:
        simple: ${QRadar.Offense.ID}
      name:
        simple: ${QRadar.Offense.Description}
      occurred:
        simple: ${QRadar.Offense.StartTime}
      sourcecategory:
        simple: siem
      sourceip:
        simple: ${QRadar.Offense.SourceAddress}
      type:
        simple: Simulation
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.create.inc
      id: f9b96475-cc1c-4476-8ba5-dc40e60b627a
      iscommand: true
      name: CreateIncident
      script: Builtin|||createNewIncident
      type: regular
      version: -1
    taskid: f9b96475-cc1c-4476-8ba5-dc40e60b627a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      listData:
        complex:
          accessor: ID
          root: QRadar.Offense
          transformers:
          - operator: LastArrayElement
      listName:
        simple: test
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.add
      id: fa7a4ac1-dc09-466d-8e88-f18061841cc3
      iscommand: true
      name: Set Data in list
      script: Builtin|||addToList
      type: regular
      version: -1
    taskid: fa7a4ac1-dc09-466d-8e88-f18061841cc3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: c01456a1-c96a-4597-8353-90819bdbc445
      iscommand: true
      name: Close
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: c01456a1-c96a-4597-8353-90819bdbc445
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1050
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1095,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
