contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.5.0
    itemVersion: 1.0.4
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: This playbook receives indicators from its parent playbook and provides
  the indicators as inputs for the sub-playbooks that push the indicators to the SIEM.
id: 473dc5a5-a9ce-4293-88a8-26200f4b4a72
inputs:
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: ""
    queryEntity: indicators
    results: null
    runFromLastJobTime: false
  required: false
  value: {}
name: TIM - Add Domain Indicators To SIEM_DEMO
outputs: []
quiet: true
sourceplaybookid: TIM - Add Domain Indicators To SIEM
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 26891d2e-12ed-4161-88f0-327e2fa6016d
      iscommand: false
      name: ""
      version: -1
    taskid: 26891d2e-12ed-4161-88f0-327e2fa6016d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -200
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e0105294-ee8a-4db2-8810-918390493b82
      iscommand: false
      name: QRadar
      type: title
      version: -1
    taskid: e0105294-ee8a-4db2-8810-918390493b82
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 990,
          "y": 210
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: modules.brand
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: modules.brand
          operator: isEqualString
          right:
            value:
              simple: QRadar v3
      - - left:
            iscontext: true
            value:
              simple: modules.state
          operator: isEqualString
          right:
            value:
              simple: active
      label: "yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 125d489b-7134-4d0d-8278-144aef6edde3
      iscommand: false
      name: Is Qradar enabled?
      type: condition
      version: -1
    taskid: 125d489b-7134-4d0d-8278-144aef6edde3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 990,
          "y": 360
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1815fc21-600a-4d26-8ba0-084a01dbcc1c
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 1815fc21-600a-4d26-8ba0-084a01dbcc1c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 780
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1f7fb4ab-b289-4da0-8ca6-ed1a96861a6a
      iscommand: false
      name: ArcSight
      type: title
      version: -1
    taskid: 1f7fb4ab-b289-4da0-8ca6-ed1a96861a6a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -80,
          "y": 210
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: modules.brand
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: modules.brand
          operator: isEqualString
          right:
            value:
              simple: ArcSight ESM v2
      - - left:
            iscontext: true
            value:
              simple: modules.state
          operator: isEqualString
          right:
            value:
              simple: active
      label: "yes"
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1c94e580-a35c-4f37-8eb0-e5000b935edc
      iscommand: false
      name: Is ArcSight enabled?
      type: condition
      version: -1
    taskid: 1c94e580-a35c-4f37-8eb0-e5000b935edc
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -80,
          "y": 360
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: playbookQuery.indicator_type
          operator: isEqualString
          right:
            value:
              simple: Domain
      label: "yes"
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "5"
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6aa730d3-01e8-4cbe-8247-c32ef076687d
      iscommand: false
      name: Are there Domain results?
      type: condition
      version: -1
    taskid: 6aa730d3-01e8-4cbe-8247-c32ef076687d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": -50
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 3705f0a6-bd9c-4395-8818-7952e26f6368
      iscommand: false
      name: TIM - ArcSight Add Domain Indicators
      playbookId: TIM - ArcSight Add Domain Indicators
      type: playbook
      version: -1
    taskid: 3705f0a6-bd9c-4395-8818-7952e26f6368
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -190,
          "y": 600
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      QRadarBlackListDomainReferenceSetName:
        simple: TIM_BlackList_Domain
      QRadarWhiteListDomainReferenceSetName:
        simple: TIM_WhiteList_Domain
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 50c3da2d-7ac8-4a6b-87f4-03861a8a9ebb
      iscommand: false
      name: TIM - QRadar Add Domain Indicators_DEMO
      playbookId: d88dd0c8-a8ff-408c-86c3-65b7522a0fdb
      type: playbook
      version: -1
    taskid: 50c3da2d-7ac8-4a6b-87f4-03861a8a9ebb
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1110,
          "y": 590
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1045,
        "width": 1680,
        "x": -190,
        "y": -200
      }
    }
  }
