contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 4f03c5b3-5bbc-4cb9-85a3-7c2b839544dc
inputs:
- description: ""
  key: 'Email '
  playbookInputQuery: null
  required: false
  value:
    simple: ${Parsed.Email}
name: Send Email - Dormant Accounts
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ac1c2cd0-afff-43b5-8af3-329838848ecf
      iscommand: false
      name: ""
      version: -1
    taskid: ac1c2cd0-afff-43b5-8af3-329838848ecf
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 40
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      body:
        simple: Hi This Test email
      subject:
        simple: Dormant Account Exception
      to:
        simple: ${inputs.Email }
    separatecontext: false
    skipunavailable: false
    task:
      brand: Gmail Single User
      description: Sends an email using Gmail.
      id: 253ac0a2-03df-4ad8-8be0-9e0545b15577
      iscommand: true
      name: Send Email to users
      script: Gmail Single User|||send-mail
      type: regular
      version: -1
    taskid: 253ac0a2-03df-4ad8-8be0-9e0545b15577
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 265,
        "width": 380,
        "x": 450,
        "y": 40
      }
    }
  }
