contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 4ecd9591-1fd9-42bc-884b-01fde7ca0aca
inputs: []
name: Demo closure
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 08daa8df-c09e-4044-80ba-86fba0f9716c
      iscommand: false
      name: ""
      version: -1
    taskid: 08daa8df-c09e-4044-80ba-86fba0f9716c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      closeNotes:
        simple: Test
      closeReason:
        simple: ${Incident Closure.Answers.0}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 5571861f-e723-402a-8e68-598fdf95fabf
      iscommand: true
      name: close incident
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 5571861f-e723-402a-8e68-598fdf95fabf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
  "2":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: closereason
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Select the close reason
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: singleSelect
      sender: ""
      title: Incident Closure
      totalanswers: 0
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: null
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7fb2fb71-06b5-4ad0-8b5c-825cff129352
      iscommand: false
      name: Incident Closure
      type: collection
      version: -1
    taskid: 7fb2fb71-06b5-4ad0-8b5c-825cff129352
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 450,
          "y": 170
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 445,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
