contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: ad90ddbf-a6b6-4ad7-89a9-8cba746592bf
inputs: []
name: Test - Playbook Error Mode
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e99bb08a-877c-4cbe-8fd5-38dc6e6f7465
      iscommand: false
      name: ""
      version: -1
    taskid: e99bb08a-877c-4cbe-8fd5-38dc6e6f7465
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: errorPath
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "4"
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      email:
        simple: sua@paloaltonetworks.com
      message:
        simple: Test
      subject:
        simple: 'Test '
    separatecontext: false
    skipunavailable: false
    task:
      brand: Gmail Single User
      description: Ask a user a question via email and process the reply directly
        into the investigation.
      id: c25efda1-e0ad-4514-8629-bb9add2cbaae
      iscommand: false
      name: Send Email
      script: EmailAskUser
      type: regular
      version: -1
    taskid: c25efda1-e0ad-4514-8629-bb9add2cbaae
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Mail Sent
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 472f6963-f88c-47e7-8a50-4bd05882f715
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 472f6963-f88c-47e7-8a50-4bd05882f715
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 620
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: errorPath
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      email:
        simple: sua@paloaltonetworks.com
      message:
        simple: Test
      subject:
        simple: 'Test '
    separatecontext: false
    skipunavailable: false
    task:
      brand: Gmail Single User
      description: Ask a user a question via email and process the reply directly
        into the investigation.
      id: c26d3b15-b9c0-4680-8e05-1c8d5b545c1f
      iscommand: false
      name: Send Email
      script: EmailAskUser
      type: regular
      version: -1
    taskid: c26d3b15-b9c0-4680-8e05-1c8d5b545c1f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 100,
          "y": 390
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 665,
        "width": 730,
        "x": 100,
        "y": 50
      }
    }
  }
