contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: GetAllAPIEndpointsV1 Contribution Pack
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 3406a71b-b75c-421a-8aae-70a1e066a428
inputs: []
name: GetAllAPIEndpointsV1
outputs: []
quiet: true
sourceplaybookid: ec464f90-0055-4cc2-86aa-7bef0f50b45f
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cec925e0-e07c-4c8b-8454-0d37aec02c78
      iscommand: false
      name: ""
      version: -1
    taskid: cec925e0-e07c-4c8b-8454-0d37aec02c78
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cf54ccfc-56c9-47eb-85f8-f265e081233c
      iscommand: false
      name: Validate the Demisto API Integration
      script: e68ee5d1-04c3-4bc5-88b2-87848befb278
      type: regular
      version: -1
    taskid: cf54ccfc-56c9-47eb-85f8-f265e081233c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: RESTAPIInstaceDetails.InstanceName
          operator: isExists
          right:
            value: {}
      label: "Yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "Yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9804c315-f68e-4aca-8328-700b69bfaa7b
      iscommand: false
      name: Check the instance is enabled or not
      type: condition
      version: -1
    taskid: 9804c315-f68e-4aca-8328-700b69bfaa7b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e379acc6-c389-4e8f-83c0-1958c22d1d77
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: e379acc6-c389-4e8f-83c0-1958c22d1d77
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -200,
          "y": 1280
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      BrandName:
        simple: ${RESTAPIInstaceDetails.Brand}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 80658bc6-99da-4919-8ea3-cff78752c794
      iscommand: false
      name: Get Automation API Endpoints
      script: a1a1467e-90d2-485a-827d-30a668ec1820
      type: regular
      version: -1
    taskid: 80658bc6-99da-4919-8ea3-cff78752c794
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      BrandName:
        simple: ${RESTAPIInstaceDetails.Brand}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1282be69-100a-447b-8c0a-fa1e0cdfc5c1
      iscommand: false
      name: Get All API Endpoints in Playbooks
      script: c8dee4ee-be77-424c-8855-7789cb25e7a0
      type: regular
      version: -1
    taskid: 1282be69-100a-447b-8c0a-fa1e0cdfc5c1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "6"
      "yes":
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${APIEndpoints.URI}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 9fbc0ba5-c246-4073-8e2d-1f65a1608d24
      iscommand: false
      name: Check API Endpoints Results exists?
      script: Exists
      type: condition
      version: -1
    taskid: 9fbc0ba5-c246-4073-8e2d-1f65a1608d24
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 2
    scriptarguments:
      csvArray:
        simple: ${APIEndpoints}
      fileName:
        simple: APIURIData.csv
      headers:
        simple: URI
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Export given array to csv file
      id: 119180b8-7050-42e5-8069-fd030b3e24e2
      iscommand: false
      name: Export API URIs to CSV
      script: ExportToCSV
      type: regular
      version: -1
    taskid: 119180b8-7050-42e5-8069-fd030b3e24e2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 690,
          "y": 1070
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "9_6_no": 0.27
    },
    "paper": {
      "dimensions": {
        "height": 1295,
        "width": 1270,
        "x": -200,
        "y": 50
      }
    }
  }
