contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: c2234bb5-fa3e-478d-81bd-a6d4fe0a6463
inputs: []
name: Test - Quiet Mode
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3cb794b6-2574-474b-8744-25f0b5b7090b
      iscommand: false
      name: ""
      version: -1
    taskid: 3cb794b6-2574-474b-8744-25f0b5b7090b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 10
    note: false
    quietmode: 1
    scriptarguments:
      IP:
        simple: ${ExtractedIndicators.IP}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6359a44c-1c89-420a-8f7b-3e7ca56e90fd
      iscommand: false
      name: Test - ExtendedContext
      playbookId: 76e2c9ee-25d8-4ac4-885f-f13e1c66d1ff
      type: playbook
      version: -1
    taskid: 6359a44c-1c89-420a-8f7b-3e7ca56e90fd
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
