contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 7ef534b6-8ebf-46a1-8c71-f11c2b98e59b
inputs: []
name: Data Collection - With Time Based TaskComplete_copy
outputs: []
sourceplaybookid: 0a61db7c-db01-4579-8476-4b3789e28822
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7c80dfa5-9f37-4652-84b5-e482e0411619
      iscommand: false
      name: ""
      version: -1
    taskid: 7c80dfa5-9f37-4652-84b5-e482e0411619
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Favorite Cartoon?
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: shortText
      sender: ""
      title: Survey
      totalanswers: 0
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: This is a Data Collection Task
      cc: null
      format: ""
      methods:
      - email
      subject:
        simple: Sample survey
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: false
        retriescount: 1
        retriesinterval: 360
      to:
        simple: shapatil@paloaltonetworks.com
    nexttasks:
      '#none#':
      - "11"
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    sla:
      days: 0
      hours: 1
      minutes: 0
      weeks: 0
    task:
      brand: ""
      id: be74ba79-a6a9-4e92-84d3-e0c3c06de3e8
      iscommand: false
      name: Collect Data
      type: collection
      version: -1
    taskid: be74ba79-a6a9-4e92-84d3-e0c3c06de3e8
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 093905ce-5edb-45f4-877f-757ea7fa3d3b
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 093905ce-5edb-45f4-877f-757ea7fa3d3b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Survey.Answers.name
          operator: isExists
      label: "Yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "Yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Check if there is name under the Answers entry in context, if there is, it means there were answers to the Data Collection
        A different logic can be applied here as well
      id: c8b5874d-a93e-4d8f-8a14-b01c42257cb6
      iscommand: false
      name: Check if we got answers
      type: condition
      version: -1
    taskid: c8b5874d-a93e-4d8f-8a14-b01c42257cb6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${Survey.Answers.0} is responded by ${Survey.Answers.name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 922ea65c-1bda-4982-85ae-13783f73556d
      iscommand: false
      name: Found Answers
      script: Print
      type: regular
      version: -1
    taskid: 922ea65c-1bda-4982-85ae-13783f73556d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: DC
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: |-
        Complete the Data Collection Task (based on the tag 'DC')
        Set to not stop on error, so if the Data Collection was already completed by a reply, this task is not going to fail
      id: 7f61e58e-d7d2-4fe8-8fbb-bda74e7ec863
      iscommand: true
      name: Complete Data Collection
      script: Builtin|||taskComplete
      type: regular
      version: -1
    taskid: 7f61e58e-d7d2-4fe8-8fbb-bda74e7ec863
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 510,
          "y": 540
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: gotResponse
      value:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 68aedc82-44d2-4472-8251-1b767cf2f30e
      iscommand: false
      name: Got response
      script: Set
      type: regular
      version: -1
    taskid: 68aedc82-44d2-4472-8251-1b767cf2f30e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      dt:
        simple: Survey.Answers(val.name !== "")
      ids:
        simple: Sending an email
      interval:
        simple: "1"
      pollingCommand:
        simple: Print
      pollingCommandArgName:
        simple: value
      tag:
        simple: polling
      timeout:
        simple: "60"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Called by the GenericPolling playbook, schedules the polling task.
      id: 340810cb-f885-4e29-80fb-db419e652439
      iscommand: false
      name: generic polling task
      script: ScheduleGenericPolling
      tags:
      - DC
      type: regular
      version: -1
    taskid: 340810cb-f885-4e29-80fb-db419e652439
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "3_4_Yes": 0.76
    },
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 1240,
        "x": 50,
        "y": 50
      }
    }
  }
