contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: ac10d8f7-b4f7-4e92-8173-3a05cef60248
inputs:
- description: ""
  key: incidentid
  playbookInputQuery: null
  required: false
  value: {}
name: GetUserConsentonXDRInvestigation
outputs:
- contextPath: EmailAskUserResponse
  description: userresponse
  type: string
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 59b14a98-2ba3-4d27-8c24-782edad79a00
      iscommand: false
      name: ""
      version: -1
    taskid: 59b14a98-2ba3-4d27-8c24-782edad79a00
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      incidentId:
        simple: ${inputs.incidentid}
      name:
        simple: XDRInvestigation
      type:
        simple: pdf
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.summaryReport
      id: 3e802c34-9d85-4624-8122-1df49c169682
      iscommand: true
      name: Generate Report
      script: Builtin|||generateSummaryReport
      type: regular
      version: -1
    taskid: 3e802c34-9d85-4624-8122-1df49c169682
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      attachIds:
        complex:
          accessor: EntryID
          filters:
          - - left:
                iscontext: true
                value:
                  simple: InfoFile.Extension
              operator: isEqualString
              right:
                value:
                  simple: pdf
          root: InfoFile
      message:
        simple: "Hi User, \n\nPlease go through the report and reply \"yes\" if you
          want to block IOC and \"no\" If you dont want to block IOC"
      option1:
        simple: "yes"
      option2:
        simple: "no"
      subject:
        simple: Block IOC Yes or No
      task:
        simple: response
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Ask a user a question via email and process the reply directly
        into the investigation.
      id: 2de41da1-e20f-44ec-8884-8256fcaa7e9b
      iscommand: false
      name: emailAskUser
      script: EmailAskUser
      type: regular
      version: -1
    taskid: 2de41da1-e20f-44ec-8884-8256fcaa7e9b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f38d9bb8-e4fd-4a7d-8c66-a0d58887cdb8
      iscommand: false
      name: This is an Automated Task, do not close manually
      tags:
      - response
      type: regular
      version: -1
    taskid: f38d9bb8-e4fd-4a7d-8c66-a0d58887cdb8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "No":
      - "6"
      "Yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      responseEntryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Extract user's response from EmailAskUser reply. Returns the first
        textual response line of the provided entry that contains the reply body.
        Use ${lastCompletedTaskEntries} to analyze the previous playbook task containing
        the user's reply.
      id: fd0220af-3773-416c-81de-dcbee554f047
      iscommand: false
      name: Validate User Response
      script: EmailAskUserResponse
      type: condition
      version: -1
    taskid: fd0220af-3773-416c-81de-dcbee554f047
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: userresponse
      value:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 38281263-acf9-476c-8515-2a6784bd91a3
      iscommand: false
      name: User Response yes
      script: Set
      type: regular
      version: -1
    taskid: 38281263-acf9-476c-8515-2a6784bd91a3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: userresponse
      value:
        simple: "no"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 5c3236c3-460b-4534-8ec6-ce0bbef98ee9
      iscommand: false
      name: User Response no
      script: Set
      type: regular
      version: -1
    taskid: 5c3236c3-460b-4534-8ec6-ce0bbef98ee9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9ce70a0d-be93-44d3-83cf-a49d305bd71f
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 9ce70a0d-be93-44d3-83cf-a49d305bd71f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1085,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
