contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 72a38be4-8d8b-463d-88f1-3a16324aee6a
inputs: []
name: email send v4
outputs: []
quiet: true
sourceplaybookid: 3a4f4315-6e77-4b29-8799-c922921edb01
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f827f620-8bc5-40d4-8378-de1bb4bfb779
      iscommand: false
      name: ""
      version: -1
    taskid: f827f620-8bc5-40d4-8378-de1bb4bfb779
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 150,
          "y": -515
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      emailnewbody:
        simple: |-
          <!DOCTYPE html>
          <html>

          <table>
          <thead>
          <tr>
          <th>ID</th>
          <th>CSPID</th>
          <th>Email</th>
          <th>SponserID</th>
          <th>SEmail</th>
          </tr>
          </thead>

          <tbody>
          <tr>
          <td>4</td>
          <td>emp123</td>
          <td>test@test.com</td>
          <td>123</td>
          <td>cortexxsoar2023@gmail.com</td>
          </tr>

          <tr>
          <td>3</td>
          <td>emp789</td>
          <td>def@test.com</td>
          <td>123</td>
          <td>cortexxsoar2023@gmail.com</td>
          </tr>

          <tr>
          <td>5</td>
          <td>emp1213</td>
          <td>jkl@test.com</td>
          <td>123</td>
          <td>cortexxsoar2023@gmail.com</td>
          </tr>
          </tbody>
          </table>

          </body>
          </html>
      emailnewrecipients:
        simple: sua@paloaltonetworks.com
      emailnewsubject:
        simple: Test Email Communication 4
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 38e397bc-6683-4d3e-8d99-97c772838ce6
      iscommand: true
      name: Set Incident Fields
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 38e397bc-6683-4d3e-8d99-97c772838ce6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 130,
          "y": -80
        }
      }
  "2":
    continueonerrortype: ""
    evidencedata:
      customfields: {}
      description:
        simple: User Email Communication
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 2
    scriptarguments:
      mail_sender_instance:
        simple: Gmail Single User_instance_1
      new_thread:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Send email reply
        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: a7341f98-05e0-4d72-8077-cc2327a5695b
      iscommand: false
      name: Send Email
      script: SendEmailReply
      type: regular
      version: -1
    taskid: a7341f98-05e0-4d72-8077-cc2327a5695b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 130,
          "y": 130
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      sla:
        simple: "600"
      slaField:
        simple: demosla
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: b15fad21-7d4d-4d68-8287-40686cac10be
      iscommand: true
      name: Set SLA
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: b15fad21-7d4d-4d68-8287-40686cac10be
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -430,
          "y": 670
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9f55a66d-ead1-4190-8c54-4ce5133007bb
      iscommand: false
      name: wait for user response
      tags:
      - userreply2
      type: regular
      version: -1
    taskid: 9f55a66d-ead1-4190-8c54-4ce5133007bb
    timertriggers:
    - action: start
      fieldname: demosla
    type: regular
    view: |-
      {
        "position": {
          "x": -440,
          "y": 840
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: true
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "60"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds.
      id: 922cd4cc-3da8-4911-84a5-5b4541ae83d1
      iscommand: false
      name: Sleep 1 min
      script: Sleep
      type: regular
      version: -1
    taskid: 922cd4cc-3da8-4911-84a5-5b4541ae83d1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 130,
          "y": 300
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: email-${incident.id}
      timeout:
        simple: "500"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Demisto Lock
      description: Gets a specific lock. If the lock doesn't exist, it creates one.
        If the lock is already in use, the command waits until the lock is released
        or until timeout is reached. If timeout is reached and the lock hasn't been
        released, the command fails to get the lock.
      id: e1cd7c2a-d57e-4b4b-8070-085838e4b2c3
      iscommand: true
      name: demisto lock
      script: Demisto Lock|||demisto-lock-get
      type: regular
      version: -1
    taskid: e1cd7c2a-d57e-4b4b-8070-085838e4b2c3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 140,
          "y": -260
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: email-${incident.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Demisto Lock
      description: Release a lock
      id: 11d4f653-f716-430d-835c-960871712f64
      iscommand: true
      name: demisto release lock
      script: Demisto Lock|||demisto-lock-release
      type: regular
      version: -1
    taskid: 11d4f653-f716-430d-835c-960871712f64
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 140,
          "y": 480
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9f899e2d-01be-41bc-8125-3fec102a9652
      iscommand: false
      name: end
      type: title
      version: -1
    taskid: 9f899e2d-01be-41bc-8125-3fec102a9652
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 130,
          "y": 620
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1450,
        "width": 970,
        "x": -440,
        "y": -515
      }
    }
  }
