contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: GetAllAPIEndpointsV2 Contribution Pack
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 788b630f-b096-4d05-8aa7-706c1247481a
inputs: []
name: GetAllAPIEndpointsV2
outputs: []
quiet: true
sourceplaybookid: ec464f90-0055-4cc2-86aa-7bef0f50b45f
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e134959a-609b-45df-857a-9f5be6f5d0d9
      iscommand: false
      name: ""
      version: -1
    taskid: e134959a-609b-45df-857a-9f5be6f5d0d9
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 125
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9fbb39b2-1ee9-4dd5-8151-3c5a03a3ca7a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 9fbb39b2-1ee9-4dd5-8151-3c5a03a3ca7a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -200,
          "y": 960
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 2
    reputationcalc: 1
    scriptarguments:
      BrandName:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: ${modules.brand}
              operator: isEqualString
              right:
                value:
                  simple: Demisto REST API
            - left:
                iscontext: true
                value:
                  simple: ${modules.brand}
              operator: isEqualString
              right:
                value:
                  simple: Core REST API
          root: ${modules.brand}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e8cf5054-6411-4c87-848c-06b069f55ca2
      iscommand: false
      name: Get Automation API Endpoints
      script: 89bc4c87-dedf-435a-87b1-3f5c26e0348a
      type: regular
      version: -1
    taskid: e8cf5054-6411-4c87-848c-06b069f55ca2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 540
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 2
    reputationcalc: 1
    scriptarguments:
      BrandName:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: ${modules.brand}
              operator: isEqualString
              right:
                value:
                  simple: Demisto REST API
            - left:
                iscontext: true
                value:
                  simple: ${modules.brand}
              operator: isEqualString
              right:
                value:
                  simple: Core REST API
          root: ${modules.brand}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 604e5649-f711-4ba7-8ac9-2c22098a9a46
      iscommand: false
      name: Get All API Endpoints in Playbooks
      script: 7c3f7430-5014-4354-8ab7-02bac4ebfe8f
      type: regular
      version: -1
    taskid: 604e5649-f711-4ba7-8ac9-2c22098a9a46
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 700
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: modules.brand
          operator: containsGeneral
          right:
            value:
              simple: Core REST API
        - left:
            iscontext: true
            value:
              simple: modules.brand
          operator: containsGeneral
          right:
            value:
              simple: Demisto REST API
      - - left:
            iscontext: true
            value:
              simple: modules.state
          operator: isEqualString
          right:
            value:
              simple: active
      label: REST API Enabled
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      REST API Enabled:
      - "7"
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3a6d05b8-b473-486d-89f1-8bef8f2c62cd
      iscommand: false
      name: Check the Demisto Rest API Integration ?
      type: condition
      version: -1
    taskid: 3a6d05b8-b473-486d-89f1-8bef8f2c62cd
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 295
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 900,
        "width": 1020,
        "x": -200,
        "y": 125
      }
    }
  }
