contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 220c3de8-ab6f-495b-897b-1a2b63681181
inputs: []
name: Quiet mode MPB
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3e1af9a9-4c0c-4f89-8f9c-b7cb077a27ba
      iscommand: false
      name: ""
      version: -1
    taskid: 3e1af9a9-4c0c-4f89-8f9c-b7cb077a27ba
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Hello 1 MPB
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 0ca91ac8-9a5b-438b-8f0e-95c689f13eca
      iscommand: false
      name: Print 1
      script: Print
      type: regular
      version: -1
    taskid: 0ca91ac8-9a5b-438b-8f0e-95c689f13eca
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: cfa05317-dcb3-42c3-8ff8-3cb94bf31582
      iscommand: false
      name: Quiet mode SPB
      playbookId: 109a73cb-1720-4e2c-83b0-5463f2690fda
      type: playbook
      version: -1
    taskid: cfa05317-dcb3-42c3-8ff8-3cb94bf31582
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Hello 2 MPB
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: af88439c-5c4c-40e1-8a69-8e982bbe26e0
      iscommand: false
      name: Print 2
      script: Print
      type: regular
      version: -1
    taskid: af88439c-5c4c-40e1-8a69-8e982bbe26e0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 590,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
