contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 711aceec-a525-43ec-8639-7c07c021fc98
inputs: []
name: mainplaybooknew
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 033c9d6c-3a95-44a9-869d-b91f586e9a7d
      iscommand: false
      name: ""
      version: -1
    taskid: 033c9d6c-3a95-44a9-869d-b91f586e9a7d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    scriptarguments:
      SplunkResults:
        complex:
          root: ${SplunkData}
          transformers:
          - operator: StringifyArray
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 6b5155e4-d766-4084-880c-86bb8235fa56
      iscommand: false
      name: NewSubplaybook
      playbookId: 4b249c20-1349-44fa-84ab-03826bdc0404
      type: playbook
      version: -1
    taskid: 6b5155e4-d766-4084-880c-86bb8235fa56
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 240
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 285,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
