contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: aa489c4d-5850-481d-88c6-cf5873e09048
inputs: []
name: Schedulecommand
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4459554e-cb83-4728-8595-81554df06964
      iscommand: false
      name: ""
      version: -1
    taskid: 4459554e-cb83-4728-8595-81554df06964
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Retrieves the current date and time.
      id: 23b496b3-8955-4edd-842b-03b3b724dce3
      iscommand: false
      name: Get Time
      script: GetTime
      type: regular
      version: -1
    taskid: 23b496b3-8955-4edd-842b-03b3b724dce3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${TimeNow}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 330b3f43-620c-4113-81ed-afe006b24916
      iscommand: false
      name: Print time
      script: Print
      type: regular
      version: -1
    taskid: 330b3f43-620c-4113-81ed-afe006b24916
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      command:
        simple: Set key=Test value=test
      cron:
        simple: 5 * * * *
      times:
        simple: "1"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Schedule a command to run inside the war room at a future time
        (once or reoccurring)
      id: 0927e9f7-343d-499b-8627-6fc6a0ef22ac
      iscommand: false
      name: Schedule
      script: ScheduleCommand
      type: regular
      version: -1
    taskid: 0927e9f7-343d-499b-8627-6fc6a0ef22ac
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4c498371-9956-4e01-8790-72bb5a5ac818
      iscommand: false
      name: Manual Task to be closed
      type: regular
      version: -1
    taskid: 4c498371-9956-4e01-8790-72bb5a5ac818
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
