contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: fb4716be-86c0-48c4-8d2f-80c9c99952bb
inputs: []
name: Demo - Sub Playbook Output
outputs:
- contextPath: Data2
  type: unknown
- contextPath: IP.Address
  description: Bad IP address.
- contextPath: IP.Geo.Country
  description: Bad IP country.
- contextPath: DBotScore.Score
  type: unknown
- contextPath: DBotScore.Vendor
  description: The vendor used to calculate the score.
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 711ad11f-539e-4581-8590-44d196d942a2
      iscommand: false
      name: ""
      version: -1
    taskid: 711ad11f-539e-4581-8590-44d196d942a2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 460,
          "y": 50
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 2
    scriptarguments:
      ignore-outputs:
        simple: "false"
      ip:
        simple: 8.8.8.8
    separatecontext: false
    skipunavailable: false
    task:
      brand: VirusTotal (API v3)
      description: Checks the reputation of an IP address.
      id: 552f9829-5d29-48cc-8203-e2c7429a2117
      iscommand: true
      name: check IP reputation
      script: VirusTotal (API v3)|||ip
      type: regular
      version: -1
    taskid: 552f9829-5d29-48cc-8203-e2c7429a2117
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 190
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: Data2=
      value:
        simple: This is test
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 9f145517-4ef2-4a02-89d1-426f0fe73ffa
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 9f145517-4ef2-4a02-89d1-426f0fe73ffa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 430
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 475,
        "width": 380,
        "x": 460,
        "y": 50
      }
    }
  }
