contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 49b61214-2ec2-4998-849d-d7626e71841c
inputs: []
name: test2354
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 096efa83-9376-4115-823a-d192cc231596
      iscommand: false
      name: ""
      version: -1
    taskid: 096efa83-9376-4115-823a-d192cc231596
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    form:
      description: ${incident.name} yes
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: ${incident.id} ${incident.name} question 1
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: shortText
      sender: ""
      title: ${incident.id} hello
      totalanswers: 0
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: sample
      cc: null
      format: ""
      methods:
      - email
      subject:
        simple: test
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: false
        retriescount: 2
        retriesinterval: 360
      to:
        simple: shapatil@paloaltonetworks.com
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 76e5e9f4-c0d5-4d7d-8de3-2130d2ecd468
      iscommand: false
      name: Untitled Task
      type: collection
      version: -1
    taskid: 76e5e9f4-c0d5-4d7d-8de3-2130d2ecd468
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 50,
          "y": 220
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 265,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
