contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 6a571a9a-1ce1-4820-862a-e99aee1e3a1f
inputs: []
name: Get Instance list in Excel
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bd26dee4-cb41-40b3-854e-1a5541c6a6d4
      iscommand: false
      name: ""
      version: -1
    taskid: bd26dee4-cb41-40b3-854e-1a5541c6a6d4
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 820,
          "y": -40
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      instance_status:
        simple: both
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns integration instances configured in Cortex XSOAR. You can
        filter by instance status and/or brand name (vendor).
      id: 48e4c377-d95a-4e2b-825c-09175ed0cd7c
      iscommand: false
      name: Get Instance List
      script: GetInstances
      type: regular
      version: -1
    taskid: 48e4c377-d95a-4e2b-825c-09175ed0cd7c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 820,
          "y": 60
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      csvArray:
        simple: ${Modules.name}
      fileName:
        simple: instance list
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Export given array to csv file
      id: 97c2db7b-837f-4a7c-8a19-677721292861
      iscommand: false
      name: Untitled Task
      script: ExportToCSV
      type: regular
      version: -1
    taskid: 97c2db7b-837f-4a7c-8a19-677721292861
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 820,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 365,
        "width": 380,
        "x": 820,
        "y": -40
      }
    }
  }
