contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: fe7c95f7-7442-4bd0-84d2-64cb104508af
inputs: []
name: Cust_IRC_Securonix_Zscaler_ZIA_Proxy_Traffic_Master
outputs: []
sourceplaybookid: 9885d44c-cd1e-4b75-8082-e74048252aff
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 43d66c56-b364-4dd2-826e-e9a34053e18f
      iscommand: false
      name: ""
      version: -1
    taskid: 43d66c56-b364-4dd2-826e-e9a34053e18f
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ec77decc-af6a-4169-85d8-445b587bf408
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: ec77decc-af6a-4169-85d8-445b587bf408
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: c8b6b377-af12-4c53-851f-35755725c161
      iscommand: false
      name: Clear context
      script: DeleteContext
      type: regular
      version: -1
    taskid: c8b6b377-af12-4c53-851f-35755725c161
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      Zscaler_Action:
        complex:
          accessor: rawevent
          root: Securonix.ViolationData
          transformers:
          - args:
              from:
                value:
                  simple: cat=
            operator: substringFrom
          - args:
              to:
                value:
                  simple: ' '
            operator: substringTo
          - args:
              delimiter: {}
            operator: splitAndTrim
      dst_ip:
        complex:
          accessor: destinationaddress
          root: Securonix.ViolationData
          transformers:
          - operator: uniq
          - args:
              prefix:
                value:
                  simple: '"'
              suffix:
                value:
                  simple: '"'
            operator: concat
          - args:
              separator:
                value:
                  simple: ' OR '
            operator: join
      hostname:
        complex:
          accessor: devicehostname
          root: Securonix.ViolationData
          transformers:
          - operator: trim
      http_status_code:
        complex:
          accessor: eventoutcome
          root: Securonix.ViolationData
          transformers:
          - operator: trim
      src_ip:
        complex:
          accessor: sourceaddress
          root: Securonix.ViolationData
          transformers:
          - operator: uniq
          - args:
              prefix:
                value:
                  simple: '"'
              suffix:
                value:
                  simple: '"'
            operator: concat
          - args:
              separator:
                value:
                  simple: ' OR '
            operator: join
      url:
        complex:
          accessor: requesturl
          root: Securonix.ViolationData
          transformers:
          - args:
              delimiter: {}
            operator: splitAndTrim
      username:
        complex:
          accessor: lanid
          root: Securonix.ViolationData
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 26fe28d5-e316-406f-8c14-6140d82a7695
      iscommand: false
      name: Cust_IRC_Securonix_Zscaler ZIA Proxy Traffic - Subplaybook
      playbookId: e27c2273-6e3b-4ae4-89ad-b9e266a8bf85
      type: playbook
      version: -1
    taskid: 26fe28d5-e316-406f-8c14-6140d82a7695
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Process
                root: CrowdStrike
          operator: isEmpty
          right:
            value: {}
        - left:
            iscontext: true
            value:
              complex:
                root: Zscaler_Action
          operator: isEqualString
          right:
            value:
              simple: Blocked
      label: No Data/Blocked
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      No Data/Blocked:
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: 65b566ba-813d-433b-8b73-ee2b27209ab4
      iscommand: false
      name: Check if Crowdstrike has brought any results on Processes
      type: condition
      version: -1
    taskid: 65b566ba-813d-433b-8b73-ee2b27209ab4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This is a Securonix initializer playbook which identifies the violator
        type, gets the associated policy violations, associates MITRE indicators,
        sets default priority and severity and assigns an analyst to the incident
      id: 0323043b-b943-4e10-8395-617fdc7b589b
      iscommand: false
      name: Cust_IRC_Securonix_Initializer
      playbookId: 3217ac4e-38e5-4d81-8c38-faf7200efc22
      type: playbook
      version: -1
    taskid: 0323043b-b943-4e10-8395-617fdc7b589b
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 710
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        This is a generic playbook which is used across all other Securonix playbooks. It start the following timers:
        * INC Ack SLA Timer
        * INC Triage SLA Timer
        * QI Ack SLA Timer
        * QI Containment SLA Timer
        * QI Resolution SLA Timer
        * QI Closure SLA Timer
        * MTTD
        * TTAA
        * TTQ
      id: 7f5a6e49-0553-42e3-84bc-87b1c6a8e467
      iscommand: false
      name: Cust_IRC_Securonix_Generic_Start_SLAs
      playbookId: 825c0dae-5f1e-46fe-80e0-ac72996e8129
      type: playbook
      version: -1
    taskid: 7f5a6e49-0553-42e3-84bc-87b1c6a8e467
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This is a generic playbook which is used across all other playbooks(Securonix
        dependent). It assigns an analyst to the incident based on the shift roster
      id: 05388d72-3607-4358-8f4c-00765f8cbd8c
      iscommand: false
      name: Cust_IRC_Securonix_Generic_Assign_Owner
      playbookId: cf99b3fe-2026-4266-8a77-cf78dd8b70fc
      type: playbook
      version: -1
    taskid: 05388d72-3607-4358-8f4c-00765f8cbd8c
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        This is a generic playbook which can be used across all other Securonix playbooks where the requirement is:
        * Closing the incident on XSOAR
        * Sending an email to the end user/analyst
      id: f831513e-96c3-47c8-8bec-d73d744f06b5
      iscommand: false
      name: Cust_IRC_Securonix_Generic_SendMail_CloseIncident
      playbookName: Wipro_IRC_Securonix_Generic_SendMail_CloseIncident
      type: playbook
      version: -1
    taskid: f831513e-96c3-47c8-8bec-d73d744f06b5
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 160,
          "y": 1420
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      dateFormat:
        simple: ISO
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Retrieves the current date and time.
      id: 348cca6a-3d51-4f19-84fe-6514ae07d74f
      iscommand: false
      name: Gettime now
      script: GetTime
      type: regular
      version: -1
    taskid: 348cca6a-3d51-4f19-84fe-6514ae07d74f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1610,
        "width": 490,
        "x": 50,
        "y": 50
      }
    }
  }
