contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: e4ad1ced-7a67-4d00-820a-8e89effde4cc
inputs: []
name: Ask Task
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 641d1921-e43d-4d88-8b7d-f7045d358e7d
      iscommand: false
      name: ""
      version: -1
    taskid: 641d1921-e43d-4d88-8b7d-f7045d358e7d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 695,
          "y": 65
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
      - "2"
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: emailto
      value:
        simple: sramesh1@paloaltonetworks.com,srikrame@gmail.com,sramesh1@palolatonetworks.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Set a value in context under the key you entered.
      id: 3dfb95c0-5801-4f94-8299-20dfb8ad868d
      iscommand: false
      name: Set
      script: Set
      type: regular
      version: -1
    taskid: 3dfb95c0-5801-4f94-8299-20dfb8ad868d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 225
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: test
                    operator: isEqualString
                    right:
                      value:
                        simple: E1
                  - left:
                      iscontext: true
                      value:
                        simple: test
                    operator: isEqualString
                    right:
                      value:
                        simple: E2
                  - left:
                      iscontext: true
                      value:
                        simple: test
                    operator: isEqualString
                    right:
                      value:
                        simple: TP
                root: test
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Indicates whether a given value is a member of given array
      id: 69994287-287a-4e4b-8839-f209a8663720
      iscommand: false
      name: Condition
      type: condition
      version: -1
    taskid: 69994287-287a-4e4b-8839-f209a8663720
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 400
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 27d423e0-4cfb-45e2-8c73-eab8506ae708
      iscommand: false
      name: "Yes"
      type: regular
      version: -1
    taskid: 27d423e0-4cfb-45e2-8c73-eab8506ae708
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 575
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5e529c3c-661a-42e6-889c-fed46787bcf8
      iscommand: false
      name: "No"
      type: regular
      version: -1
    taskid: 5e529c3c-661a-42e6-889c-fed46787bcf8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 575
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      body:
        simple: test
      subject:
        simple: test
      to:
        simple: ${emailto}
    separatecontext: false
    skipunavailable: false
    task:
      brand: EWSO365
      description: Sends an email.
      id: 7f2d583d-1e0f-4780-8cad-3a64d09bde05
      iscommand: true
      name: sendmail
      script: EWSO365|||send-mail
      type: regular
      version: -1
    taskid: 7f2d583d-1e0f-4780-8cad-3a64d09bde05
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 575
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: emailto
      value:
        complex:
          root: emailto
          transformers:
          - args:
              delimiter:
                value:
                  simple: ','
            operator: split
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: e2366f7a-bf4d-4784-8b79-acc9322d0da6
      iscommand: false
      name: Make an array
      script: Set
      type: regular
      version: -1
    taskid: e2366f7a-bf4d-4784-8b79-acc9322d0da6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 400
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: {}
      cc: null
      format: ""
      methods:
      - email
      replyOptions:
      - "Yes"
      - "No"
      subject:
        simple: Test
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
        simple: sramesh1@paloaltonetworks.com
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e837ca34-2109-40ca-8548-e791258817e3
      iscommand: false
      name: Ask Task
      type: condition
      version: -1
    taskid: e837ca34-2109-40ca-8548-e791258817e3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 400
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 605,
        "width": 1455,
        "x": 50,
        "y": 65
      }
    }
  }
