contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.0.0
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: |-
  Detonate a webpage or remote file using the WildFire integration. This playbook returns relevant reports to the War Room and file reputations to the context data.
  The detonation supports the following file types:
  APK, JAR, DOC, DOCX, RTF, OOXLS, XLSX, PPT, PPTX, XML, PE32, PDF, DMG, PKG, RAR, 7Z, JS.
id: b8bb973b-1f70-4984-812f-c60dc561346a
inputs:
- description: URL of the webpage or file url to detonate. The URL is taken from the
    context.
  key: URL
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Data
      root: URL
- description: Duration for executing the polling (in minutes).
  key: Interval
  playbookInputQuery: null
  required: false
  value:
    simple: "1"
- description: The duration after which to stop polling and to resume the playbook
    (in minutes).
  key: Timeout
  playbookInputQuery: null
  required: false
  value:
    simple: "60"
- description: The resource type to download. Default is PDF. XML is also possible.
  key: ReportFileType
  playbookInputQuery: null
  required: false
  value: {}
name: Detonate URL - WildFire v2.1_copy
outputs:
- contextPath: DBotScore
  description: The DBotScore object
  type: unknown
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: File.Size
  description: File size
  type: number
- contextPath: File.MD5
  description: MD5 hash
  type: string
- contextPath: File.SHA1
  description: SHA1 hash
  type: string
- contextPath: File.Type
  description: File type e.g. "PE"
  type: string
- contextPath: File.SHA256
  description: SHA256 hash
  type: string
- contextPath: File.EntryID
  description: The Entry ID of the sample
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that determined that the file is malicious.
  type: string
- contextPath: File.Name
  description: Filename
  type: string
- contextPath: File.Malicious.Description
  description: For malicious files, the reason the vendor determined that the file
    is malicious.
  type: string
- contextPath: DBotScore.Indicator
  description: The indicator we tested.
  type: string
- contextPath: DBotScore.Type
  description: The type of indicator.
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score.
  type: string
- contextPath: IP.Address
  description: IPs relevant to the sample.
  type: string
- contextPath: File
  description: The File object.
  type: unknown
- contextPath: InfoFile
  description: The report file object.
  type: unknown
- contextPath: InfoFile.EntryID
  description: The EntryID of the report file.
  type: string
- contextPath: InfoFile.Extension
  description: The extension of the report file.
  type: string
- contextPath: InfoFile.Name
  description: The name of the report file.
  type: string
- contextPath: InfoFile.Info
  description: The info of the report file.
  type: string
- contextPath: InfoFile.Size
  description: The size of the report file.
  type: number
- contextPath: InfoFile.Type
  description: The type of the report file.
  type: string
- contextPath: File.Malicious
  description: The malicious object.
  type: unknown
- contextPath: WildFire.Report
  description: The submission object.
  type: unknown
- contextPath: WildFire.Report.MD5
  description: MD5 of the submission.
  type: string
- contextPath: WildFire.Report.SHA256
  description: SHA256 of the submission.
  type: string
- contextPath: WildFire.Report.FileType
  description: The type of the submission.
  type: string
- contextPath: WildFire.Report.Status
  description: The status of the submission.
  type: string
- contextPath: WildFire.Report.Size
  description: The size of the submission.
  type: number
- contextPath: WildFire.Report.URL
  description: URL of the submission.
  type: string
- contextPath: WildFire.Report.detection_reasons
  description: The detection reasons object.
  type: unknown
- contextPath: WildFire.Report.detection_reasons.description
  description: Reason for the detection verdict.
  type: string
- contextPath: WildFire.Report.detection_reasons.name
  description: Name of the detection.
  type: string
- contextPath: WildFire.Report.detection_reasons.type
  description: Type of the detection.
  type: string
- contextPath: WildFire.Report.detection_reasons.verdict
  description: Verdict of the detection.
  type: string
- contextPath: WildFire.Report.detection_reasons.artifacts
  description: Artifacts for the detection reasons.
  type: string
- contextPath: WildFire.Report.iocs
  description: Associated IOCs.
  type: string
sourceplaybookid: Detonate URL - WildFire v2.1
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c36af7f0-61b0-4e84-8aa8-88d8036245ca
      iscommand: false
      name: ""
      version: -1
    taskid: c36af7f0-61b0-4e84-8aa8-88d8036245ca
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      upload:
        complex:
          root: inputs.URL
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Uploads the URL of a remote file to WildFire for analysis.
      id: e416ba05-2d66-4671-888b-8034680e8796
      iscommand: true
      name: WildFire Upload File URL
      script: '|||wildfire-upload-file-url'
      type: regular
      version: -1
    taskid: e416ba05-2d66-4671-888b-8034680e8796
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 490,
          "y": 545
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        complex:
          accessor: Report.URL
          root: WildFire
      Interval:
        complex:
          root: inputs.Interval
      PollingCommandArgName:
        simple: url
      PollingCommandName:
        simple: wildfire-report
      Timeout:
        complex:
          root: inputs.Timeout
      dt:
        simple: WildFire.Report(val.Status != 'Success').URL
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: d3f1053f-bf63-454e-8d38-f05d94d99556
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: d3f1053f-bf63-454e-8d38-f05d94d99556
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1770
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 60484d20-fc2d-499b-8778-3962368dfe5b
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 60484d20-fc2d-499b-8778-3962368dfe5b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.URL
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Look for file URLs to detonate
      id: 75c1c4a7-1f26-4785-89eb-e1a3b085b364
      iscommand: false
      name: Is there a URL to detonate?
      type: condition
      version: -1
    taskid: 75c1c4a7-1f26-4785-89eb-e1a3b085b364
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 370
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: WildFire-v2
                root: modules
                transformers:
                - args:
                    field:
                      value:
                        simple: state
                  operator: getField
          operator: isEqualString
          right:
            value:
              simple: active
      label: "yes"
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if integration instance is enabled.
      id: b340e210-9895-45fe-82bc-3ee9a6d6fc39
      iscommand: false
      name: Is WildFire-v2 enabled?
      type: condition
      version: -1
    taskid: b340e210-9895-45fe-82bc-3ee9a6d6fc39
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      url:
        complex:
          accessor: Report.URL
          root: WildFire
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieves results for a file hash using WildFire.
      id: 784929aa-945f-40a8-8eaa-c88dae629e7c
      iscommand: true
      name: WildFire Get Report
      script: '|||wildfire-report'
      type: regular
      version: -1
    taskid: 784929aa-945f-40a8-8eaa-c88dae629e7c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 602.5,
          "y": 1945
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      upload:
        complex:
          root: inputs.URL
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Uploads a URL of a webpage to WildFire for analysis.
      id: cfa99438-c73d-4832-8e7a-76e13983ffd9
      iscommand: true
      name: WildFire Upload URL
      script: '|||wildfire-upload-url'
      type: regular
      version: -1
    taskid: cfa99438-c73d-4832-8e7a-76e13983ffd9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 1245
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.URL
                transformers:
                - operator: count
          operator: isEqualNumber
          right:
            iscontext: true
            value:
              complex:
                accessor: URL
                root: WildFire.Report
                transformers:
                - operator: count
      label: "yes"
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Was the file successfully submitted using the URL provided.
      id: d01bafd2-adb0-4dab-82d4-7423360ab62d
      iscommand: false
      name: Was there an unsuccessful file url submission?
      type: condition
      version: -1
    taskid: d01bafd2-adb0-4dab-82d4-7423360ab62d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 490,
          "y": 1070
        }
      }
  "12":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Report.URL
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: WildFire.Report.Status
                    operator: isEqualString
                    right:
                      value:
                        simple: Pending
                root: WildFire
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 79ee7f6d-3b41-4751-8f2d-498963463e23
      iscommand: false
      name: Was the file uploaded successfully and is a report pending?
      type: condition
      version: -1
    taskid: 79ee7f6d-3b41-4751-8f2d-498963463e23
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 275,
          "y": 1595
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        complex:
          accessor: Report.SHA256
          root: WildFire
      Interval:
        complex:
          root: inputs.Interval
      PollingCommandArgName:
        simple: sha256
      PollingCommandName:
        simple: wildfire-report
      Timeout:
        complex:
          root: inputs.Timeout
      dt:
        simple: WildFire.Report(val.Status != 'Success').SHA256
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 9096b3eb-3e33-40d6-877d-c14a4b90c81c
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 9096b3eb-3e33-40d6-877d-c14a4b90c81c
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 817.5,
          "y": 1770
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      url:
        complex:
          accessor: Report.URL
          root: WildFire
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if a report already exists for the file or URL submitted.
      id: 8b3e228e-a8ed-49f5-880a-3f9935680418
      iscommand: true
      name: WildFire Get Report - Check If a Report already exists
      script: '|||wildfire-report'
      type: regular
      version: -1
    taskid: 8b3e228e-a8ed-49f5-880a-3f9935680418
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 1420
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      url:
        complex:
          accessor: Report.URL
          root: WildFire
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if a report already exists for the file or URL submitted.
      id: 78a903df-da41-42d6-8c13-947499a01942
      iscommand: true
      name: WildFire Get Report - Check If a Report already exists
      script: '|||wildfire-report'
      type: regular
      version: -1
    taskid: 78a903df-da41-42d6-8c13-947499a01942
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "17":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: URL
                root: WildFire.Report
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "11"
      "yes":
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Was the file successfully submitted using the URL provided.
      id: 5cd7721e-7625-4193-8246-3e7d67a3a817
      iscommand: false
      name: Was there a successful file url submission?
      type: condition
      version: -1
    taskid: 5cd7721e-7625-4193-8246-3e7d67a3a817
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 490,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "7_5_#default#": 0.7
    },
    "paper": {
      "dimensions": {
        "height": 2135,
        "width": 1147.5,
        "x": 50,
        "y": 50
      }
    }
  }
