contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: This is the playbook which runs on unclassified Securonix incidents
id: 259d6899-ee15-48a0-8f49-55f656173b0d
inputs: []
name: Cust_IRC_Securonix_UnClassified
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a551abbc-10af-46fa-8543-dcfb47534010
      iscommand: false
      name: ""
      version: -1
    taskid: a551abbc-10af-46fa-8543-dcfb47534010
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This is a Securonix initializer playbook which identifies the violator
        type, gets the associated policy violations, associates MITRE indicators,
        sets default priority and severity and assigns an analyst to the incident
      id: e18e3d1b-5dd3-402f-8700-155cbd6b3284
      iscommand: false
      name: Cust_IRC_Securonix_Initializer
      playbookId: 3217ac4e-38e5-4d81-8c38-faf7200efc22
      type: playbook
      version: -1
    taskid: e18e3d1b-5dd3-402f-8700-155cbd6b3284
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2b4efa89-47b3-46c8-8b62-4e155751fe73
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 2b4efa89-47b3-46c8-8b62-4e155751fe73
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        This is a generic playbook which can be used across all other Securonix playbooks where the requirement is:
        * Closing the incident on XSOAR
        * Sending an email to the end user/analyst
      id: 19e3c4c0-7cea-4740-8360-b924f6c89152
      iscommand: false
      name: Cust_IRC_Securonix_Generic_SendMail_CloseIncident
      playbookName: Wipro_IRC_Securonix_Generic_SendMail_CloseIncident
      type: playbook
      version: -1
    taskid: 19e3c4c0-7cea-4740-8360-b924f6c89152
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: name
                root: incident
                transformers:
                - operator: toUpperCase
          operator: containsString
          right:
            value:
              simple: VECTRA
      label: Vectra detection
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      Vectra detection:
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c28f1eb0-c998-49ea-8e84-9c7e17119154
      iscommand: false
      name: Check if Vectra detection
      type: condition
      version: -1
    taskid: c28f1eb0-c998-49ea-8e84-9c7e17119154
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
