contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 9b4a2443-d95c-4b19-8a0a-1cb25d399f07
inputs:
- description: ""
  key: emailnewrecipients
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: emailnewsubject
  playbookInputQuery: null
  required: false
  value: {}
name: email send
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d5c54c87-fd39-4fad-8fe5-6e8c0514eaf5
      iscommand: false
      name: ""
      version: -1
    taskid: d5c54c87-fd39-4fad-8fe5-6e8c0514eaf5
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 20,
          "y": -80
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      emailnewbody:
        simple: |
          <!DOCTYPE html>
          <html>

          <table>
          <thead>
          <tr>
          <th>ID</th>
          <th>CSPID</th>
          <th>Email</th>
          <th>SponserID</th>
          <th>SEmail</th>
          </tr>
          </thead>

          <tbody>
          <tr>
          <td>2</td>
          <td>emp456</td>
          <td>abc@test.com</td>
          <td>456</td>
          <td>sua@paloaltonetworks.com</td>
          </tr>

          <tr>
          <td>1</td>
          <td>emp1011</td>
          <td>ghi@test.com</td>
          <td>456</td>
          <td>sua@paloaltonetworks.com</td>
          </tr>
          </tbody>
          </table>

          </body>
          </html>
      emailnewrecipients:
        simple: ${inputs.emailnewrecipients}
      emailnewsubject:
        simple: ${inputs.emailnewsubject}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: d753b727-7e89-4bb1-8f11-2abca0da5ab3
      iscommand: true
      name: Set Incident Fields
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: d753b727-7e89-4bb1-8f11-2abca0da5ab3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1270,
          "y": 100
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: errorPath
    evidencedata:
      customfields: {}
      description:
        simple: User Email Communication
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "10"
      '#none#':
      - "7"
    note: false
    quietmode: 2
    scriptarguments:
      mail_sender_instance:
        simple: Gmail Single User_instance_1
      new_thread:
        simple: "true"
      retry-count:
        simple: "3"
      retry-interval:
        simple: "300"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Send email reply
        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: dd159752-e79d-4f16-8b66-5c9d11794fdf
      iscommand: false
      name: Send Email
      script: SendEmailReply
      type: regular
      version: -1
    taskid: dd159752-e79d-4f16-8b66-5c9d11794fdf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 520,
          "y": 260
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      body:
        simple: "Hi \n\nThis is test email"
      subject:
        simple: ${incident.name}  - ${incident.tags}
      to:
        simple: sua@paloaltonetworks.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: Gmail Single User
      description: Sends an email using Gmail.
      id: e7c95cfd-c517-4d9f-8948-450f8382c3ac
      iscommand: true
      name: Send Email using Using EmailAskUser
      script: Gmail Single User|||send-mail
      tags:
      - userreply
      type: regular
      version: -1
    taskid: e7c95cfd-c517-4d9f-8948-450f8382c3ac
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 10,
          "y": 60
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8c40ed7b-e11b-422b-864c-dca7c8c905c3
      iscommand: false
      name: Wiat time
      tags:
      - userreply
      type: regular
      version: -1
    taskid: 8c40ed7b-e11b-422b-864c-dca7c8c905c3
    timertriggers:
    - action: start
      fieldname: demoslatimer
    type: regular
    view: |-
      {
        "position": {
          "x": 10,
          "y": 220
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: "Yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 560a0184-098e-4405-81ad-a86ed266a8f8
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 560a0184-098e-4405-81ad-a86ed266a8f8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 10,
          "y": 385
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      sla:
        simple: "10"
      slaField:
        simple: demoslatimer
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 03441187-53d8-426f-848e-f5c3e714daef
      iscommand: true
      name: Set SLA
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 03441187-53d8-426f-848e-f5c3e714daef
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 750
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0a904fa9-e33c-4d17-843e-fb7c5a9b167c
      iscommand: false
      name: wait for user response
      tags:
      - userreply
      type: regular
      version: -1
    taskid: 0a904fa9-e33c-4d17-843e-fb7c5a9b167c
    timertriggers:
    - action: start
      fieldname: demoslatimer
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 925
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: true
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: emailtestlock - ${incident.id}
      timeout:
        simple: "900"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Demisto Lock
      description: Gets a specific lock. If the lock doesn't exist, it creates one.
        If the lock is already in use, the command waits until the lock is released
        or until timeout is reached. If timeout is reached and the lock hasn't been
        released, the command fails to get the lock.
      id: 4a84fd63-7a2a-4d59-819f-8e2639ddb1e4
      iscommand: true
      name: Acquire Lock
      script: Demisto Lock|||demisto-lock-get
      type: regular
      version: -1
    taskid: 4a84fd63-7a2a-4d59-819f-8e2639ddb1e4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1280,
          "y": 280
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: true
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: emailtestlock - ${incident.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Demisto Lock
      description: Release a lock
      id: 3d867ce0-54ff-420b-8ec1-8cf1a694335e
      iscommand: true
      name: Release Lock
      script: Demisto Lock|||demisto-lock-release
      type: regular
      version: -1
    taskid: 3d867ce0-54ff-420b-8ec1-8cf1a694335e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1100
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2f59dbc9-f0cb-4ced-8c96-4d3f042f2a18
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 2f59dbc9-f0cb-4ced-8c96-4d3f042f2a18
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1290
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1435,
        "width": 1650,
        "x": 10,
        "y": -80
      }
    }
  }
