contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 15e2b193-60d3-4a88-8a3c-1d1581dfca7e
inputs: []
name: Test - Upload attachment to an Incident
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ef09afce-d5c5-4bd2-8a00-8770278418a7
      iscommand: false
      name: ""
      version: -1
    taskid: ef09afce-d5c5-4bd2-8a00-8770278418a7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      body:
        simple: '{"field": "emailnewattachment"}'
      entryID:
        complex:
          accessor: EntryID}
          root: ${File
      retry-count:
        simple: "10"
      retry-interval:
        simple: "10"
      uri:
        simple: /incident/upload/8
    separatecontext: false
    skipunavailable: false
    task:
      brand: Core REST API
      description: Send HTTP Multipart request to upload files to Demisto server.
      id: 7c0172c1-254c-45b1-837f-db3a0465f528
      iscommand: true
      name: Upload the IOC attachment to BU Incident
      script: Core REST API|||demisto-api-multipart
      type: regular
      version: -1
    taskid: 7c0172c1-254c-45b1-837f-db3a0465f528
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 220
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 265,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
