contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: f1ef2508-0212-40bf-8d12-032ecfdd491c
inputs:
- description: ""
  key: incidentID
  playbookInputQuery: null
  required: false
  value: {}
name: ReOpenBulkInvestigations
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7ae0680f-683f-476d-8e66-30364ebc983f
      iscommand: false
      name: ""
      version: -1
    taskid: 7ae0680f-683f-476d-8e66-30364ebc983f
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -130
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 2
    scriptarguments:
      body:
        simple: '{"id":"${IncidentData.id}","version":${IncidentData.version}}'
      uri:
        simple: /investigation/${IncidentData.id}/reopen
    separatecontext: false
    skipunavailable: false
    task:
      brand: Core REST API
      description: send HTTP POST request
      id: 56cc407a-4061-4c06-874c-247dc64a4341
      iscommand: true
      name: Re-Open Incident
      script: Core REST API|||demisto-api-post
      type: regular
      version: -1
    taskid: 56cc407a-4061-4c06-874c-247dc64a4341
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 360
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 2
    scriptarguments:
      body:
        simple: '{"userFilter":false,"filter":{"page":0,"size":50,"query":"id:${inputs.incidentID}","sort":[{"field":"id","asc":false}]}}'
      extend-context:
        simple: IncidentData.id=.response.data.id::IncidentData.version=.response.data.version
      uri:
        simple: /incidents/search
    separatecontext: false
    skipunavailable: false
    task:
      brand: Core REST API
      description: send HTTP POST request
      id: 9cdf9221-b0cd-43e6-8ffb-6145d9b16768
      iscommand: true
      name: SearchIncidents
      script: Core REST API|||demisto-api-post
      type: regular
      version: -1
    taskid: 9cdf9221-b0cd-43e6-8ffb-6145d9b16768
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: IncidentData
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 55260d7c-ef91-4633-89d9-e38428b5d800
      iscommand: false
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: 55260d7c-ef91-4633-89d9-e38428b5d800
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 560
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 785,
        "width": 380,
        "x": 450,
        "y": -130
      }
    }
  }
