contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: df6bbbfd-05c8-4d53-8bed-d7871b3af0f8
inputs: []
name: Case - Create Inc and Upload Attachment
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 35a0df49-8160-4fab-8792-bb0523331e0b
      iscommand: false
      name: ""
      version: -1
    taskid: 35a0df49-8160-4fab-8792-bb0523331e0b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: Test Incident 13
      severity:
        simple: "1"
      type:
        simple: Manual
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.create.inc
      id: 7b8f90ba-fa68-48cd-8dec-946a5fc15e55
      iscommand: true
      name: Create BU New Incident
      script: Builtin|||createNewIncident
      type: regular
      version: -1
    taskid: 7b8f90ba-fa68-48cd-8dec-946a5fc15e55
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 2
    scriptarguments:
      body:
        simple: '{''field'': ''attachment''}'
      entryID:
        complex:
          accessor: EntryID}
          root: ${File
      uri:
        simple: /incident/upload/${CreatedIncidentID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Core REST API
      description: Send HTTP Multipart request to upload files to Demisto server.
      id: 14f0509c-6006-4d02-8da3-40520079cbfa
      iscommand: true
      name: Upload the IOC attachment to BU Incident
      script: Core REST API|||demisto-api-multipart
      type: regular
      version: -1
    taskid: 14f0509c-6006-4d02-8da3-40520079cbfa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: File.Name
          operator: isEqualString
          right:
            value:
              simple: SplunkResults file
      label: "yes"
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5be111ac-be03-4242-8836-89f54e0f3afd
      iscommand: false
      name: Check the Splunk results file exists or not
      type: condition
      version: -1
    taskid: 5be111ac-be03-4242-8836-89f54e0f3afd
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 2
    scriptarguments:
      body:
        simple: '{''field'': ''attachment''}'
      entryID:
        complex:
          accessor: EntryID}
          root: ${File
      uri:
        simple: /incident/upload/${CreatedIncidentID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Core REST API
      description: Send HTTP Multipart request to upload files to Demisto server.
      id: d91e2801-f58c-4fb5-8644-71c54ddc77aa
      iscommand: true
      name: Upload the Splunk Search Results file attachment to  BU Incident
      script: Core REST API|||demisto-api-multipart
      type: regular
      version: -1
    taskid: d91e2801-f58c-4fb5-8644-71c54ddc77aa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.linkIncidents
      id: a0965a5e-efbf-4470-8268-70f3b5b275cd
      iscommand: true
      name: 'Link Incident '
      script: Builtin|||linkIncidents
      type: regular
      version: -1
    taskid: a0965a5e-efbf-4470-8268-70f3b5b275cd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: CreatedIncidentID
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 433c1f56-d944-45a1-846b-075cbf61eda8
      iscommand: false
      name: Delete context key CreatedIncidentID
      script: DeleteContext
      type: regular
      version: -1
    taskid: 433c1f56-d944-45a1-846b-075cbf61eda8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7607b94c-c61b-47ef-8a19-124fd3878ffd
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 7607b94c-c61b-47ef-8a19-124fd3878ffd
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1260,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
