contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 6c31e87b-51cc-4d73-87f9-6eec09ef9be6
inputs:
- description: ""
  key: Username
  playbookInputQuery: null
  required: false
  value: {}
name: Demo Sub Playbook
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d23b5509-c52f-4961-8c07-cf077f07c527
      iscommand: false
      name: ""
      version: -1
    taskid: d23b5509-c52f-4961-8c07-cf077f07c527
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      value:
        simple: ${inputs.Username}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: e544fd00-3e91-46c3-83b7-815c675d5c5a
      iscommand: false
      name: Print task
      script: Print
      type: regular
      version: -1
    taskid: e544fd00-3e91-46c3-83b7-815c675d5c5a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": 220
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Pretty-print the contents of the playbook context
      id: 8f02cc26-6ed2-4cc5-8e6f-e93329c346d0
      iscommand: false
      name: Print
      script: PrintContext
      type: regular
      version: -1
    taskid: 8f02cc26-6ed2-4cc5-8e6f-e93329c346d0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 570,
          "y": 350
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    scriptarguments:
      Hostname:
        simple: ${Hostname.Host}
      Users:
        simple: ${Usersnames.users}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 529fb728-5dc5-4b9b-8a89-426609e62732
      iscommand: false
      name: Demo Check List
      playbookId: 169e7e6a-9d54-467c-84ea-a705c1212888
      type: playbook
      version: -1
    taskid: 529fb728-5dc5-4b9b-8a89-426609e62732
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 600
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 645,
        "width": 910,
        "x": 40,
        "y": 50
      }
    }
  }
