contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 0b38269c-1a8e-403b-88aa-65e9fcd19ef9
inputs:
- description: ""
  key: max_tries
  playbookInputQuery: null
  required: false
  value:
    simple: "3"
- description: ""
  key: taskid
  playbookInputQuery: null
  required: false
  value:
    simple: "1"
name: Test-SubplaybookCounter
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 19626fcc-fb8e-4f47-8edc-fb6ffb83f0b0
      iscommand: false
      name: ""
      version: -1
    taskid: 19626fcc-fb8e-4f47-8edc-fb6ffb83f0b0
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 60
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: test.${inputs.taskid}.retrycount
      value:
        complex:
          root: ${test}
          transformers:
          - args:
              dt:
                value:
                  simple: ${inputs=val.taskid+'.retrycount'}
            operator: DT
          - args:
              applyIfEmpty: {}
              defaultValue:
                value:
                  simple: "0"
            operator: SetIfEmpty
          - args:
              by:
                value:
                  simple: "1"
            operator: addition
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 0ec58b6f-86f8-4c9c-8bc4-992b045f5797
      iscommand: false
      name: Set
      script: Set
      type: regular
      version: -1
    taskid: 0ec58b6f-86f8-4c9c-8bc4-992b045f5797
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1080,
          "y": 390
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${test.1.retrycount}
          operator: isEqualNumber
          right:
            value:
              simple: "6"
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e3b949ed-f2e5-4d3a-88b8-3dbcd1f6e94d
      iscommand: false
      name: check
      type: condition
      version: -1
    taskid: e3b949ed-f2e5-4d3a-88b8-3dbcd1f6e94d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: test.${inputs.taskid}.stop
      value:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 80336118-5f39-4858-8716-38d5eed8d770
      iscommand: false
      name: Set
      script: Set
      type: regular
      version: -1
    taskid: 80336118-5f39-4858-8716-38d5eed8d770
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 590
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bae923d0-627e-4645-8364-2de62272cc92
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: bae923d0-627e-4645-8364-2de62272cc92
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -130,
          "y": 780
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: test.${inputs.taskid}.retrycount
      value:
        complex:
          root: ${test}
          transformers:
          - args:
              field:
                iscontext: true
                value:
                  simple: ${inputs.taskid}
            operator: getField
          - args:
              field:
                value:
                  simple: retrycount
            operator: getField
          - args:
              applyIfEmpty: {}
              defaultValue:
                value:
                  simple: "0"
            operator: SetIfEmpty
          - args:
              by:
                value:
                  simple: "1"
            operator: addition
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 900e740c-6d14-40ea-8d98-90c00d2c414a
      iscommand: false
      name: Set
      script: Set
      type: regular
      version: -1
    taskid: 900e740c-6d14-40ea-8d98-90c00d2c414a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 785,
        "width": 1590,
        "x": -130,
        "y": 60
      }
    }
  }
