contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: c4d5300c-2a90-4526-877f-a610a581457a
inputs: []
name: ip_enrich_playbook
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b63fdc00-4e0b-4e20-840c-c4a2031c5462
      iscommand: false
      name: ""
      version: -1
    taskid: b63fdc00-4e0b-4e20-840c-c4a2031c5462
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Upload file
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: attachments
      sender: ""
      title: Upload file here
      totalanswers: 0
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: null
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: false
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3af899ea-4b2e-4777-86b1-b04427355691
      iscommand: false
      name: Attach file
      type: collection
      version: -1
    taskid: 3af899ea-4b2e-4777-86b1-b04427355691
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      entryID:
        simple: '${.=(val.File instanceof Array ? val.File[val.File.length-1].EntryID
          : val.File.EntryID)}'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Load the contents of a file into context.
      id: 9f99782d-dd48-41c9-8dad-4cd2b8f76482
      iscommand: false
      name: Read file
      script: ReadFile
      type: regular
      version: -1
    taskid: 9f99782d-dd48-41c9-8dad-4cd2b8f76482
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      text:
        simple: ${FileData}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.extract.indicators
      id: 62e11b0c-e570-4809-811e-b68edd49d646
      iscommand: true
      name: Extract indicators
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: 62e11b0c-e570-4809-811e-b68edd49d646
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      ip:
        simple: ${ExtractedIndicators.IP}
    separatecontext: false
    skipunavailable: false
    task:
      brand: VirusTotal (API v3)
      description: Checks the reputation of an IP address.
      id: 795267c6-efb5-4da3-8544-95089eabbaa4
      iscommand: true
      name: Enrich IPs
      script: VirusTotal (API v3)|||ip
      type: regular
      version: -1
    taskid: 795267c6-efb5-4da3-8544-95089eabbaa4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      csvArray:
        simple: ${VirusTotal.IP}
      fileName:
        simple: IP_results_file.csv
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Export given array to csv file
      id: 79e8ae39-9371-4dc4-8deb-14244ce85a36
      iscommand: false
      name: Export to CSV file
      script: ExportToCSV
      type: regular
      version: -1
    taskid: 79e8ae39-9371-4dc4-8deb-14244ce85a36
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 940,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
