contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 645f49bb-d5dd-416a-8b15-d63104f7c4b3
inputs: []
name: Pause Multiple Investigation
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fde29c78-67ec-441a-870e-43261a566d95
      iscommand: false
      name: ""
      version: -1
    taskid: fde29c78-67ec-441a-870e-43261a566d95
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 60
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    scriptarguments:
      IncidentID:
        simple: "11"
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 564714f7-efce-4ca2-8cb1-a8ba358988b9
      iscommand: false
      name: Pause Playbook Execution
      playbookId: 1e5adb84-1488-46a7-8bf5-3c5cd87b2b33
      type: playbook
      version: -1
    taskid: 564714f7-efce-4ca2-8cb1-a8ba358988b9
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 265,
        "width": 380,
        "x": 450,
        "y": 60
      }
    }
  }
