contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 03ff78c5-85ee-440c-8b27-3a6dafae869f
inputs: []
name: testdata
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 409a7901-e672-4f2c-8500-248230a49164
      iscommand: false
      name: ""
      version: -1
    taskid: 409a7901-e672-4f2c-8500-248230a49164
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${qradar.inc}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: e94f6191-48e0-421d-8885-7e5e56a544b8
      iscommand: false
      name: print
      script: Print
      type: regular
      version: -1
    taskid: e94f6191-48e0-421d-8885-7e5e56a544b8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 690,
          "y": 200
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: sss
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 1fc77d6e-1b0f-4927-8d10-72fedf23136f
      iscommand: false
      name: Untitled Task
      script: Print
      type: regular
      version: -1
    taskid: 1fc77d6e-1b0f-4927-8d10-72fedf23136f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 690,
          "y": 350
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      builtincondition:
      - - left:
            iscontext: true
            value:
              simple: Data.IP
          operator: isEqualString
          right:
            value:
              simple: 192.168.1.2
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 18d77889-12dd-4b7d-891d-4a550f8b8fec
      iscommand: false
      name: testsubplybookloop
      playbookId: 1d00dcf8-c830-40b8-88d9-0c124cb13e90
      type: playbook
      version: -1
    taskid: 18d77889-12dd-4b7d-891d-4a550f8b8fec
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 560
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    scriptarguments:
      Keys:
        simple: ${Key}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a88d076e-4876-45b2-8759-b847e0f72eb7
      iscommand: false
      name: test_abc
      playbookId: 75a87d34-8dbf-45de-8f96-69380e28e7d0
      type: playbook
      version: -1
    taskid: a88d076e-4876-45b2-8759-b847e0f72eb7
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 60,
          "y": 360
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Output_data
      value:
        simple: "[{\n\"rawType\":\"Unclassified\"},\n{\"autime\":168798989500},\n{\"changeStatus\":
          \"updated\"}\n] "
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: f549558d-adcf-452b-890c-2538bc2bc8ce
      iscommand: false
      name: Set Data
      script: Set
      type: regular
      version: -1
    taskid: f549558d-adcf-452b-890c-2538bc2bc8ce
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 180
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 605,
        "width": 1020,
        "x": 50,
        "y": 50
      }
    }
  }
