contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: e4de8b26-806b-4eba-8cc0-39c2d4ccde6e
inputs: []
name: sample-1
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 164bb8d4-01a5-46cd-8410-b6fb1390386c
      iscommand: false
      name: ""
      version: -1
    taskid: 164bb8d4-01a5-46cd-8410-b6fb1390386c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": -20
        }
      }
  "1":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Choose your manager
        options: []
        optionsarg:
        - complex:
            accessor: shiftB
            root: lists
            transformers:
            - args:
                delimiter:
                  value:
                    simple: ','
              operator: split
        - {}
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: singleSelect
      sender: ""
      title: select managers
      totalanswers: 0
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: dsf
      cc: null
      format: ""
      methods:
      - SlackV3
      subject:
        simple: hi
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
        simple: shapatil@paloaltonetworks.com
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a435dd2a-aed2-4f45-8292-44d987c97404
      iscommand: false
      name: Escalation Manager selection task
      type: collection
      version: -1
    taskid: a435dd2a-aed2-4f45-8292-44d987c97404
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 50,
          "y": 230
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      incidentId:
        simple: ${incident.id}
      timerField:
        simple: datacollectiontimer
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.start.timer
      id: 32a98f20-3ced-4fe0-8229-e5794b0cea67
      iscommand: true
      name: Untitled Task
      script: Builtin|||startTimer
      type: regular
      version: -1
    taskid: 32a98f20-3ced-4fe0-8229-e5794b0cea67
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 420
        }
      }
  "3":
    continueonerrortype: ""
    form:
      description: sf
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: sf
        options: []
        optionsarg:
        - simple: "Yes"
        - simple: "No"
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: singleSelect
      sender: ""
      title: sf
      totalanswers: 0
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: dsf
      cc: null
      format: ""
      methods:
      - SlackV2
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
        simple: shapatil@paloaltonetworks.com
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b37e08a5-81ff-4122-889f-dbd63650c79a
      iscommand: false
      name: Untitled Task
      type: collection
      version: -1
    taskid: b37e08a5-81ff-4122-889f-dbd63650c79a
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 530,
          "y": 240
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 535,
        "width": 860,
        "x": 50,
        "y": -20
      }
    }
  }
