contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 200f5e69-4176-4d4b-84e5-43bea45a1668
inputs: []
name: Random user assignment from list
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8b8f027d-e0b8-4db1-8a92-d0df026b8eb7
      iscommand: false
      name: ""
      version: -1
    taskid: 8b8f027d-e0b8-4db1-8a92-d0df026b8eb7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        complex:
          accessor: shiftA
          root: lists
          transformers:
          - args:
              dt:
                value:
                  simple: .=rand(val); function rand(x){str=x.split(","); r=Math.floor(Math.random()
                    * str.length); return str[r]}
            operator: DT
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: e7413f7f-ffeb-4121-8a7f-e6faeeb3992b
      iscommand: false
      name: Random User assignment in Shifts
      script: Print
      type: regular
      version: -1
    taskid: e7413f7f-ffeb-4121-8a7f-e6faeeb3992b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 240
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 285,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
