contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 201643d3-8251-4c6f-8572-fa7985b43b01
inputs:
- description: ""
  key: incident_id
  playbookInputQuery: null
  required: false
  value:
    simple: 90,91
name: ReopenBulkIncidents
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e8a2e9f0-9ef7-412f-8908-2e6e5ce1b684
      iscommand: false
      name: ""
      version: -1
    taskid: e8a2e9f0-9ef7-412f-8908-2e6e5ce1b684
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      body:
        simple: '{"userFilter":false,"filter":{"page":0,"size":50,"query":"id:90","sort":[{"field":"id","asc":false}]}}'
      extend-context:
        simple: IncidentData.ID=.response.data.id::IncidentData.Version=.response.data.version
      uri:
        simple: /incidents/search
    separatecontext: false
    skipunavailable: false
    task:
      brand: Core REST API
      description: send HTTP POST request
      id: f9dc93d6-7589-4af1-827f-d9e31d736800
      iscommand: true
      name: Get Incident data
      script: Core REST API|||demisto-api-post
      type: regular
      version: -1
    taskid: f9dc93d6-7589-4af1-827f-d9e31d736800
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4ba2929d-bc19-4718-802f-957fae204654
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 4ba2929d-bc19-4718-802f-957fae204654
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 430
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 475,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
