contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: ca1bca5e-57b6-415e-8ad1-0689b29b9887
inputs: []
name: ReopenInvestigation
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 89e29cd4-bf33-4f52-8815-37245f70567a
      iscommand: false
      name: ""
      version: -1
    taskid: 89e29cd4-bf33-4f52-8815-37245f70567a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      fromdate:
        simple: 7 days ago
      limit:
        simple: "10"
      query:
        simple: status:Closed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Searches Demisto incidents. A summarized version of this scrips is avilable with the summarizedversion argument.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 7dc83525-6f3c-492b-8f72-6df91344cd12
      iscommand: false
      name: SearchIncidents
      script: SearchIncidentsV2
      type: regular
      version: -1
    taskid: 7dc83525-6f3c-492b-8f72-6df91344cd12
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 220
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    scriptarguments:
      incidentID:
        simple: ${foundIncidents.id}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 509e23ba-0a32-46b8-8eb0-d45e599885f9
      iscommand: false
      name: ReOpenBulkInvestigations
      playbookId: f1ef2508-0212-40bf-8d12-032ecfdd491c
      type: playbook
      version: -1
    taskid: 509e23ba-0a32-46b8-8eb0-d45e599885f9
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 445,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
