contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 8ccdcf35-3aba-470d-83de-c361ce63e5cd
inputs: []
name: test
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7c2a6b20-1be4-46e1-821b-b7f139bf0238
      iscommand: false
      name: ""
      version: -1
    taskid: 7c2a6b20-1be4-46e1-821b-b7f139bf0238
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 40,
          "y": -960
        }
      }
  "1":
    continueonerrortype: ""
    fieldMapping:
    - incidentfield: Phishing Sub-type
      output:
        simple: ${ext}
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Yes, 10 digit password
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Prints text to war room (Markdown supported)
      id: 23e5bece-7d87-4a45-863c-9b71f8c35229
      iscommand: false
      name: Set
      script: Print
      type: regular
      version: -1
    taskid: 23e5bece-7d87-4a45-863c-9b71f8c35229
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -460,
          "y": 0
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.details
          operator: isEqualString
          right:
            value:
              simple: "Yes"
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "4"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Gets a value and return it. This is to be used in playbook conditional
        tasks - get a value from incident field, label or context, and act accordingly.
        \nIf an array is returned. the first value will be the decision making value."
      id: 90a4f244-3953-426c-8cad-fa0eab8aa9a2
      iscommand: false
      name: Check if value exists in a list
      type: condition
      version: -1
    taskid: 90a4f244-3953-426c-8cad-fa0eab8aa9a2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 460
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: "Yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 397d181a-c48c-4e8a-83e9-ffbbd0189ad9
      iscommand: false
      name: Print Yes
      script: Print
      type: regular
      version: -1
    taskid: 397d181a-c48c-4e8a-83e9-ffbbd0189ad9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -230,
          "y": 640
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: "NO"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 9897edd3-3fd6-462d-8445-0f4492388e4a
      iscommand: false
      name: Print No
      script: Print
      type: regular
      version: -1
    taskid: 9897edd3-3fd6-462d-8445-0f4492388e4a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 310,
          "y": 660
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      roles:
        simple: windows
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: a2aea902-fd24-40be-8c20-8554f5d5b013
      iscommand: true
      name: Set Role to windows
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: a2aea902-fd24-40be-8c20-8554f5d5b013
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 660,
          "y": 470
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      closeNotes:
        simple: Test JOb
      closeReason:
        simple: Duplicate
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: b8178915-e35b-4226-8c87-c2ff6a210e86
      iscommand: true
      name: Close
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: b8178915-e35b-4226-8c87-c2ff6a210e86
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 20,
          "y": 1420
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 75fc9096-35bf-43df-8f46-38b62814b344
      iscommand: false
      name: Tags testing
      playbookId: 4615403c-bf6f-4113-8f54-dc780b92e502
      type: playbook
      version: -1
    taskid: 75fc9096-35bf-43df-8f46-38b62814b344
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 20,
          "y": 870
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 18047380-d535-4b54-8bf0-a74057c12048
      iscommand: false
      name: Tags testing
      playbookId: 4615403c-bf6f-4113-8f54-dc780b92e502
      type: playbook
      version: -1
    taskid: 18047380-d535-4b54-8bf0-a74057c12048
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 20,
          "y": 1050
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 42aa6572-5ba0-43b5-8a79-bdc0e7b74985
      iscommand: false
      name: Tags testing
      playbookId: 4615403c-bf6f-4113-8f54-dc780b92e502
      type: playbook
      version: -1
    taskid: 42aa6572-5ba0-43b5-8a79-bdc0e7b74985
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 20,
          "y": 1240
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "120"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: 51de3177-96d6-4eb3-8ad7-cb90e79ba822
      iscommand: false
      name: Untitled Task
      script: Sleep
      type: regular
      version: -1
    taskid: 51de3177-96d6-4eb3-8ad7-cb90e79ba822
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 280
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Passwd
      value:
        simple: sUresh@101$#
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 7eca8ab8-25e5-479e-835c-ec2c5325b404
      iscommand: false
      name: Provide Password
      script: Set
      type: regular
      version: -1
    taskid: 7eca8ab8-25e5-479e-835c-ec2c5325b404
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 10,
          "y": -510
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      contextKey:
        simple: PasswdResult
      data:
        simple: ${Passwd}
      flags:
        simple: gm
      regex:
        simple: (?=^.{10,}$)(?=.*\d)(?=.*[!@#$%^&*]+)(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Extracts regex data from the provided text. The script support
        groups and looping.
      id: 21aa0a87-4934-4c1f-8096-c74b18d561b7
      iscommand: false
      name: Validate password length
      script: MatchRegexV2
      type: regular
      version: -1
    taskid: 21aa0a87-4934-4c1f-8096-c74b18d561b7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 10,
          "y": -345
        }
      }
  "13":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${MatchRegex.results}
          operator: isEqualString
          right:
            iscontext: true
            value:
              simple: ${Passwd}
      label: "yes"
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 58adcf61-1772-469f-880d-5fe806ba37f9
      iscommand: false
      name: Password Length is 10
      type: condition
      version: -1
    taskid: 58adcf61-1772-469f-880d-5fe806ba37f9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 10,
          "y": -170
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e52ed29a-7421-4f84-8fae-bd0bf377936d
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: e52ed29a-7421-4f84-8fae-bd0bf377936d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 20,
          "y": 200
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      data:
        simple: Test
      filename:
        simple: TestFile.csv
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Creates a file (using the given data input or entry ID) and uploads it to the current investigation War Room.
      id: fc217565-abdd-4249-85b3-7af0d8b1e62f
      iscommand: false
      name: FileCreate
      script: FileCreateAndUploadV2
      type: regular
      version: -1
    taskid: fc217565-abdd-4249-85b3-7af0d8b1e62f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": -570
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    sla:
      days: 0
      hours: 0
      minutes: 0
      weeks: 0
    task:
      brand: ""
      id: 704ade2e-1f59-4c38-8dcb-fa13f25cc47b
      iscommand: false
      name: wait
      tags:
      - timerbreach
      type: regular
      version: -1
    taskid: 704ade2e-1f59-4c38-8dcb-fa13f25cc47b
    timertriggers:
    - action: start
      fieldname: demoslatimer
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": -680
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: test
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 9713feb3-20e9-4965-8e82-bef40d4d2cfc
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 9713feb3-20e9-4965-8e82-bef40d4d2cfc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 40,
          "y": -850
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2475,
        "width": 1500,
        "x": -460,
        "y": -960
      }
    }
  }
