contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 5cd8aa24-830d-4fe6-8493-9e21fe178e98
inputs:
- description: Please input the list of unique users and domains
  key: Unique_events
  playbookInputQuery: null
  required: false
  value: {}
name: Cust_IRC_Securonix_Cisco_Umbrella_master
outputs: []
quiet: true
sourceplaybookid: 63d20f81-72f6-4c47-80b4-daec4560c43f
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "46"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 264ebd1c-e951-4eb8-81c4-e7644b92cfad
      iscommand: false
      name: ""
      version: -1
    taskid: 264ebd1c-e951-4eb8-81c4-e7644b92cfad
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a42e4d72-0e13-416e-8bef-3df00a56c45c
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: a42e4d72-0e13-416e-8bef-3df00a56c45c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 1770
        }
      }
  "25":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: sourceusername
                root: incident
          operator: isNotEmpty
      label: Saved
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "26"
      Saved:
      - "37"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3ea38a03-dd07-4f26-8a79-0e695efe6eb3
      iscommand: false
      name: Check if source username is saved
      type: condition
      version: -1
    taskid: 3ea38a03-dd07-4f26-8a79-0e695efe6eb3
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 895
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    scriptarguments:
      hostname:
        complex:
          accessor: sourcehostname
          root: incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        This is a generic playbook which can be used across all other playbooks where the requirement is:
        * Resolving a hostname against EPO or ITAM (in the same order) and finding out the username associated with it
        * It adds the "internal.username" key to the context with enriched information
      id: 61af7e6e-9e01-4023-8052-1be634850497
      iscommand: false
      name: Cust_IRC_Generic_Find_User_Of_Host_master
      playbookId: 6afcc234-b2f6-4840-85a2-4a518288ffb9
      type: playbook
      version: -1
    taskid: 61af7e6e-9e01-4023-8052-1be634850497
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "27":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: username
                root: internal
          operator: isExists
          right:
            value: {}
      - - left:
            iscontext: true
            value:
              complex:
                accessor: username
                root: internal
          operator: isNotEmpty
      label: Resolved
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "33"
      Resolved:
      - "40"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 79a7d29f-62ff-4b98-8f6f-db3a0f7d603c
      iscommand: false
      name: Check if user resolved
      type: condition
      version: -1
    taskid: 79a7d29f-62ff-4b98-8f6f-db3a0f7d603c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "31":
    continueonerrortype: ""
    id: "31"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "41"
    note: false
    quietmode: 0
    scriptarguments:
      username:
        complex:
          accessor: sourceusername
          root: incident
          transformers:
          - args:
              to:
                value:
                  simple: '@wipro.com'
            operator: substringTo
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        This is a generic playbook which can be used across all other playbooks where the requirement is:
        * Resolving a username against EPO or ITAM (in the same order) and finding out the hostname associated with it
        * It adds the "internal.hostname" key to the context with enriched information
      id: 8f095269-c5c2-4898-8236-4e81af53a5a5
      iscommand: false
      name: Cust_IRC_Generic_Find_Host_Of_User_master
      playbookId: b3dbbaae-4e4b-47e2-815e-c0dedd468933
      type: playbook
      version: -1
    taskid: 8f095269-c5c2-4898-8236-4e81af53a5a5
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 1420
        }
      }
  "33":
    continueonerrortype: ""
    id: "33"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "40"
    note: false
    quietmode: 0
    scriptarguments:
      Domain:
        complex:
          accessor: domainname
          root: incident
      hostname:
        complex:
          accessor: sourcehostname
          root: incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7b8df217-bdf2-4e2a-8048-7411df984589
      iscommand: false
      name: Cust_IRC_Securonix_Cisco_Umbrella_Common_subplaybook_Compliance_Check
      playbookId: 4a00c6a4-93f4-4711-85c8-144874223704
      type: playbook
      version: -1
    taskid: 7b8df217-bdf2-4e2a-8048-7411df984589
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1420
        }
      }
  "37":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: sourcehostname
                root: incident
          operator: isNotEmpty
      label: Saved
    continueonerrortype: ""
    id: "37"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "31"
      Saved:
      - "41"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8b458343-3fa8-44f4-888a-1599a09e7647
      iscommand: false
      name: Check if source hostname is  saved
      type: condition
      version: -1
    taskid: 8b458343-3fa8-44f4-888a-1599a09e7647
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 705,
          "y": 1245
        }
      }
  "40":
    continueonerrortype: ""
    id: "40"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      Domain:
        complex:
          accessor: domainname
          root: incident
      Event Threshold:
        complex:
          accessor: Wipro_IRC_Cisco_Umbrella_usecase_event_threshold
          root: lists
          transformers:
          - args:
              field:
                iscontext: true
                value:
                  simple: incident.securonixpolicy
            operator: getField
      Hostname:
        complex:
          accessor: sourcehostname
          root: incident
      Username:
        complex:
          accessor: username
          root: internal
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8c5b01d2-8ce5-48ba-8af8-b780507b8c3a
      iscommand: false
      name: Cust_IRC_Cisco_Umbrella_Playbook_enrichment_actions
      playbookId: 077565ac-0e28-487c-8d0f-6e43e5138da9
      type: playbook
      version: -1
    taskid: 8c5b01d2-8ce5-48ba-8af8-b780507b8c3a
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
  "41":
    continueonerrortype: ""
    id: "41"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      Domain:
        complex:
          accessor: domainname
          root: incident
      Event Threshold:
        complex:
          accessor: Wipro_IRC_Cisco_Umbrella_usecase_event_threshold
          root: lists
          transformers:
          - args:
              field:
                iscontext: true
                value:
                  simple: incident.securonixpolicy
            operator: getField
      Hostname:
        complex:
          accessor: hostname
          root: internal
          transformers:
          - args:
              applyIfEmpty: {}
              defaultValue:
                iscontext: true
                value:
                  simple: incident.sourcehostname
            operator: SetIfEmpty
      Username:
        complex:
          accessor: sourceusername
          root: incident
          transformers:
          - args:
              to:
                value:
                  simple: '@wipro.com'
            operator: substringTo
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ed442e7a-71a1-4a9f-8333-1141a1d49032
      iscommand: false
      name: Cust_IRC_Cisco_Umbrella_Playbook_enrichment_actions
      playbookId: 077565ac-0e28-487c-8d0f-6e43e5138da9
      type: playbook
      version: -1
    taskid: ed442e7a-71a1-4a9f-8333-1141a1d49032
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 705,
          "y": 1595
        }
      }
  "43":
    continueonerrortype: ""
    id: "43"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "44"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        This is a generic playbook which is used across all other Securonix playbooks. It start the following timers:
        * INC Ack SLA Timer
        * INC Triage SLA Timer
        * QI Ack SLA Timer
        * QI Containment SLA Timer
        * QI Resolution SLA Timer
        * QI Closure SLA Timer
        * MTTD
        * TTAA
        * TTQ
      id: 0e7e777a-211b-4641-8f23-7125a812c4f8
      iscommand: false
      name: Cust_IRC_Securonix_Generic_Start_SLAs
      playbookId: 825c0dae-5f1e-46fe-80e0-ac72996e8129
      type: playbook
      version: -1
    taskid: 0e7e777a-211b-4641-8f23-7125a812c4f8
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 370
        }
      }
  "44":
    continueonerrortype: ""
    id: "44"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "45"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This is a Securonix initializer playbook which identifies the violator
        type, gets the associated policy violations, associates MITRE indicators,
        sets default priority and severity and assigns an analyst to the incident
      id: dceef309-07a5-40a4-80c1-5add03577f19
      iscommand: false
      name: Cust_IRC_Securonix_Initializer
      playbookId: 3217ac4e-38e5-4d81-8c38-faf7200efc22
      type: playbook
      version: -1
    taskid: dceef309-07a5-40a4-80c1-5add03577f19
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 545
        }
      }
  "45":
    continueonerrortype: ""
    id: "45"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    scriptarguments:
      deviceaction:
        complex:
          accessor: ViolationData
          root: Securonix
          transformers:
          - args:
              field:
                value:
                  simple: deviceaction
            operator: getField
          - operator: uniq
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      domainname:
        complex:
          accessor: ViolationData
          root: Securonix
          transformers:
          - args:
              field:
                value:
                  simple: destinationdnsdomain
            operator: getField
          - operator: uniq
          - args:
              separator:
                value:
                  simple: ','
            operator: join
      sourceusername:
        complex:
          accessor: ViolationData
          root: Securonix
          transformers:
          - args:
              field:
                value:
                  simple: sourceusername
            operator: getField
          - operator: uniq
          - args:
              separator:
                value:
                  simple: ','
            operator: join
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 982f6962-6f1b-4f16-8e92-6c8ab4c6eb42
      iscommand: true
      name: Set the required usecase specific incident fields in the layout
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 982f6962-6f1b-4f16-8e92-6c8ab4c6eb42
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 720
        }
      }
  "46":
    continueonerrortype: ""
    id: "46"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "43"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This is a generic subplaybook of Wipro_IRC_Generic_Assign_Analyst_Shift_Based_master
        which checks the input role and reads the list and assigns the analyst accordingly
      id: a8dda148-f8ec-4e96-81e8-eced6a1d7910
      iscommand: false
      name: Cust_IRC_Generic_Assign_Analyst_Shift_Based_subplaybook
      playbookName: Wipro_IRC_Generic_Assign_Analyst_Shift_Based_subplaybook
      type: playbook
      version: -1
    taskid: a8dda148-f8ec-4e96-81e8-eced6a1d7910
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1785,
        "width": 1035,
        "x": 50,
        "y": 50
      }
    }
  }
