contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 5d8493d5-65bc-4dc1-8b8a-4aef68a19d41
inputs: []
name: Sendmail
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7b51a974-9359-41d8-89c7-62f590def39d
      iscommand: false
      name: ""
      version: -1
    taskid: 7b51a974-9359-41d8-89c7-62f590def39d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 760,
          "y": 60
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      subject:
        simple: testing task in subplaybook
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends an email.
      id: 726017a6-cc82-49f7-8414-458f8478288d
      iscommand: true
      name: Sendmail
      script: '|||send-mail'
      type: regular
      version: -1
    taskid: 726017a6-cc82-49f7-8414-458f8478288d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 760,
          "y": 230
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      email:
        simple: shapatil@paloaltonetworks.com
      message:
        simple: reply
      subject:
        simple: test email ask user
      task:
        simple: "3"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Ask a user a question via email and process the reply directly
        into the investigation.
      id: 20d04fba-69be-44c8-8e67-668c2c012abd
      iscommand: false
      name: Untitled Task
      script: EmailAskUser
      type: regular
      version: -1
    taskid: 20d04fba-69be-44c8-8e67-668c2c012abd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 750,
          "y": 420
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: sd
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: eb819004-5b7d-4091-8753-1569b6b44291
      iscommand: false
      name: Untitled Task
      script: Print
      type: regular
      version: -1
    taskid: eb819004-5b7d-4091-8753-1569b6b44291
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 750,
          "y": 570
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 605,
        "width": 390,
        "x": 750,
        "y": 60
      }
    }
  }
