contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 98b92f17-c5c6-4a91-80e0-21653cf7d605
inputs: []
name: TIM - Export Indicator in STIX
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dfbf679c-10f8-484c-8911-8d4b7e6b19d8
      iscommand: false
      name: ""
      version: -1
    taskid: dfbf679c-10f8-484c-8911-8d4b7e6b19d8
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: type:IP
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: |-
        Searches Cortex XSOAR Indicators.

        Search for XSOAR Indicators and returns the id, indicator_type, value, and score/verdict.

        You can add additional fields from the indicators using the add_field_to_context argument.
      id: 5d26a105-a8a1-4702-8bd9-7db53e2b6144
      iscommand: false
      name: Search Indicators
      script: SearchIndicator
      type: regular
      version: -1
    taskid: 5d26a105-a8a1-4702-8bd9-7db53e2b6144
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 220
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      body:
        simple: '{"ids":${foundIndicators.id},"all":false,"filter":{"page":0,"size":50,"query":"type:IP","sort":[{"field":"calculatedTime","asc":false}],"period":{"by":"day","fromValue":7}},"columns":["indicator_type","value","score","firstSeen","lastSeen","timestamp","relatedIncCount","sourceBrands","sourceInstances","expirationStatus","expiration","isUnit42Enriched"]}'
      extend-context:
        simple: APIData=
      uri:
        simple: /indicators/batch/export/stix
    separatecontext: false
    skipunavailable: false
    task:
      brand: Core REST API
      description: send HTTP POST request.
      id: 09dba819-95f2-43f1-8155-f1e58b414362
      iscommand: true
      name: Batch export to STIX
      script: Core REST API|||core-api-post
      type: regular
      version: -1
    taskid: 09dba819-95f2-43f1-8155-f1e58b414362
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 430
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      filename:
        simple: Test.json
      uri:
        simple: /indicators/stix/${APIData.response.filename}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Core REST API
      description: Download files from Core server.
      id: 9aa6db54-fe18-4f7b-81ea-7f5fc1cc16f2
      iscommand: true
      name: Download the STIX format file
      script: Core REST API|||core-api-download
      type: regular
      version: -1
    taskid: 9aa6db54-fe18-4f7b-81ea-7f5fc1cc16f2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 645
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "5"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: e664c188-cf22-434c-8115-5c3dcb85688b
      iscommand: false
      name: wait for file to generate
      script: Sleep
      type: regular
      version: -1
    taskid: e664c188-cf22-434c-8115-5c3dcb85688b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 990,
          "y": 550
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 690,
        "width": 920,
        "x": 450,
        "y": 50
      }
    }
  }
