contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: SplitData Contribution Pack
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: c33af6c7-700a-4110-8c69-1fa70909d05f
inputs:
- description: ""
  key: DataPrint
  playbookInputQuery: null
  required: false
  value: {}
name: PrintinLoop
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7d77ff3c-c563-47a8-8b4e-bd3149ca619f
      iscommand: false
      name: ""
      version: -1
    taskid: 7d77ff3c-c563-47a8-8b4e-bd3149ca619f
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 2
    scriptarguments:
      value:
        complex:
          accessor: DataPrint}
          root: ${inputs
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: e35a0433-1734-46b0-8a18-cbc48405e99b
      iscommand: false
      name: Print Data
      script: Print
      type: regular
      version: -1
    taskid: e35a0433-1734-46b0-8a18-cbc48405e99b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 240
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ae49db41-a7d8-4cd1-897c-cd3aa8e6ffa5
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: ae49db41-a7d8-4cd1-897c-cd3aa8e6ffa5
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 390
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 405,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
