contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: f3fb96a5-9bc4-4158-8917-bf80e9f30a6b
inputs: []
name: newplaybook
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ae0254f2-d12e-41da-83d3-4b8db9a8a6fc
      iscommand: false
      name: ""
      version: -1
    taskid: ae0254f2-d12e-41da-83d3-4b8db9a8a6fc
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9e6a973f-e7f3-4502-8e85-42302c7cf1b7
      iscommand: false
      name: User Response
      tags:
      - response
      type: regular
      version: -1
    taskid: 9e6a973f-e7f3-4502-8e85-42302c7cf1b7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      responseEntryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Extract user's response from EmailAskUser reply. Returns the first
        textual response line of the provided entry that contains the reply body.
        Use ${lastCompletedTaskEntries} to analyze the previous playbook task containing
        the user's reply.
      id: 9f41b138-3792-41b6-8f0c-a17f03a13c50
      iscommand: false
      name: Validating User response
      script: EmailAskUserResponse
      type: condition
      version: -1
    taskid: 9f41b138-3792-41b6-8f0c-a17f03a13c50
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      DatetimeToWaitUntil:
        simple: ${initiatetime]
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: Pauses execution until the date and time that was specified in
        the plabyook input is reached.
      id: 9bc9d50a-7041-487f-8ecb-9e52bb21e091
      iscommand: false
      name: Wait Until Datetime
      playbookId: Wait Until Datetime
      type: playbook
      version: -1
    taskid: 9bc9d50a-7041-487f-8ecb-9e52bb21e091
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: initiatetime
      value:
        complex:
          accessor: created
          root: incident
          transformers:
          - args:
              variation:
                value:
                  simple: in 2 minutes
            operator: ModifyDateTime
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: dc68cadb-8f5a-4e68-8a30-b7e99b6cdcd8
      iscommand: false
      name: Set wait time by 2 minutes
      script: Set
      type: regular
      version: -1
    taskid: dc68cadb-8f5a-4e68-8a30-b7e99b6cdcd8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
