contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: dcf479b3-db2a-4ae2-89ea-1ec3f046ff88
inputs: []
name: Cust_IRC_Securonix_Zscaler_Cloud_Sandbox_Master
outputs: []
sourceplaybookid: 9885d44c-cd1e-4b75-8082-e74048252aff
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b72f9aaa-f8e4-4dc4-8032-25094629784a
      iscommand: false
      name: ""
      version: -1
    taskid: b72f9aaa-f8e4-4dc4-8032-25094629784a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      bamd5:
        complex:
          accessor: devicecustomstring4
          root: Securonix.ViolationData
          transformers:
          - args:
              delimiter: {}
            operator: splitAndTrim
      dst_ip:
        complex:
          accessor: destinationaddress
          root: Securonix.ViolationData
          transformers:
          - operator: uniq
          - args:
              prefix:
                value:
                  simple: '"'
              suffix:
                value:
                  simple: '"'
            operator: concat
          - args:
              separator:
                value:
                  simple: ' OR '
            operator: join
      hostname:
        complex:
          accessor: devicehostname
          root: Securonix.ViolationData
          transformers:
          - operator: trim
      http_status_code:
        complex:
          accessor: eventoutcome
          root: Securonix.ViolationData
          transformers:
          - operator: trim
      src_ip:
        complex:
          accessor: sourceaddress
          root: Securonix.ViolationData
          transformers:
          - operator: uniq
          - args:
              prefix:
                value:
                  simple: '"'
              suffix:
                value:
                  simple: '"'
            operator: concat
          - args:
              separator:
                value:
                  simple: ' OR '
            operator: join
      username:
        complex:
          accessor: lanid
          root: Securonix.ViolationData
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 963a6ebc-184b-4d58-89e4-ad43af7ba89c
      iscommand: false
      name: Cust_IRC_Securonix_Zscaler Cloud Sandbox - Subplaybook
      playbookId: df3bef29-f6d1-44be-8f2c-1dd36462dca7
      type: playbook
      version: -1
    taskid: 963a6ebc-184b-4d58-89e4-ad43af7ba89c
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a7778a25-e6ac-4dd0-8bcd-7780bbbcf980
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: a7778a25-e6ac-4dd0-8bcd-7780bbbcf980
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: f36d5459-90f6-41f3-8b26-67f0d65e8fe2
      iscommand: false
      name: Clear context
      script: DeleteContext
      type: regular
      version: -1
    taskid: f36d5459-90f6-41f3-8b26-67f0d65e8fe2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: Zscaler_Category
          operator: isEqualString
          right:
            value:
              simple: BENIGN
        - left:
            iscontext: true
            value:
              complex:
                root: Zscaler_Category
          operator: isEqualString
          right:
            value:
              simple: NONE
        - left:
            iscontext: true
            value:
              complex:
                root: Zscaler_Category
          operator: isEmpty
      label: Benign/None
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      Benign/None:
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c5e4230e-8092-4c9e-8b05-2cf93f31180a
      iscommand: false
      name: check Zscaler Category
      type: condition
      version: -1
    taskid: c5e4230e-8092-4c9e-8b05-2cf93f31180a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This is a generic playbook which is used across all other playbooks(Securonix
        dependent). It assigns an analyst to the incident based on the shift roster
      id: cc3112fe-ddcd-4f6a-8a41-88ecb8623e4f
      iscommand: false
      name: Cust_IRC_Securonix_Generic_Assign_Owner
      playbookId: cf99b3fe-2026-4266-8a77-cf78dd8b70fc
      type: playbook
      version: -1
    taskid: cc3112fe-ddcd-4f6a-8a41-88ecb8623e4f
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        This is a generic playbook which is used across all other Securonix playbooks. It start the following timers:
        * INC Ack SLA Timer
        * INC Triage SLA Timer
        * QI Ack SLA Timer
        * QI Containment SLA Timer
        * QI Resolution SLA Timer
        * QI Closure SLA Timer
        * MTTD
        * TTAA
        * TTQ
      id: 0dbef78e-b812-45df-8564-460a11049b32
      iscommand: false
      name: Cust_IRC_Securonix_Generic_Start_SLAs
      playbookId: 825c0dae-5f1e-46fe-80e0-ac72996e8129
      type: playbook
      version: -1
    taskid: 0dbef78e-b812-45df-8564-460a11049b32
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This is a Securonix initializer playbook which identifies the violator
        type, gets the associated policy violations, associates MITRE indicators,
        sets default priority and severity and assigns an analyst to the incident
      id: d49ba409-ffa2-4d10-83fa-88296a1461fa
      iscommand: false
      name: Cust_IRC_Securonix_Initializer
      playbookId: 3217ac4e-38e5-4d81-8c38-faf7200efc22
      type: playbook
      version: -1
    taskid: d49ba409-ffa2-4d10-83fa-88296a1461fa
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        This is a generic playbook which can be used across all other Securonix playbooks where the requirement is:
        * Closing the incident on XSOAR
        * Sending an email to the end user/analyst
      id: ea81463d-a696-4f20-8ec4-ad7c51a117a9
      iscommand: false
      name: Cust_IRC_Securonix_Generic_SendMail_CloseIncident
      playbookName: Wipro_IRC_Securonix_Generic_SendMail_CloseIncident
      type: playbook
      version: -1
    taskid: ea81463d-a696-4f20-8ec4-ad7c51a117a9
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 160,
          "y": 1420
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      dateFormat:
        simple: ISO
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Retrieves the current date and time.
      id: 82498364-592f-4881-83f3-cf769265c0a9
      iscommand: false
      name: Gettime Now
      script: GetTime
      type: regular
      version: -1
    taskid: 82498364-592f-4881-83f3-cf769265c0a9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1610,
        "width": 490,
        "x": 50,
        "y": 50
      }
    }
  }
