contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: d4ec0947-ff08-4d6e-800f-09b5d4fc25f4
inputs: []
name: get email address playbook
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 43271c59-ead2-45ef-8830-488678703d20
      iscommand: false
      name: ""
      version: -1
    taskid: 43271c59-ead2-45ef-8830-488678703d20
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      header:
        simple: ip
      list_name:
        simple: testjson
      value:
        simple: 1.1.1.1
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Parses a list by header and value.
      id: 5d0c6857-d466-4074-8806-1fffd40a00d6
      iscommand: false
      name: get email address
      script: GetListRow
      type: regular
      version: -1
    taskid: 5d0c6857-d466-4074-8806-1fffd40a00d6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 245,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
