contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 1d00dcf8-c830-40b8-88d9-0c124cb13e90
inputs:
- description: ""
  key: IP
  playbookInputQuery: null
  required: false
  value:
    simple: Data.IP
name: testsubplybookloop
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1ff8f548-8336-47a9-8097-aab5c5864ee9
      iscommand: false
      name: ""
      version: -1
    taskid: 1ff8f548-8336-47a9-8097-aab5c5864ee9
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      value:
        simple: ${inputs.IP}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 27eeefe4-a2fa-4219-8652-12b69c1b97c8
      iscommand: false
      name: print value
      script: Print
      type: regular
      version: -1
    taskid: 27eeefe4-a2fa-4219-8652-12b69c1b97c8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 220
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 265,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
