contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 7f5c8881-496f-4517-8f15-85ff64b61fe4
inputs: []
name: Qradar - Risky User
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d7c7a7ac-3a63-411d-8fe7-ade7bb008a31
      iscommand: false
      name: ""
      version: -1
    taskid: d7c7a7ac-3a63-411d-8fe7-ade7bb008a31
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 740,
          "y": 80
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      body:
        simple: Detected new login for ${incident.username} at ${incident.occurred}
      subject:
        simple: Test Email
      to:
        simple: ${incident.username}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Send an email
      id: bdda79b7-84a1-45a8-800a-2a761e550908
      iscommand: true
      name: Send Email
      script: '|||send-mail'
      type: regular
      version: -1
    taskid: bdda79b7-84a1-45a8-800a-2a761e550908
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 570,
          "y": 380
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.username
          operator: containsString
          right:
            value:
              simple: '@'
      - - left:
            iscontext: true
            value:
              simple: incident.severity
          operator: isEqualString
          right:
            value:
              simple: High
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c613ed56-d93f-407f-805d-9f92a57415a8
      iscommand: false
      name: 'Is it risky? '
      type: condition
      version: -1
    taskid: c613ed56-d93f-407f-805d-9f92a57415a8
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 740,
          "y": 195
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: unknown email
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 1b51d625-a86e-4e10-87a6-35a740ded470
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 1b51d625-a86e-4e10-87a6-35a740ded470
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1090,
          "y": 380
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: aed2659e-5645-4366-85a9-face1068a707
      iscommand: true
      name: Close
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: aed2659e-5645-4366-85a9-face1068a707
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 760,
          "y": 590
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 605,
        "width": 900,
        "x": 570,
        "y": 80
      }
    }
  }
