contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 3a1e6563-af90-4aeb-857c-7d44dd8bc1bf
inputs: []
name: Email Subject
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: eab0ca3e-4851-4367-8915-76f5dc57d84b
      iscommand: false
      name: ""
      version: -1
    taskid: eab0ca3e-4851-4367-8915-76f5dc57d84b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 710,
          "y": 30
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.labels.Email/subject
          operator: containsGeneral
          right:
            value:
              simple: urgent
      label: "yes"
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 49e2ce84-397d-459d-80bb-174b4ce949fd
      iscommand: false
      name: Check Email Subject Contains Urgent
      type: condition
      version: -1
    taskid: 49e2ce84-397d-459d-80bb-174b4ce949fd
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 710,
          "y": 200
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: EWSO365
      description: Sends an email.
      id: 2eca2b2b-4ec4-4b19-8698-edd7775957cc
      iscommand: false
      name: Print Urgent
      type: regular
      version: -1
    taskid: 2eca2b2b-4ec4-4b19-8698-edd7775957cc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 350,
          "y": 450
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 41f2c239-e616-4ed0-8726-12be06c390bd
      iscommand: false
      name: Print Not Urgent
      type: regular
      version: -1
    taskid: 41f2c239-e616-4ed0-8726-12be06c390bd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 950,
          "y": 460
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 525,
        "width": 980,
        "x": 350,
        "y": 30
      }
    }
  }
