contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 99788f3d-2a74-4f71-86ed-63a27a121154
inputs:
- description: ""
  key: host
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: user
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: dest_ip
  playbookInputQuery: null
  required: false
  value: {}
name: Playbook to perform rest of task
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 34e1a63f-d740-42b5-88c2-c187ac72cfcd
      iscommand: false
      name: ""
      version: -1
    taskid: 34e1a63f-d740-42b5-88c2-c187ac72cfcd
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${inputs.host} | ${inputs.user} | ${inputs.dest_ip}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 121533f4-f774-48dd-8c7b-1f0d6451613b
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 121533f4-f774-48dd-8c7b-1f0d6451613b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 75c897f4-e15f-4fd7-8aeb-c6ff89ce9deb
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 75c897f4-e15f-4fd7-8aeb-c6ff89ce9deb
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 415,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
