contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: 2.1.18
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
description: "Create ServiceNow Ticket allows you to open new tickets as a task from
  a parent playbook.\nWhen creating the ticket, you can decide to update based on
  on the ticket's state, which will wait for the ticket to resolve or close with StatePolling.
  \nAlternatively, you can select to mirror the ServiceNow ticket and incident fields.
  \ To apply either of these options, set the SyncTicket value in the playbook inputs
  to one of the following options: \n1. StatePolling\n2. Mirror\n3. Leave Blank to
  use none."
id: 1282d406-1654-45ec-802f-234a38e09e41
inputs:
- description: Set the category of the ServiceNow Ticket.
  key: Category
  playbookInputQuery: null
  required: false
  value: {}
- description: The group to which to assign the new ticket.
  key: AssignmentGroup
  playbookInputQuery: null
  required: false
  value: {}
- description: Set a short description of the ticket.
  key: ShortDescription
  playbookInputQuery: null
  required: false
  value: {}
- description: Set the impact for the new ticket. Leave empty for ServiceNow default
    impact.
  key: Impact
  playbookInputQuery: null
  required: false
  value: {}
- description: Set the urgency of the new ticket. Leave empty for ServiceNow default
    urgency.
  key: Urgency
  playbookInputQuery: null
  required: false
  value: {}
- description: Set the severity of the new ticket. Leave empty for ServiceNow default
    severity.
  key: 'Severity '
  playbookInputQuery: null
  required: false
  value: {}
- description: Add a comment for the created ticket.
  key: Comment
  playbookInputQuery: null
  required: false
  value: {}
- description: "In this use case, Additional polling commands are relevant when using
    StatePolling, and there is more than one ServiceNow instance. It will specify
    the polling command to use a specific instance to run on. \nIf so, please add
    \"Using\" to the value. \nThe playbook will then take the instance name as the
    instance to use. "
  key: AdditionalPollingCommandName
  playbookInputQuery: null
  required: false
  value: {}
- description: |
    Set the ServiceNow Instance that will be used for mirroring/running polling commands.
  key: InstanceName
  playbookInputQuery: null
  required: false
  value:
    simple: jira-v2_instance_srik
- description: Set tags for mirror comments and files to ServiceNow.
  key: MirrorCommentTags
  playbookInputQuery: null
  required: false
  value:
    simple: comment,attachment
- description: ""
  key: MirrorDirection
  playbookInputQuery: null
  required: false
  value:
    simple: In
name: Create Jira Ticket
outputs: []
sourceplaybookid: Create ServiceNow Ticket
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d5f3e2ce-d90b-4890-8079-2e6dfb2c26c3
      iscommand: false
      name: ""
      version: -1
    taskid: d5f3e2ce-d90b-4890-8079-2e6dfb2c26c3
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": -200,
          "y": 50
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      description:
        simple: Test JIRA Mirroring
      issueTypeName:
        simple: task
      projectName:
        simple: cs
      summary:
        simple: XSOAR ticket 1
      using:
        simple: jira-v2_instance_srik
    separatecontext: false
    skipunavailable: false
    task:
      brand: jira-v2
      description: Creates a new issue in Jira.
      id: 670bac1d-87e0-4e33-8923-75c7d9fa2eb7
      iscommand: true
      name: Create JIRA ticket
      script: jira-v2|||jira-create-issue
      type: regular
      version: -1
    taskid: 670bac1d-87e0-4e33-8923-75c7d9fa2eb7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -200,
          "y": 205
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 42d5c30c-a509-4f23-8bf3-0a4184d6cae6
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 42d5c30c-a509-4f23-8bf3-0a4184d6cae6
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1100
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      dbotMirrorDirection:
        simple: ${inputs.MirrorDirection}
      dbotMirrorId:
        simple: ${Ticket.[0].Id}
      dbotMirrorInstance:
        simple: ${inputs.InstanceName}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 5a399eaa-a5c0-494c-8630-9496e649544b
      iscommand: true
      name: Enable JIRA Ticket Mirroring
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 5a399eaa-a5c0-494c-8630-9496e649544b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -200,
          "y": 380
        }
      }
  "13":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: que1
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: shortText
      sender: Your SOC team
      title: Waiting for JIRA ticket Approval
      totalanswers: 0
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: null
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: false
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1a759d0f-de2d-44c7-82ee-742a6c87b4f2
      iscommand: false
      name: Waiting for JIRA ticket Approval
      tags:
      - waiting
      type: collection
      version: -1
    taskid: 1a759d0f-de2d-44c7-82ee-742a6c87b4f2
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 265,
          "y": 565
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${incident.closeNotes}
          operator: isEqualString
          right:
            value:
              simple: success
      label: "yes"
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 33d534d7-5221-432f-81d8-2fe9ed1c0177
      iscommand: false
      name: Check return status of BlockIP
      type: condition
      version: -1
    taskid: 33d534d7-5221-432f-81d8-2fe9ed1c0177
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: ${incident.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 080ba5b3-ad5a-474d-86f4-37ee70a55a76
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 080ba5b3-ad5a-474d-86f4-37ee70a55a76
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "16":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          complex:
            accessor: sourceip
            root: incident
            transformers:
            - args:
                prefix:
                  value:
                    simple: Please investigate this IPs
                suffix: {}
              operator: concat
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: shortText
      sender: ""
      title: Manual Investigation Required
      totalanswers: 0
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        complex:
          accessor: sourceip
          root: incident
          transformers:
          - args:
              prefix:
                value:
                  simple: 'Source IP '
              suffix:
                value:
                  simple: ' need to be investigated'
            operator: concat
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: false
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7c1f8178-e390-4c13-8f14-ef56f74b65da
      iscommand: false
      name: Manual Investigation Required
      type: collection
      version: -1
    taskid: 7c1f8178-e390-4c13-8f14-ef56f74b65da
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dfdab83b-e86f-471c-86df-c3c6d7bee33e
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: dfdab83b-e86f-471c-86df-c3c6d7bee33e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -200,
          "y": 620
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 1060,
        "x": -200,
        "y": 50
      }
    }
  }
