contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 0cf574b0-dda8-432f-8135-1bdf85923f72
inputs: []
name: 'Demo - Playbook '
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8a777f26-91b1-4143-85ea-47614cc42833
      iscommand: false
      name: ""
      version: -1
    taskid: 8a777f26-91b1-4143-85ea-47614cc42833
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    scriptarguments:
      'IP ':
        simple: 195.22.26.248
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 20ab6873-224a-4df4-8423-09cb7850f627
      iscommand: false
      name: Demo - Sub Playbook Output
      playbookId: fb4716be-86c0-48c4-8d2f-80c9c99952bb
      type: playbook
      version: -1
    taskid: 20ab6873-224a-4df4-8423-09cb7850f627
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
