contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: e5b5ec4a-fd14-4054-812f-7213301fd546
inputs: []
name: ExtractIncidentContext
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 149b61cc-ef7c-48ec-8b3e-85d604cde6cd
      iscommand: false
      name: ""
      version: -1
    taskid: 149b61cc-ef7c-48ec-8b3e-85d604cde6cd
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      fromdate:
        simple: 7 Days ago
      query:
        simple: id:111429
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Searches Demisto incidents.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: 4bcee0a3-66ce-4e35-8d29-5b5474dfe1c6
      iscommand: false
      name: GetIncidentID
      script: SearchIncidentsV2
      type: regular
      version: -1
    taskid: 4bcee0a3-66ce-4e35-8d29-5b5474dfe1c6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      get_key:
        simple: PaloAltoNetworksXDR
      incident_id:
        simple: ${foundIncidents.id}
      set_key:
        simple: incidentexportdata
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets a value from the specified incident's context.
      id: 08c567ba-9a3b-478c-8fd0-ca8d014ab92f
      iscommand: false
      name: Extract Incident Context
      script: GetByIncidentId
      type: regular
      version: -1
    taskid: 08c567ba-9a3b-478c-8fd0-ca8d014ab92f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      csvArray:
        simple: ${incidentexportdata}
      fileName:
        simple: ${foundIncidents.id}.csv
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Export given array to csv file
      id: e64de28c-0dc3-46ab-8eab-915e73d63b16
      iscommand: false
      name: Create CSV
      script: ExportToCSV
      type: regular
      version: -1
    taskid: e64de28c-0dc3-46ab-8eab-915e73d63b16
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
      keysToKeep:
        simple: File
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: 182b26e6-089b-4ff7-8535-1217f23c6658
      iscommand: false
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: 182b26e6-089b-4ff7-8535-1217f23c6658
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
