contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 43e5403f-e058-453d-84cf-07c634307d98
inputs: []
name: DemoTestPlaybook
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 928ae4ee-0ff9-4ed4-8344-a8bd1cc7ade1
      iscommand: false
      name: ""
      version: -1
    taskid: 928ae4ee-0ff9-4ed4-8344-a8bd1cc7ade1
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      socassigned:
        simple: "1"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: cdb98daf-7531-41e5-85d9-3e8915e54391
      iscommand: true
      name: Set field SOCAssigned
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: cdb98daf-7531-41e5-85d9-3e8915e54391
    timertriggers:
    - action: start
      fieldname: demoslatimer
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "2":
    continueonerrortype: ""
    form:
      description: Test Survery
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: 'Tell me about experience '
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: longText
      sender: ""
      title: Suvery Question
      totalanswers: 0
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Please fill the survery
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d431782a-49d0-41d1-8e3b-fd77b1bbe9d0
      iscommand: false
      name: SOC Anlayst
      type: collection
      version: -1
    taskid: d431782a-49d0-41d1-8e3b-fd77b1bbe9d0
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": -30,
          "y": 400
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      socassigned:
        simple: "0"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: f0db8f94-4840-45b3-8a7b-08b8e549f2e7
      iscommand: true
      name: Set field SOCAssigned
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: f0db8f94-4840-45b3-8a7b-08b8e549f2e7
    timertriggers:
    - action: pause
      fieldname: demoslatimer
    type: regular
    view: |-
      {
        "position": {
          "x": 300,
          "y": 740
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 960fdf60-ab98-4cd5-8e97-32a3700aacf5
      iscommand: false
      name: Is this an incident
      type: condition
      version: -1
    taskid: 960fdf60-ab98-4cd5-8e97-32a3700aacf5
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 980,
          "y": 390
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: "Yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 8b46120b-1360-450a-8abe-72ecfd3c72d4
      iscommand: false
      name: Print "Yes"
      script: Print
      type: regular
      version: -1
    taskid: 8b46120b-1360-450a-8abe-72ecfd3c72d4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1400,
          "y": 560
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Yes its an incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 93a83616-1ca3-41a6-8ec5-801b28092514
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: 93a83616-1ca3-41a6-8ec5-801b28092514
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 300,
          "y": 970
        }
      }
  "7":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Provide the severity ?
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: shortText
      sender: ""
      title: Change the incident Severity
      totalanswers: 0
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Test Survery
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ae8dd3e4-e6a3-4e06-8678-7aa7946a3a35
      iscommand: false
      name: Need Analyst Inputs
      type: collection
      version: -1
    taskid: ae8dd3e4-e6a3-4e06-8678-7aa7946a3a35
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 300,
          "y": 1310
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      socassigned:
        simple: "1"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 3c6b4012-5547-42c8-8582-95a60688897b
      iscommand: true
      name: Set field SOCAssigned
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 3c6b4012-5547-42c8-8582-95a60688897b
    timertriggers:
    - action: start
      fieldname: demoslatimer
    type: regular
    view: |-
      {
        "position": {
          "x": 300,
          "y": 1130
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e92f0fca-58c2-446a-8d5f-c9f3fb8ad05d
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: e92f0fca-58c2-446a-8d5f-c9f3fb8ad05d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 310,
          "y": 1640
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      socassigned:
        simple: "0"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 0b6c0d4e-e98b-4a22-8426-3edf9c8833d3
      iscommand: true
      name: Set field SOCAssigned
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 0b6c0d4e-e98b-4a22-8426-3edf9c8833d3
    timertriggers:
    - action: stop
      fieldname: demoslatimer
    type: regular
    view: |-
      {
        "position": {
          "x": 310,
          "y": 1480
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "4_3_#default#": 0.11
    },
    "paper": {
      "dimensions": {
        "height": 1655,
        "width": 1810,
        "x": -30,
        "y": 50
      }
    }
  }
