contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 5472d107-4afc-4826-86f7-f6bb856b9069
inputs: []
name: DemoJiraTicketCreation
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 786477b3-3338-45c4-83b3-c8045cc27505
      iscommand: false
      name: ""
      version: -1
    taskid: 786477b3-3338-45c4-83b3-c8045cc27505
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 2
    scriptarguments:
      assignee:
        simple: Suresh
      description:
        simple: Demo Test Jira
      issueTypeName:
        simple: Task
      labels:
        simple: test
      priority:
        simple: "3"
      projectName:
        simple: XSOARDemo
      summary:
        simple: 'This is test Jira Issue '
      using:
        simple: jira-v2_instance_4
    separatecontext: false
    skipunavailable: false
    task:
      brand: jira-v2
      description: Creates a new issue in Jira.
      id: 6a6e41e4-2a44-4dcf-81bd-be5ce0d72524
      iscommand: true
      name: Create JIRA Ticket
      script: jira-v2|||jira-create-issue
      type: regular
      version: -1
    taskid: 6a6e41e4-2a44-4dcf-81bd-be5ce0d72524
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      dbotMirrorDirection:
        simple: Both
      dbotMirrorId:
        simple: ${Ticket.Id}
      dbotMirrorInstance:
        simple: jira-v2_instance_4
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: ff6fc8bd-10e5-43fd-829a-d04d7de40adf
      iscommand: true
      name: Set JIRA fields
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: ff6fc8bd-10e5-43fd-829a-d04d7de40adf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 445,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
