contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: cb220948-7059-472d-8a90-30818d7613f1
inputs: []
name: 'JLR DormantAccounts '
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cf6738b5-ec66-48dc-8612-8e33ca2a1cd0
      iscommand: false
      name: ""
      version: -1
    taskid: cf6738b5-ec66-48dc-8612-8e33ca2a1cd0
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 460,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    scriptarguments:
      SponserEmail:
        complex:
          accessor: SEmail
          root: ParseCSV.ParsedCSV
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8868b58b-d4c0-499b-8cbf-c38c3ce1a226
      iscommand: false
      name: Demo - Dormant Accounts
      playbookId: 761f5876-98c7-4bd9-8fa6-1e2d6887d56e
      type: playbook
      version: -1
    taskid: 8868b58b-d4c0-499b-8cbf-c38c3ce1a226
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 460,
          "y": 380
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This script will parse a CSV file and place the unique IPs, Domains
        and Hashes into the context.
      id: b0c75d5e-42aa-40ec-8909-91c1506d2938
      iscommand: false
      name: Parse the CSV file
      script: ParseCSV
      type: regular
      version: -1
    taskid: b0c75d5e-42aa-40ec-8909-91c1506d2938
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 200
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 425,
        "width": 380,
        "x": 460,
        "y": 50
      }
    }
  }
