contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 7d948c49-d49b-4af4-8536-94e43118faec
inputs: []
name: qwqwe
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b230065c-1ccc-4d78-8e11-a78cd6ea0749
      iscommand: false
      name: ""
      version: -1
    taskid: b230065c-1ccc-4d78-8e11-a78cd6ea0749
    timertriggers: []
    type: start
version: -1
