contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: afdf5a1d-17e0-4d01-8fec-f7d7fc09a7e9
inputs: []
name: email send v1
outputs: []
quiet: true
sourceplaybookid: 3a4f4315-6e77-4b29-8799-c922921edb01
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 30567d35-94f0-4c8c-880a-44258fa0d366
      iscommand: false
      name: ""
      version: -1
    taskid: 30567d35-94f0-4c8c-880a-44258fa0d366
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 480,
          "y": 65
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      emailnewbody:
        simple: |-
          <!DOCTYPE html>
          <html>

          <table>
          <thead>
          <tr>
          <th>ID</th>
          <th>CSPID</th>
          <th>Email</th>
          <th>SponserID</th>
          <th>SEmail</th>
          </tr>
          </thead>

          <tbody>
          <tr>
          <td>4</td>
          <td>emp123</td>
          <td>test@test.com</td>
          <td>123</td>
          <td>cortexxsoar2023@gmail.com</td>
          </tr>

          <tr>
          <td>3</td>
          <td>emp789</td>
          <td>def@test.com</td>
          <td>123</td>
          <td>cortexxsoar2023@gmail.com</td>
          </tr>

          <tr>
          <td>5</td>
          <td>emp1213</td>
          <td>jkl@test.com</td>
          <td>123</td>
          <td>cortexxsoar2023@gmail.com</td>
          </tr>
          </tbody>
          </table>

          </body>
          </html>
      emailnewrecipients:
        simple: sua@paloaltonetworks.com
      emailnewsubject:
        simple: Test Email Communication 1
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 95adbe6d-1f2f-4943-8a77-5103a560fc4c
      iscommand: true
      name: Set Incident Fields
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 95adbe6d-1f2f-4943-8a77-5103a560fc4c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 575
        }
      }
  "2":
    continueonerrortype: ""
    evidencedata:
      customfields: {}
      description:
        simple: User Email Communication
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 2
    scriptarguments:
      mail_sender_instance:
        simple: Gmail Single User_instance_1
      new_thread:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Send email reply
        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 86181bfd-e8fc-4042-8b73-8c358c1990b5
      iscommand: false
      name: Send Email
      script: SendEmailReply
      type: regular
      version: -1
    taskid: 86181bfd-e8fc-4042-8b73-8c358c1990b5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 750
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      sla:
        simple: "600"
      slaField:
        simple: demosla
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 49d9e8be-4951-4601-8e95-239265206f36
      iscommand: true
      name: Set SLA
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 49d9e8be-4951-4601-8e95-239265206f36
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d0151aaa-7898-4b1a-8c42-fcb401c2e9bc
      iscommand: false
      name: wait for user response
      tags:
      - userreply2
      type: regular
      version: -1
    taskid: d0151aaa-7898-4b1a-8c42-fcb401c2e9bc
    timertriggers:
    - action: start
      fieldname: demosla
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 225
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: true
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "60"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds.
      id: e097216f-c7cd-4c16-8257-fe3895f74ebc
      iscommand: false
      name: Sleep 1 min+
      script: Sleep
      type: regular
      version: -1
    taskid: e097216f-c7cd-4c16-8257-fe3895f74ebc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 910
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: email-${incident.id}
      timeout:
        simple: "500"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Demisto Lock
      description: Gets a specific lock. If the lock doesn't exist, it creates one.
        If the lock is already in use, the command waits until the lock is released
        or until timeout is reached. If timeout is reached and the lock hasn't been
        released, the command fails to get the lock.
      id: 44943f86-e1e6-4ccb-8888-7098dd209bb5
      iscommand: true
      name: demisto lock
      script: Demisto Lock|||demisto-lock-get
      type: regular
      version: -1
    taskid: 44943f86-e1e6-4ccb-8888-7098dd209bb5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 400
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: email-${incident.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Demisto Lock
      description: Release a lock
      id: 2b6f9845-043a-488b-8545-b810e9d39e23
      iscommand: true
      name: demisto release lock
      script: Demisto Lock|||demisto-lock-release
      type: regular
      version: -1
    taskid: 2b6f9845-043a-488b-8545-b810e9d39e23
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 470,
          "y": 1090
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6be69657-8c23-479d-865d-70f15b3eb031
      iscommand: false
      name: end
      type: title
      version: -1
    taskid: 6be69657-8c23-479d-865d-70f15b3eb031
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 460,
          "y": 1330
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1345,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
