contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 268f7745-9661-4ce1-8a03-65e8529591c0
inputs: []
name: email send v3
outputs: []
quiet: true
sourceplaybookid: 3a4f4315-6e77-4b29-8799-c922921edb01
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fbd21444-8234-4821-836c-9a54a9edeb61
      iscommand: false
      name: ""
      version: -1
    taskid: fbd21444-8234-4821-836c-9a54a9edeb61
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 130,
          "y": -690
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      emailnewbody:
        simple: |-
          <!DOCTYPE html>
          <html>

          <table>
          <thead>
          <tr>
          <th>ID</th>
          <th>CSPID</th>
          <th>Email</th>
          <th>SponserID</th>
          <th>SEmail</th>
          </tr>
          </thead>

          <tbody>
          <tr>
          <td>4</td>
          <td>emp123</td>
          <td>test@test.com</td>
          <td>123</td>
          <td>cortexxsoar2023@gmail.com</td>
          </tr>

          <tr>
          <td>3</td>
          <td>emp789</td>
          <td>def@test.com</td>
          <td>123</td>
          <td>cortexxsoar2023@gmail.com</td>
          </tr>

          </tbody>
          </table>

          </body>
          </html>
      emailnewrecipients:
        simple: cortexxsoar2023@paloaltonetworks.com
      emailnewsubject:
        simple: Test Email Communication 3
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 021c9550-1a4c-458b-8dbb-a2fb8e6e6cf0
      iscommand: true
      name: Set Incident Fields
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 021c9550-1a4c-458b-8dbb-a2fb8e6e6cf0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 110,
          "y": -130
        }
      }
  "2":
    continueonerrortype: ""
    evidencedata:
      customfields: {}
      description:
        simple: User Email Communication
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 2
    scriptarguments:
      mail_sender_instance:
        simple: Gmail Single User_instance_1
      new_thread:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Send email reply
        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 505b0b24-9364-4060-8d50-de6eedc8b65d
      iscommand: false
      name: Send Email
      script: SendEmailReply
      type: regular
      version: -1
    taskid: 505b0b24-9364-4060-8d50-de6eedc8b65d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 130,
          "y": 130
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      sla:
        simple: "600"
      slaField:
        simple: demosla
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 64c96bc1-77f1-40b3-8b42-1a7b19e21e67
      iscommand: true
      name: Set SLA
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 64c96bc1-77f1-40b3-8b42-1a7b19e21e67
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -430,
          "y": 670
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d68fae89-d5f9-4fe7-8402-9f525c694828
      iscommand: false
      name: wait for user response
      tags:
      - userreply2
      type: regular
      version: -1
    taskid: d68fae89-d5f9-4fe7-8402-9f525c694828
    timertriggers:
    - action: start
      fieldname: demosla
    type: regular
    view: |-
      {
        "position": {
          "x": -440,
          "y": 840
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: true
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "60"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds.
      id: 235e5425-d4ca-42c9-8fa9-c986f3771ea9
      iscommand: false
      name: Sleep 1 sec
      script: Sleep
      type: regular
      version: -1
    taskid: 235e5425-d4ca-42c9-8fa9-c986f3771ea9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 110,
          "y": 340
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: email-${incident.id}
      timeout:
        simple: "500"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Demisto Lock
      description: Gets a specific lock. If the lock doesn't exist, it creates one.
        If the lock is already in use, the command waits until the lock is released
        or until timeout is reached. If timeout is reached and the lock hasn't been
        released, the command fails to get the lock.
      id: 317df1da-b4de-4bac-8238-f812be0f1156
      iscommand: true
      name: demisto lock
      script: Demisto Lock|||demisto-lock-get
      type: regular
      version: -1
    taskid: 317df1da-b4de-4bac-8238-f812be0f1156
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 110,
          "y": -380
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: email-${incident.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Demisto Lock
      description: Release a lock
      id: 090c1764-f989-4e22-8dd7-d6e1e4bbee17
      iscommand: true
      name: demisto release lock
      script: Demisto Lock|||demisto-lock-release
      type: regular
      version: -1
    taskid: 090c1764-f989-4e22-8dd7-d6e1e4bbee17
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 110,
          "y": 525
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a70e1cbd-50a3-4af2-80ec-808675a1f93b
      iscommand: false
      name: end
      type: title
      version: -1
    taskid: a70e1cbd-50a3-4af2-80ec-808675a1f93b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 110,
          "y": 790
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1625,
        "width": 950,
        "x": -440,
        "y": -690
      }
    }
  }
