contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: fb4716be-86c0-48c4-8d2f-80c9c99952bb
inputs: []
name: Demo - Sub Playbook Output
outputs:
- contextPath: Data
  description: This will not take any context keys, we just need provide the description
    of Context Path (Data)
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 711ad11f-539e-4581-8590-44d196d942a2
      iscommand: false
      name: ""
      version: -1
    taskid: 711ad11f-539e-4581-8590-44d196d942a2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 460,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Test Task 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: e3809ca4-ebee-4285-82e9-50a7d7c9688b
      iscommand: false
      name: Print Task 2
      script: Print
      type: regular
      version: -1
    taskid: e3809ca4-ebee-4285-82e9-50a7d7c9688b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 720
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 2
    scriptarguments:
      ip:
        simple: ${inputs.IP }
      using:
        simple: VirusTotal (API v3)_instance_1
    separatecontext: false
    skipunavailable: false
    task:
      brand: VirusTotal (API v3)
      description: Checks the reputation of an IP address.
      id: f1ab3c8a-4c02-4b7f-8590-3932bbbd33d2
      iscommand: true
      name: Check IP reputation
      script: VirusTotal (API v3)|||ip
      type: regular
      version: -1
    taskid: f1ab3c8a-4c02-4b7f-8590-3932bbbd33d2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 960,
          "y": 180
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      domain:
        simple: google.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: VirusTotal (API v3)
      description: Checks the reputation of a domain.
      id: a03c46f2-71ff-458f-817d-cf9968898a03
      iscommand: true
      name: Check Domain reputation
      script: VirusTotal (API v3)|||domain
      type: regular
      version: -1
    taskid: a03c46f2-71ff-458f-817d-cf9968898a03
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1060,
          "y": 390
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      append:
        simple: "true"
      ignore-outputs:
        simple: "false"
      key:
        simple: Data
      value:
        simple: Test
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 49e0b559-33ee-4d93-8932-cecd3501275a
      iscommand: false
      name: Set Data
      script: Set
      type: regular
      version: -1
    taskid: 49e0b559-33ee-4d93-8932-cecd3501275a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 190
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 1000,
        "x": 440,
        "y": 50
      }
    }
  }
