contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 99767e53-0ad7-472f-81d5-9e569b157a28
inputs:
- description: ""
  key: Data
  playbookInputQuery: null
  required: false
  value:
    simple: ${ParseExcel.[0]}
name: Set Incident Data
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cbdb68ea-405f-4f40-83f9-0d24ba32d779
      iscommand: false
      name: ""
      version: -1
    taskid: cbdb68ea-405f-4f40-83f9-0d24ba32d779
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 20
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: violationid:${inputs.Data.ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Searches Demisto incidents. A summarized version of this scrips is avilable with the summarizedversion argument.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 1c0a3d20-1ea9-49fe-8cbf-08d22d72e41e
      iscommand: false
      name: search incident with violation id
      script: SearchIncidentsV2
      type: regular
      version: -1
    taskid: 1c0a3d20-1ea9-49fe-8cbf-08d22d72e41e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      acknowleged:
        complex:
          accessor: Acknowleged}
          filters:
          - - left:
                iscontext: true
                value:
                  simple: ${inputs.Data.ID}
              operator: isEqualString
              right:
                value:
                  simple: ${incident.violationid}
          root: ${inputs.Data
      closurecategory:
        complex:
          accessor: Closure Category
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.Data.ID
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: ${incident.violationid}
          root: inputs.Data
      closurenotes:
        complex:
          accessor: Closure Notes}
          filters:
          - - left:
                iscontext: true
                value:
                  simple: ${inputs.Data.ID}
              operator: isEqualString
              right:
                value:
                  simple: ${incident.violationid}
          root: ${inputs.Data
      id:
        simple: ${foundIncidents.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: cb2bc1fc-a3fb-48e2-8d91-ed7303e8404e
      iscommand: true
      name: update the incident
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: cb2bc1fc-a3fb-48e2-8d91-ed7303e8404e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 390
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: ${foundIncidents.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 238e7cf2-f01c-48be-82e2-4cfafa57adcd
      iscommand: true
      name: Close investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 238e7cf2-f01c-48be-82e2-4cfafa57adcd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 630
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 705,
        "width": 380,
        "x": 450,
        "y": 20
      }
    }
  }
