contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: a1fe2f53-7773-4521-83e3-ab3eb51af944
inputs:
- description: ""
  key: IPFields
  playbookInputQuery: null
  required: false
  value:
    simple: sourceip,destinationip
name: sample qradar playbook
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9f391347-de71-4582-8d05-0293da3d944f
      iscommand: false
      name: ""
      version: -1
    taskid: 9f391347-de71-4582-8d05-0293da3d944f
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    note: false
    quietmode: 0
    scriptarguments:
      interval:
        simple: "1"
      query_expression:
        complex:
          root: inputs.IPFields
          transformers:
          - args:
              join:
                value:
                  simple: =
              list2:
                iscontext: true
                value:
                  simple: IP
            operator: ProductJoin
          - args:
              separator:
                value:
                  simple: ''' OR "'
            operator: join
          - args:
              regex:
                value:
                  simple: =
              replaceWith:
                value:
                  simple: '" = '''
            operator: replaceMatch
          - args:
              prefix:
                value:
                  simple: ' from events where "'
              suffix: {}
            operator: concat
          - args:
              prefix:
                value:
                  simple: date, sourceip, destinationip
              suffix: {}
            operator: concat
          - args:
              prefix: {}
              suffix:
                value:
                  simple: ''' '
            operator: concat
          - args:
              prefix:
                value:
                  simple: 'select '
              suffix:
                value:
                  simple: last 1 minutes
            operator: concat
      range:
        simple: 0-5
      timeout:
        simple: "600"
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: This playbook runs a QRadar query and return its results to the
        context.
      id: 46294ca7-9c95-442d-820f-ca9ca81e82f1
      iscommand: false
      name: QRadarFullSearch
      playbookId: QRadarFullSearch
      type: playbook
      version: -1
    taskid: 46294ca7-9c95-442d-820f-ca9ca81e82f1
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
