contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 9a6bc1f6-2bd0-452a-8d9f-ef3d6e9e5055
inputs: []
name: verify SSL main playbook
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ebb16193-6408-4943-8ce6-e6c4d540162d
      iscommand: false
      name: ""
      version: -1
    taskid: ebb16193-6408-4943-8ce6-e6c4d540162d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: urlList=.
      list_name:
        simple: urls-list
      parse_all:
        simple: "True"
      value:
        complex:
          accessor: urls-list}
          root: ${lists
          transformers:
          - args:
              delimiter:
                value:
                  simple: ','
            operator: split
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Parses a list by header and value.
      id: 8623be3e-93b4-47c1-8fe7-be3f9e5c530f
      iscommand: false
      name: get from list
      script: GetListRow
      type: regular
      version: -1
    taskid: 8623be3e-93b4-47c1-8fe7-be3f9e5c530f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    scriptarguments:
      entry:
        simple: ${getListRow.Result.Results}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 56322f78-95b2-4e5b-824b-96ff18bb6730
      iscommand: false
      name: verify SSL sub playbook
      playbookId: f2f82edf-9118-4f3e-8ca4-b68b0240e31d
      type: playbook
      version: -1
    taskid: 56322f78-95b2-4e5b-824b-96ff18bb6730
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 415,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
