contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 169e7e6a-9d54-467c-84ea-a705c1212888
inputs:
- description: ""
  key: Users
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: Hostname
  playbookInputQuery: null
  required: false
  value: {}
name: Demo Check List
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d8bafbd9-5a89-4b5a-877d-43b375aa52a4
      iscommand: false
      name: ""
      version: -1
    taskid: d8bafbd9-5a89-4b5a-877d-43b375aa52a4
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    reputationcalc: 1
    scriptarguments:
      key:
        simple: Users
      value:
        simple: ${inputs.Users}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Set a value in context under the key you entered. If no value is entered, the script doesn't do anything.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      id: 1899bafe-8504-4d87-8130-be9cb9c0eec2
      iscommand: false
      name: Print users
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: 1899bafe-8504-4d87-8130-be9cb9c0eec2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 190
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      attachIDs:
        simple: ${FileEntryIDs}
    separatecontext: false
    skipunavailable: false
    task:
      brand: EWSO365
      description: Sends an email.
      id: 0893b86f-deb0-4967-88f0-571854444bb6
      iscommand: true
      name: Send Mail
      script: EWSO365|||send-mail
      type: regular
      version: -1
    taskid: 0893b86f-deb0-4967-88f0-571854444bb6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 410
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 455,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
