contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: d93777f8-e033-4c91-8a63-749264d3b624
inputs: []
name: qradar sample playbook
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 61056310-b7d4-4d46-8547-5fdef99e1cf2
      iscommand: false
      name: ""
      version: -1
    taskid: 61056310-b7d4-4d46-8547-5fdef99e1cf2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Please upload a file
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: attachments
      sender: ""
      title: IOC file
      totalanswers: 0
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: Please upload a file
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: false
        retriescount: 2
        retriesinterval: 360
      to: null
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 980e5774-b32d-4f85-84f3-7dcf5eafa364
      iscommand: false
      name: Upload a file
      type: collection
      version: -1
    taskid: 980e5774-b32d-4f85-84f3-7dcf5eafa364
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      entryID:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: File.Extension
              operator: isEqualString
              right:
                value:
                  simple: TXT
            - left:
                iscontext: true
                value:
                  simple: File.Extension
              operator: isEqualString
              right:
                value:
                  simple: txt
          root: File
          transformers:
          - args:
              field:
                value:
                  simple: EntryID
            operator: getField
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.extract.indicators
      id: 702e0578-7a01-408b-878a-3a8f1a69bff3
      iscommand: true
      name: extract indicators from a file
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: 702e0578-7a01-408b-878a-3a8f1a69bff3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs.paloaltonetworks.com/cortex/cortex-xsoar/6-2/cortex-xsoar-admin/playbooks/automations.html
      id: de0ce982-85e2-47d7-8a5d-f64f1e3c44a1
      iscommand: false
      name: delete context
      script: DeleteContext
      type: regular
      version: -1
    taskid: de0ce982-85e2-47d7-8a5d-f64f1e3c44a1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    scriptarguments:
      IPAddress:
        simple: ${ExtractedIndicators.IP}
      InvestigationIPFields:
        simple: sourceip,destinationip
      InvestigationUserFields:
        simple: username
      QradarIPfield:
        simple: sourceip,destinationip
      SHA256:
        simple: ${ExtractedIndicators.File}
      TimeFrame:
        simple: LAST 7 DAYS
      URL:
        simple: ${ExtractedIndicators.URL}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: 'The Playbook queries QRadar SIEM for indicators such as file hashes,
        IP addresses, domains, or urls. '
      id: daa1b3e1-f180-4138-8d91-19efa08dd5fb
      iscommand: false
      name: QRadar Indicator Hunting V2_copy
      playbookId: fee733df-d9c0-4df4-83dc-79b481899479
      type: playbook
      version: -1
    taskid: daa1b3e1-f180-4138-8d91-19efa08dd5fb
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 770
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 815,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
