contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 7ad4f49d-0d1b-415a-8967-88acfbb88c37
inputs: []
name: sample playbook axis
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2cd2c5ab-9ec0-439c-8274-c7156361686d
      iscommand: false
      name: ""
      version: -1
    taskid: 2cd2c5ab-9ec0-439c-8274-c7156361686d
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: sd
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: shortText
      sender: ""
      title: sd
      totalanswers: 0
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        complex:
          accessor: details
          root: incident
          transformers:
          - args:
              regex:
                value:
                  simple: \n
              replaceWith:
                value:
                  simple: <br>
            operator: replaceMatch
          - args:
              prefix:
                value:
                  simple: "<!DOCTYPE html>\n<html>\n<body>\n\n<h2>An unordered HTML
                    list</h2>\n\n<ul>\n  <li>Coffee</li>\n  <li>Tea</li>\n  <li>Milk</li>\n</ul>
                    \n"
              suffix:
                value:
                  simple: |2-

                    </body>
                    </html>
            operator: concat
      cc: null
      format: html
      methods:
      - email
      subject:
        simple: ss
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
        simple: shapatil@paloaltonetworks.com
    note: false
    quietmode: 0
    scriptarguments:
      htmlBody:
        simple: "<!DOCTYPE html>\n<html>\n<body>\n\n<h2>An unordered HTML list</h2>\n\n<ul>\n
          \ <li>Coffee</li>\n  <li>Tea</li>\n  <li>Milk</li>\n</ul>  \n\n${incident.details}\n\n</body>\n</html>"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends an email using Microsoft Graph.
      id: 753a7994-f0e8-449a-8ba3-3be105adaa0f
      iscommand: false
      name: task A
      type: collection
      version: -1
    taskid: 753a7994-f0e8-449a-8ba3-3be105adaa0f
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 450,
          "y": 255
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 300,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
